#line 2 "libpgn_parser_a-pgn_scanner.c"

#line 4 "libpgn_parser_a-pgn_scanner.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define yy_create_buffer pgn_create_buffer
#define yy_delete_buffer pgn_delete_buffer
#define yy_flex_debug pgn_flex_debug
#define yy_init_buffer pgn_init_buffer
#define yy_flush_buffer pgn_flush_buffer
#define yy_load_buffer_state pgn_load_buffer_state
#define yy_switch_to_buffer pgn_switch_to_buffer
#define yyin pgnin
#define yyleng pgnleng
#define yylex pgnlex
#define yylineno pgnlineno
#define yyout pgnout
#define yyrestart pgnrestart
#define yytext pgntext
#define yywrap pgnwrap
#define yyalloc pgnalloc
#define yyrealloc pgnrealloc
#define yyfree pgnfree

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 34
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;
#endif /* ! C99 */

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE pgnrestart(pgnin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#define YY_BUF_SIZE 16384
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

extern int pgnleng;

extern FILE *pgnin, *pgnout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up pgntext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up pgntext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 * Given that the standard has decreed that size_t exists since 1989,
 * I guess we can afford to depend on it. Manoj.
 */

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via pgnrestart()), so that the user can continue scanning by
	 * just pointing pgnin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when pgntext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int pgnleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow pgnwrap()'s to do buffer switches
 * instead of setting up a fresh pgnin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void pgnrestart (FILE *input_file  );
void pgn_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE pgn_create_buffer (FILE *file,int size  );
void pgn_delete_buffer (YY_BUFFER_STATE b  );
void pgn_flush_buffer (YY_BUFFER_STATE b  );
void pgnpush_buffer_state (YY_BUFFER_STATE new_buffer  );
void pgnpop_buffer_state (void );

static void pgnensure_buffer_stack (void );
static void pgn_load_buffer_state (void );
static void pgn_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER pgn_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE pgn_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE pgn_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE pgn_scan_bytes (yyconst char *bytes,int len  );

void *pgnalloc (yy_size_t  );
void *pgnrealloc (void *,yy_size_t  );
void pgnfree (void *  );

#define yy_new_buffer pgn_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        pgnensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            pgn_create_buffer(pgnin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        pgnensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            pgn_create_buffer(pgnin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

typedef unsigned char YY_CHAR;

FILE *pgnin = (FILE *) 0, *pgnout = (FILE *) 0;

typedef int yy_state_type;

extern int pgnlineno;

int pgnlineno = 1;

extern char *pgntext;
#define yytext_ptr pgntext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up pgntext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	pgnleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 22
#define YY_END_OF_BUFFER 23
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[158] =
    {   0,
        0,    0,   23,   21,   17,   20,   15,   21,   15,   15,
       15,   21,   21,   21,   17,   15,   16,   15,   13,   15,
       15,   15,    0,   19,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,   18,   16,   14,   15,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,   15,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,   15,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,   15,
       12,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,

        0,    0,    0,    0,    0,    0,    0,    0,    0,    5,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        3,    0,    0,    0,    0,    0,    8,    0,    0,    0,
        0,    0,    2,    4,    0,    0,    7,    0,    0,   11,
        0,    6,    0,    0,    0,    0,    0,   10,    0,    0,
        0,    1,    0,    0,    0,    9,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    1,    5,    1,    1,    1,    1,    1,    1,
        1,    1,    6,    1,    7,    8,    9,   10,   11,   12,
       13,   13,   13,   13,   13,   13,   13,    1,   14,    1,
        1,    1,    1,    1,   15,   16,   17,   18,   19,   20,
       21,   22,   23,   21,   24,   25,   26,   27,   28,   21,
       21,   29,   30,   31,   32,   33,   34,   21,   21,   21,
       35,    1,   36,    1,    1,    1,   37,   38,   39,   40,

       41,   42,   21,   43,   44,   21,   45,   46,   47,   48,
       49,   21,   21,   50,   51,   52,   53,   54,   55,   21,
       21,   21,   56,    1,   57,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[58] =
    {   0,
        1,    1,    1,    2,    1,    3,    3,    1,    3,    3,
        3,    3,    3,    1,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    1,    1,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    1,    1
    } ;

static yyconst flex_int16_t yy_base[175] =
    {   0,
        0,   57,  406,  407,    5,  407,    0,  397,    8,   15,
       21,  401,  100,  346,   35,    0,  394,  390,  407,   30,
      390,  387,  395,  407,   26,   41,  393,   40,   42,   44,
       45,   68,  152,   74,  153,  339,  407,  407,    0,  388,
       46,  131,  155,   48,  157,  156,   50,  132,  158,  159,
      161,  163,  383,  388,  169,  164,  165,  168,  388,  162,
      173,  183,  187,  176,  170,  382,  385,  353,  174,  204,
      384,  208,   77,  210,  213,  383,  215,  221,  223,  374,
      407,  225,  381,   79,  380,  378,  219,  378,   93,  228,
      239,  377,  226,   98,  375,  100,  374,  342,  373,  102,

      371,  233,  237,  104,  241,  370,  369,  337,  318,  407,
      242,  301,  300,  268,  248,  299,  297,  257,  296,  263,
      407,  292,  259,  289,  288,  256,  407,  240,  268,  286,
      252,  281,  407,  407,  269,  231,  407,  247,  260,  407,
      276,  407,  250,  228,  146,  105,   95,  407,   90,   54,
      278,  407,   83,   71,   11,  407,  407,  307,  309,  313,
      317,  320,  324,  328,  332,  336,  340,  344,  348,  352,
      356,  360,  364,  368
    } ;

static yyconst flex_int16_t yy_def[175] =
    {   0,
      158,  158,  157,  157,  157,  157,  159,  157,  159,  159,
      159,  160,  157,  161,  157,  159,  157,  159,  157,  159,
      159,  159,  160,  157,  162,  162,  162,  162,  162,  162,
      162,  162,  162,  162,  162,  161,  157,  157,  159,  159,
      157,  162,  162,  162,  162,  162,  162,  162,  162,  162,
      162,  162,  159,  163,  162,  162,  162,  162,  162,  162,
      162,  162,  162,  162,  162,  159,  163,  157,  162,  162,
      162,  162,  157,  162,  162,  162,  162,  162,  162,  159,
      157,  162,  162,  157,  162,  164,  162,  162,  157,  162,
      162,  162,  162,  157,  165,  157,  164,  157,  162,  157,

      166,  162,  162,  157,  162,  167,  165,  157,  168,  157,
      157,  169,  166,  157,  162,  162,  170,  162,  167,  157,
      157,  168,  157,  171,  169,  157,  157,  162,  157,  170,
      157,  162,  157,  157,  171,  157,  157,  162,  172,  157,
      157,  157,  162,  172,  157,  173,  162,  157,  173,  157,
      157,  157,  174,  174,  157,  157,    0,  157,  157,  157,
      157,  157,  157,  157,  157,  157,  157,  157,  157,  157,
      157,  157,  157,  157
    } ;

static yyconst flex_int16_t yy_nxt[465] =
    {   0,
        4,    5,    6,    5,    4,  157,   15,    8,   15,    9,
       10,   11,   11,   12,   18,   19,  157,   20,   20,   20,
       20,   21,   19,   22,   20,   20,   20,   20,   19,   41,
       20,   20,   20,   20,   13,    4,   15,   19,   15,   20,
       20,   20,   20,   41,   41,   41,  156,   41,   41,   41,
       54,   41,   42,   41,   44,   14,    4,    4,    5,    6,
        5,    4,   46,   47,    8,   43,    9,   10,   11,   11,
       12,   41,   48,   42,   45,  155,   44,   41,   57,   60,
       73,   86,   84,   95,   46,   47,   43,  155,   51,  152,
       49,   13,    4,   48,  150,   45,   89,  101,  151,   57,

       60,   94,  106,   96,  109,  100,  112,  104,  117,  150,
       51,   49,   14,    4,   25,   26,   27,   28,   29,   30,
       27,   27,   27,   27,   27,   27,   27,   27,   31,   32,
       33,   27,   34,   35,   41,   41,   25,   26,   27,   28,
       29,   30,   27,   27,   27,   27,   27,   27,   27,   31,
       32,   33,   27,   34,   35,   41,   41,   55,   41,   41,
       41,   41,   41,   61,   41,   41,   41,   41,   41,   56,
       50,   41,   41,   41,   52,   58,   41,   41,   55,   41,
       70,  148,   59,   71,   61,   65,   41,   63,   62,   64,
       41,   56,   50,   74,   72,   52,   69,   58,   78,   75,

       79,   76,   70,   59,   82,   71,   65,   41,   63,   62,
       64,   41,   77,   41,   74,   72,   41,   69,   41,   78,
       75,   79,   41,   76,   41,   82,   41,   83,   41,   41,
       88,   41,  145,   77,   87,   91,   41,   90,   85,   93,
       41,   92,   41,   41,   41,  111,  124,  115,   83,   99,
       41,   41,   88,   41,  102,   87,  105,   91,   90,   85,
       41,   93,  138,   92,  145,  103,  142,  116,  118,  115,
       99,  129,  139,  136,  143,  102,  147,  105,  128,  141,
      146,  151,  153,  138,  141,  132,  103,  140,  116,  118,
      131,  137,  126,  136,  134,  143,  123,  147,  133,  128,

      120,  131,  129,  127,  114,  126,  132,    7,    7,    7,
        7,   16,   16,   23,   23,   23,   23,   36,   36,   36,
       36,   27,  123,   27,   67,   67,   67,   67,   97,   97,
       97,   97,  107,  107,  107,  107,  113,  113,  113,  113,
      119,  119,  119,  119,  122,  122,  122,  122,  125,  125,
      125,  125,  130,  130,  130,  130,  135,  135,  135,  135,
      144,  144,  144,  144,  149,  149,  149,  149,  154,  154,
      154,  154,  121,  108,  120,  114,  111,  110,   98,  108,
      104,  100,   98,   96,   94,   39,   89,   84,   81,   68,
       80,   73,   68,   66,   53,   37,   41,   24,   40,   39,

       39,   38,   37,   24,   17,  157,    3,  157,  157,  157,
      157,  157,  157,  157,  157,  157,  157,  157,  157,  157,
      157,  157,  157,  157,  157,  157,  157,  157,  157,  157,
      157,  157,  157,  157,  157,  157,  157,  157,  157,  157,
      157,  157,  157,  157,  157,  157,  157,  157,  157,  157,
      157,  157,  157,  157,  157,  157,  157,  157,  157,  157,
      157,  157,  157,  157
    } ;

static yyconst flex_int16_t yy_chk[465] =
    {   0,
        1,    1,    1,    1,    1,    0,    5,    1,    5,    1,
        1,    1,    1,    1,    9,    9,    0,    9,    9,    9,
        9,   10,   10,   10,   10,   10,   10,   10,   11,   25,
       11,   11,   11,   11,    1,    1,   15,   20,   15,   20,
       20,   20,   20,   28,   26,   29,  155,   30,   31,   41,
       41,   44,   25,   47,   28,    1,    1,    2,    2,    2,
        2,    2,   30,   31,    2,   26,    2,    2,    2,    2,
        2,   32,   31,   25,   29,  154,   28,   34,   44,   47,
       73,   73,   84,   84,   30,   31,   26,  153,   34,  150,
       32,    2,    2,   31,  149,   29,   89,   89,  147,   44,

       47,   94,   94,   96,   96,  100,  100,  104,  104,  146,
       34,   32,    2,    2,   13,   13,   13,   13,   13,   13,
       13,   13,   13,   13,   13,   13,   13,   13,   13,   13,
       13,   13,   13,   13,   42,   48,   13,   13,   13,   13,
       13,   13,   13,   13,   13,   13,   13,   13,   13,   13,
       13,   13,   13,   13,   13,   33,   35,   42,   43,   46,
       45,   49,   50,   48,   51,   60,   52,   56,   57,   43,
       33,   58,   55,   65,   35,   45,   61,   69,   42,   64,
       56,  145,   46,   57,   48,   52,   62,   50,   49,   51,
       63,   43,   33,   60,   58,   35,   55,   45,   64,   61,

       65,   62,   56,   46,   69,   57,   52,   70,   50,   49,
       51,   72,   63,   74,   60,   58,   75,   55,   77,   64,
       61,   65,   87,   62,   78,   69,   79,   70,   82,   93,
       75,   90,  144,   63,   74,   78,  102,   77,   72,   82,
      103,   79,   91,  128,  105,  111,  111,  102,   70,   87,
      138,  115,   75,  143,   90,   74,   93,   78,   77,   72,
      118,   82,  128,   79,  139,   91,  136,  103,  105,  102,
       87,  129,  129,  135,  138,   90,  143,   93,  115,  141,
      141,  151,  151,  128,  132,  118,   91,  131,  103,  105,
      130,  126,  125,  124,  123,  138,  122,  143,  120,  115,

      119,  117,  116,  114,  113,  112,  118,  158,  158,  158,
      158,  159,  159,  160,  160,  160,  160,  161,  161,  161,
      161,  162,  109,  162,  163,  163,  163,  163,  164,  164,
      164,  164,  165,  165,  165,  165,  166,  166,  166,  166,
      167,  167,  167,  167,  168,  168,  168,  168,  169,  169,
      169,  169,  170,  170,  170,  170,  171,  171,  171,  171,
      172,  172,  172,  172,  173,  173,  173,  173,  174,  174,
      174,  174,  108,  107,  106,  101,   99,   98,   97,   95,
       92,   88,   86,   85,   83,   80,   76,   71,   68,   67,
       66,   59,   54,   53,   40,   36,   27,   23,   22,   21,

       18,   17,   14,   12,    8,    3,  157,  157,  157,  157,
      157,  157,  157,  157,  157,  157,  157,  157,  157,  157,
      157,  157,  157,  157,  157,  157,  157,  157,  157,  157,
      157,  157,  157,  157,  157,  157,  157,  157,  157,  157,
      157,  157,  157,  157,  157,  157,  157,  157,  157,  157,
      157,  157,  157,  157,  157,  157,  157,  157,  157,  157,
      157,  157,  157,  157
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int pgn_flex_debug;
int pgn_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *pgntext;
#line 1 "pgn_scanner.l"
#line 2 "pgn_scanner.l"

/*
  This software is provided 'as-is', without any express or implied
  warranty.  In no event will the authors be held liable for any damages
  arising from the use of this software.
  Silvio Quadri 2010.
*/

#include <stdio.h>
#include "defines.h"
#include "pgn_scanner.h"


char* pgntag_event = NULL;
char* pgntag_site = NULL;
char* pgntag_date = NULL;
char* pgntag_round = NULL;
char* pgntag_white = NULL;
char* pgntag_black = NULL;
char* pgntag_result = NULL;
char* pgntag_termination = NULL;
char* pgntag_annotator = NULL;
char* pgntag_fen = NULL;

char* pgntag_variant = NULL;

char* pgnmoves = NULL;
int   pgnmvchcount = 0;
int   pgnmvchalloc = 0;

/* -------------------------------------------------------- */
int   pgnlineno;
int   pgncolno;

char* pgnerror = NULL;


char*   extracttag(char*);
void    addmove(char*);

int     pgnwrap(void){ return 1; }

#line 676 "libpgn_parser_a-pgn_scanner.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int pgnwrap (void );
#else
extern int pgnwrap (void );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  );
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO fwrite( pgntext, pgnleng, 1, pgnout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( pgnin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( pgnin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, pgnin))==0 && ferror(pgnin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(pgnin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int pgnlex (void);

#define YY_DECL int pgnlex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after pgntext and pgnleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 59 "pgn_scanner.l"


#line 832 "libpgn_parser_a-pgn_scanner.c"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! pgnin )
			pgnin = stdin;

		if ( ! pgnout )
			pgnout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			pgnensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				pgn_create_buffer(pgnin,YY_BUF_SIZE );
		}

		pgn_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of pgntext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 158 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_current_state != 157 );
		yy_cp = (yy_last_accepting_cpos);
		yy_current_state = (yy_last_accepting_state);

yy_find_action:
		yy_act = yy_accept[yy_current_state];

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
/* rule 1 can match eol */
YY_RULE_SETUP
#line 61 "pgn_scanner.l"
{  pgntag_annotator = extracttag( pgntext ); pgncolno += pgnleng; }
	YY_BREAK
case 2:
/* rule 2 can match eol */
YY_RULE_SETUP
#line 62 "pgn_scanner.l"
{  pgntag_black   = extracttag( pgntext ); pgncolno += pgnleng; }
	YY_BREAK
case 3:
/* rule 3 can match eol */
YY_RULE_SETUP
#line 63 "pgn_scanner.l"
{  pgntag_date    = extracttag( pgntext ); pgncolno += pgnleng; }
	YY_BREAK
case 4:
/* rule 4 can match eol */
YY_RULE_SETUP
#line 64 "pgn_scanner.l"
{  pgntag_event   = extracttag( pgntext ); pgncolno += pgnleng; }
	YY_BREAK
case 5:
/* rule 5 can match eol */
YY_RULE_SETUP
#line 65 "pgn_scanner.l"
{  pgntag_fen     = extracttag( pgntext ); pgncolno += pgnleng; }
	YY_BREAK
case 6:
/* rule 6 can match eol */
YY_RULE_SETUP
#line 66 "pgn_scanner.l"
{  pgntag_result  = extracttag( pgntext ); pgncolno += pgnleng; }
	YY_BREAK
case 7:
/* rule 7 can match eol */
YY_RULE_SETUP
#line 67 "pgn_scanner.l"
{  pgntag_round   = extracttag( pgntext ); pgncolno += pgnleng; }
	YY_BREAK
case 8:
/* rule 8 can match eol */
YY_RULE_SETUP
#line 68 "pgn_scanner.l"
{  pgntag_site    = extracttag( pgntext ); pgncolno += pgnleng; }
	YY_BREAK
case 9:
/* rule 9 can match eol */
YY_RULE_SETUP
#line 69 "pgn_scanner.l"
{  pgntag_termination = extracttag( pgntext ); pgncolno += pgnleng; }
	YY_BREAK
case 10:
/* rule 10 can match eol */
YY_RULE_SETUP
#line 70 "pgn_scanner.l"
{  pgntag_variant = extracttag( pgntext ); pgncolno += pgnleng; }
	YY_BREAK
case 11:
/* rule 11 can match eol */
YY_RULE_SETUP
#line 71 "pgn_scanner.l"
{  pgntag_white   = extracttag( pgntext ); pgncolno += pgnleng; }
	YY_BREAK
case 12:
/* rule 12 can match eol */
YY_RULE_SETUP
#line 72 "pgn_scanner.l"
{  printf( "Tag no reconocido en %d\n", pgnlineno );  pgncolno += pgnleng ; }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 74 "pgn_scanner.l"
{ /* Por ahora ignoro los numeros de movidas */ pgncolno += pgnleng; }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 75 "pgn_scanner.l"
pgncolno += pgnleng;
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 76 "pgn_scanner.l"
addmove( pgntext ); pgncolno += pgnleng ;
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 77 "pgn_scanner.l"
pgncolno += pgnleng ;
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 79 "pgn_scanner.l"
{ /* ignore whitespace */ pgncolno += pgnleng ; }
	YY_BREAK
case 18:
/* rule 18 can match eol */
YY_RULE_SETUP
#line 80 "pgn_scanner.l"
/* ignore comments */ pgncolno += pgnleng;
	YY_BREAK
case 19:
/* rule 19 can match eol */
YY_RULE_SETUP
#line 81 "pgn_scanner.l"
/* ignore comments */ pgncolno += pgnleng;
	YY_BREAK
case 20:
/* rule 20 can match eol */
YY_RULE_SETUP
#line 83 "pgn_scanner.l"
{ pgncolno = 1; pgnlineno ++; }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 86 "pgn_scanner.l"
{
                                  pgnerror = ALLOC( 256 );
                                  sprintf( pgnerror, "Caracter no reconocido (%c) Linea: %d, Col: %d", pgntext[0], pgnlineno, pgncolno );
                                  yyterminate();
                               };
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 92 "pgn_scanner.l"
ECHO;
	YY_BREAK
#line 1040 "libpgn_parser_a-pgn_scanner.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed pgnin at a new source and called
			 * pgnlex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = pgnin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_last_accepting_cpos);
				yy_current_state = (yy_last_accepting_state);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( pgnwrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * pgntext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of pgnlex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					pgnrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), (size_t) num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			pgnrestart(pgnin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) pgnrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 158 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 158 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 157);

	return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp )
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up pgntext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					pgnrestart(pgnin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( pgnwrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve pgntext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void pgnrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        pgnensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            pgn_create_buffer(pgnin,YY_BUF_SIZE );
	}

	pgn_init_buffer(YY_CURRENT_BUFFER,input_file );
	pgn_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void pgn_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		pgnpop_buffer_state();
	 *		pgnpush_buffer_state(new_buffer);
     */
	pgnensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	pgn_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (pgnwrap()) processing, but the only time this flag
	 * is looked at is after pgnwrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void pgn_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	pgnin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE pgn_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) pgnalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in pgn_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) pgnalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in pgn_create_buffer()" );

	b->yy_is_our_buffer = 1;

	pgn_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with pgn_create_buffer()
 * 
 */
    void pgn_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		pgnfree((void *) b->yy_ch_buf  );

	pgnfree((void *) b  );
}

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a pgnrestart() or at EOF.
 */
    static void pgn_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	pgn_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then pgn_init_buffer was _probably_
     * called from pgnrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void pgn_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		pgn_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void pgnpush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	pgnensure_buffer_stack();

	/* This block is copied from pgn_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from pgn_switch_to_buffer. */
	pgn_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void pgnpop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	pgn_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		pgn_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void pgnensure_buffer_stack (void)
{
	int num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)pgnalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in pgnensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)pgnrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in pgnensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE pgn_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) pgnalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in pgn_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	pgn_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to pgnlex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       pgn_scan_bytes() instead.
 */
YY_BUFFER_STATE pgn_scan_string (yyconst char * yystr )
{
    
	return pgn_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to pgnlex() will
 * scan from a @e copy of @a bytes.
 * @param bytes the byte buffer to scan
 * @param len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE pgn_scan_bytes  (yyconst char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) pgnalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in pgn_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = pgn_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in pgn_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up pgntext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		pgntext[pgnleng] = (yy_hold_char); \
		(yy_c_buf_p) = pgntext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		pgnleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int pgnget_lineno  (void)
{
        
    return pgnlineno;
}

/** Get the input stream.
 * 
 */
FILE *pgnget_in  (void)
{
        return pgnin;
}

/** Get the output stream.
 * 
 */
FILE *pgnget_out  (void)
{
        return pgnout;
}

/** Get the length of the current token.
 * 
 */
int pgnget_leng  (void)
{
        return pgnleng;
}

/** Get the current token.
 * 
 */

char *pgnget_text  (void)
{
        return pgntext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void pgnset_lineno (int  line_number )
{
    
    pgnlineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see pgn_switch_to_buffer
 */
void pgnset_in (FILE *  in_str )
{
        pgnin = in_str ;
}

void pgnset_out (FILE *  out_str )
{
        pgnout = out_str ;
}

int pgnget_debug  (void)
{
        return pgn_flex_debug;
}

void pgnset_debug (int  bdebug )
{
        pgn_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from pgnlex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    pgnin = stdin;
    pgnout = stdout;
#else
    pgnin = (FILE *) 0;
    pgnout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * pgnlex_init()
     */
    return 0;
}

/* pgnlex_destroy is for both reentrant and non-reentrant scanners. */
int pgnlex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		pgn_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		pgnpop_buffer_state();
	}

	/* Destroy the stack itself. */
	pgnfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * pgnlex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *pgnalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *pgnrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void pgnfree (void * ptr )
{
	free( (char *) ptr );	/* see pgnrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 92 "pgn_scanner.l"



char*  extracttag(char* line){
    char*  initquote = strchr( line, '"' );
    initquote ++;
    char*  endquote = strchr( initquote, '"' );
    endquote --;

    int  len = endquote - initquote + 1;
    char* ret = ALLOC( len + 1 );
    strncpy( ret, initquote, len );
    ret[len] = 0;
    return ret;
}

void    addmove(char* move){
    if( !pgnmoves ){ 
        pgnmoves = ALLOC( 32 ); 
        pgnmoves[0] = 0;
        pgnmvchcount = 0;
        pgnmvchalloc = 32;
     }
    int  len = strlen( move );
    if( pgnmvchcount + len + 1 >= pgnmvchalloc ){
        pgnmvchalloc += len + 32;
        pgnmoves = REALLOC( pgnmoves, pgnmvchalloc );
    }

    if( pgnmvchcount ){ 
        strcat( pgnmoves + pgnmvchcount, " " ); 
        len ++; 
    }
    strcat( pgnmoves + pgnmvchcount, move );
    pgnmvchcount += len;
}




#define  FREEVARIABLE(var) if( var ){ free( var ); var = NULL; }

void   freepgn( ){

    FREEVARIABLE( pgntag_event )
    FREEVARIABLE( pgntag_site )
    FREEVARIABLE( pgntag_date )
    FREEVARIABLE( pgntag_round )
    FREEVARIABLE( pgntag_white )
    FREEVARIABLE( pgntag_black )
    FREEVARIABLE( pgntag_result )
    FREEVARIABLE( pgntag_fen )
    FREEVARIABLE( pgntag_variant )
    FREEVARIABLE( pgntag_termination )
    FREEVARIABLE( pgnmoves )
    FREEVARIABLE( pgnerror )
    pgnmvchcount = 0;
    pgnmvchalloc = 0;
}


void   initpgn( ){
    freepgn( );
    pgnlineno = 1;
    pgncolno  = 0;
}

int   pgnscan_string(char* scan){
    initpgn();
    YY_BUFFER_STATE buf = pgn_scan_string(scan );
    pgn_switch_to_buffer(buf );
    int ret = pgnlex();
    return pgnerror ? 0 : 1;
}

int   pgnscan_file(FILE* file){
    initpgn();
    pgnin = file;
    int ret = pgnlex();
    return pgnerror ? 0 : 1 ;
}

int   pgnscan_fname(char* fname){
    initpgn();
    pgnin = fopen( fname, "r" ) ;
    if( !pgnin ) return;
    int ret = pgnlex();
    fclose( pgnin );
    return pgnerror ? 0 : 1 ;
}

