#line 2 "qgames_scanner.c"

#line 4 "qgames_scanner.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define yy_create_buffer qgz_create_buffer
#define yy_delete_buffer qgz_delete_buffer
#define yy_flex_debug qgz_flex_debug
#define yy_init_buffer qgz_init_buffer
#define yy_flush_buffer qgz_flush_buffer
#define yy_load_buffer_state qgz_load_buffer_state
#define yy_switch_to_buffer qgz_switch_to_buffer
#define yyin qgzin
#define yyleng qgzleng
#define yylex qgzlex
#define yylineno qgzlineno
#define yyout qgzout
#define yyrestart qgzrestart
#define yytext qgztext
#define yywrap qgzwrap
#define yyalloc qgzalloc
#define yyrealloc qgzrealloc
#define yyfree qgzfree

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 34
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;
#endif /* ! C99 */

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE qgzrestart(qgzin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#define YY_BUF_SIZE 16384
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

extern int qgzleng;

extern FILE *qgzin, *qgzout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE qgzlex. 
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-qgzlineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < qgzleng; ++yyl )\
                    if ( qgztext[yyl] == '\n' )\
                        --qgzlineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up qgztext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up qgztext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 * Given that the standard has decreed that size_t exists since 1989,
 * I guess we can afford to depend on it. Manoj.
 */

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via qgzrestart()), so that the user can continue scanning by
	 * just pointing qgzin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when qgztext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int qgzleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow qgzwrap()'s to do buffer switches
 * instead of setting up a fresh qgzin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void qgzrestart (FILE *input_file  );
void qgz_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE qgz_create_buffer (FILE *file,int size  );
void qgz_delete_buffer (YY_BUFFER_STATE b  );
void qgz_flush_buffer (YY_BUFFER_STATE b  );
void qgzpush_buffer_state (YY_BUFFER_STATE new_buffer  );
void qgzpop_buffer_state (void );

static void qgzensure_buffer_stack (void );
static void qgz_load_buffer_state (void );
static void qgz_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER qgz_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE qgz_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE qgz_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE qgz_scan_bytes (yyconst char *bytes,int len  );

void *qgzalloc (yy_size_t  );
void *qgzrealloc (void *,yy_size_t  );
void qgzfree (void *  );

#define yy_new_buffer qgz_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        qgzensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            qgz_create_buffer(qgzin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        qgzensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            qgz_create_buffer(qgzin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

typedef unsigned char YY_CHAR;

FILE *qgzin = (FILE *) 0, *qgzout = (FILE *) 0;

typedef int yy_state_type;

extern int qgzlineno;

int qgzlineno = 1;

extern char *qgztext;
#define yytext_ptr qgztext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up qgztext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	qgzleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 65
#define YY_END_OF_BUFFER 66
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[411] =
    {   0,
        0,    0,    2,    2,    0,    0,    0,    0,    0,    0,
        0,    0,   66,   64,   57,   59,    1,   58,   64,   55,
       56,   56,   56,   56,   56,   56,   56,   56,   56,   56,
       56,   56,    2,    3,   63,   57,   60,   32,   58,   63,
       63,   55,   61,   62,   62,   62,   62,   62,   62,   62,
       62,   62,   62,   62,   62,   62,   62,   62,   62,   62,
       62,   62,   62,   62,   62,    6,    6,    9,    8,    7,
       27,   65,   28,   27,   57,   58,   55,   56,   56,   56,
       56,   56,   56,   56,   56,   56,   56,   56,   56,   56,
       56,   56,   56,   56,    2,   31,   62,   62,   62,   62,

       34,   62,   62,   62,   44,   62,   62,   62,   62,   62,
       62,   62,    4,   62,   62,   62,   34,   62,   62,   62,
       44,   62,   62,   62,   62,   62,   62,    0,    5,    0,
        7,    7,   27,   27,    0,   26,   56,   56,   56,   56,
       56,   56,   56,   56,   56,   56,   56,   56,   56,   56,
       56,   62,   30,   62,   62,   39,   62,   62,   33,   62,
       62,   62,   62,   62,   30,   62,   62,   39,   62,   62,
       33,   62,   62,   62,   62,   26,   56,   56,   56,   56,
       56,   56,   56,   56,   56,   56,   56,   56,   56,   56,
       56,   62,   62,   62,   62,   40,   62,   62,   50,   62,

       62,   62,   62,   62,   62,   40,   62,   62,   50,   62,
       62,   56,   56,   56,   56,   56,   14,   56,   56,   17,
       56,   56,   56,   56,   56,   56,   24,   62,   62,   62,
       62,   62,   42,   62,   62,   50,   62,   54,   62,   62,
       62,   62,   62,   42,   62,   62,   50,   62,   54,   56,
       11,   12,   56,   56,   56,   56,   56,   19,   20,   56,
       23,   56,   62,   35,   62,   62,   62,   62,   62,   62,
       52,   62,   35,   62,   62,   62,   62,   62,   62,   52,
       56,   25,   56,   15,   56,   56,   56,   56,   29,   62,
       62,   38,   41,   62,   45,   51,   62,   29,   62,   62,

       38,   41,   62,   45,   51,   62,   56,   56,   56,   56,
       56,   56,   29,   62,   62,   38,   43,   62,   45,   62,
       62,   29,   62,   62,   38,   43,   62,   45,   62,   62,
       56,   56,   16,   18,   21,   22,   36,   62,   62,   62,
       62,   62,   53,   36,   62,   62,   62,   62,   62,   53,
       10,   13,   56,   37,   62,   62,   62,   62,   37,   62,
       62,   62,   62,   37,   62,   62,   62,   62,   37,   62,
       62,   62,   62,   62,   62,   62,   62,   62,   62,   62,
       62,   62,   62,   62,   62,   62,   62,   62,   62,   62,
       49,   62,   47,   62,   49,   62,   47,   48,   49,   46,

       47,   48,   49,   46,   47,   48,   46,   48,   46,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    5,    6,    7,    1,    1,    8,    1,    1,
        1,    1,    1,    9,   10,    1,    1,   11,   11,   11,
       11,   11,   11,   11,   11,   11,   11,   12,   13,    1,
        1,    1,   14,    1,   15,   15,   15,   15,   15,   15,
       15,   15,   15,   15,   15,   15,   15,   15,   15,   15,
       15,   15,   15,   15,   15,   15,   15,   15,   15,   15,
        1,    1,    1,    1,   16,    1,   17,   18,   19,   20,

       21,   22,   23,   24,   25,   26,   15,   27,   28,   29,
       30,   31,   32,   33,   34,   35,   36,   37,   38,   15,
       39,   40,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[41] =
    {   0,
        1,    1,    2,    3,    1,    4,    1,    1,    3,    5,
        5,    6,    1,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5
    } ;

static yyconst flex_int16_t yy_base[426] =
    {   0,
        0,    0, 1000,  999,   40,   80,    0,  120,  136,  152,
      163,  167, 1004, 1007,  173, 1007, 1007,    0,  992,  991,
      987,  160,  120,  121,  164,  165,  166,  168,  167,  170,
      172,  173,    0, 1007, 1007,  186, 1007, 1007,    0,  992,
      988,  987, 1007,  983,  185,  182,  187,  188,  186,  190,
      192,  199,  203,  205,  209,  213,  218,  221,  222,  229,
      226,  233,  240,  241,  232, 1007,  253, 1007, 1007,  982,
        0, 1007, 1007,  265,  268,    0,  984,  965, 1007,  196,
      243,  250,  259,  247,  261,  262,  264,  265,  269,  270,
      271,  272,  279,  280,    0, 1007,  964, 1007,  274,  285,

      956,  281,  300,  282,  948,  292,  273,  283,  284,  301,
      304,  309, 1007,  917,  312,  313,  316,  320,  325,  324,
      332,  335,  336,  340,  345,  346,  349,  350, 1007,  916,
      913, 1007,    0,  366,  920,    0,  351,  352,  359,  354,
      366,  363,  367,  369,  372,  377,  374,  368,  383,  384,
      385,  317,  911,  386,  387,  909,  388,  394,  901,  393,
      396,  395,  404,  407,  411,  420,  421,  424,  427,  428,
      431,  434,  435,  441,  445, 1007,  401,  400,  436,  444,
      448,  452,  446,  449,  456,  457,  462,  466,  463,  467,
      471,  472,  468,  476,  478,  485,  480,  487,  486,  491,

      488,  498,  502,  506,  510,  515,  514,  518,  524,  527,
      530,  499,  531,  534,  535,  519, 1007,  536,  415, 1007,
      538,  541,  544,  492,  548,  547, 1007,  549,  550,  552,
      551,  554,  561,  558,  559,  571,  562,  897,  572,  577,
      583,  584,  588,  593,  592,  596,  604,  603,  597,  585,
     1007, 1007,  611,  606,  614,  605,  613, 1007,  893,  615,
     1007,  618,  560,  623,  621,  624,  625,  626,  628,  629,
      635,  641,  647,  650,  651,  655,  658,  661,  662,  669,
      664, 1007,  652, 1007,  672,  674,  675,  670,  889,  671,
      676,  875,  869,  686,  688,  851,  680,  689,  694,  698,

      701,  704,  708,  711,  712,  717,  716,  703,  722,  726,
      727,  730, 1007,  721,  729, 1007,  843,  733, 1007,  734,
      731,  808,  738,  745,  807,  746,  754,  786,  755,  758,
      759,  765, 1007, 1007, 1007, 1007,  778,  760,  766,  767,
      768,  770,  774,  775,  779,  782,  790,  793,  794,  798,
     1007, 1007,  801,  747,  800,  787,  804,  802,  812,  816,
      817,  821,  822, 1007,  825,  824,  826,  827,  741,  831,
      832,  836,  837,  842,  846,  847,  848,  862,  863,  866,
      867,  633,  852,  870,  855,  882,  883,  886,  887,  856,
      735,  876,  693,  890,  896,  900,  904,  638, 1007,  632,

     1007,  907,  575,  910,  495, 1007, 1007,  399,  343, 1007,
      930,  936,  942,  948,  954,  960,  338,  966,  295,  968,
      970,  219,  976,  982,  988
    } ;

static yyconst flex_int16_t yy_def[426] =
    {   0,
      410,    1,  411,  411,  410,  410,  412,  413,  414,  414,
      415,  415,  410,  410,  410,  410,  410,  416,  410,  410,
      417,  417,  417,  417,  417,  417,  417,  417,  417,  417,
      417,  417,  418,  410,  410,  410,  410,  410,  416,  410,
      410,  410,  410,  419,  419,  419,  419,  419,  419,  419,
      419,  419,  419,  419,  420,  420,  420,  420,  420,  420,
      420,  420,  420,  420,  420,  410,  421,  410,  410,  422,
      423,  410,  410,  424,  410,  416,  410,  417,  410,  417,
      417,  417,  417,  417,  417,  417,  417,  417,  417,  417,
      417,  417,  417,  417,  418,  410,  419,  410,  419,  419,

      419,  419,  419,  419,  419,  419,  419,  419,  419,  419,
      419,  420,  410,  410,  420,  420,  420,  420,  420,  420,
      420,  420,  420,  420,  420,  420,  420,  421,  410,  410,
      422,  410,  423,  424,  425,  423,  417,  417,  417,  417,
      417,  417,  417,  417,  417,  417,  417,  417,  417,  417,
      417,  419,  419,  419,  419,  419,  419,  419,  419,  419,
      419,  419,  419,  420,  420,  420,  420,  420,  420,  420,
      420,  420,  420,  420,  420,  410,  417,  417,  417,  417,
      417,  417,  417,  417,  417,  417,  417,  417,  417,  417,
      417,  419,  419,  419,  419,  419,  419,  419,  419,  419,

      419,  420,  420,  420,  420,  420,  420,  420,  420,  420,
      420,  417,  417,  417,  417,  417,  410,  417,  417,  410,
      417,  417,  417,  417,  417,  417,  410,  419,  419,  419,
      419,  419,  419,  419,  419,  419,  419,  419,  420,  420,
      420,  420,  420,  420,  420,  420,  420,  420,  420,  417,
      410,  410,  417,  417,  417,  417,  417,  410,  417,  417,
      410,  417,  419,  419,  419,  419,  419,  419,  419,  419,
      419,  420,  420,  420,  420,  420,  420,  420,  420,  420,
      417,  410,  417,  410,  417,  417,  417,  417,  419,  419,
      419,  419,  419,  419,  419,  419,  419,  420,  420,  420,

      420,  420,  420,  420,  420,  420,  417,  417,  417,  417,
      417,  417,  410,  419,  419,  410,  419,  419,  410,  419,
      419,  410,  420,  420,  410,  420,  420,  410,  420,  420,
      417,  417,  410,  410,  410,  410,  419,  419,  419,  419,
      419,  419,  419,  420,  420,  420,  420,  420,  420,  420,
      410,  410,  417,  419,  419,  419,  419,  419,  420,  420,
      420,  420,  420,  410,  419,  419,  419,  419,  410,  420,
      420,  420,  420,  419,  419,  419,  419,  420,  420,  420,
      420,  419,  419,  419,  419,  420,  420,  420,  420,  419,
      419,  419,  419,  420,  420,  420,  420,  419,  410,  419,

      410,  420,  410,  420,  410,  410,  410,  410,  410,    0,
      410,  410,  410,  410,  410,  410,  410,  410,  410,  410,
      410,  410,  410,  410,  410
    } ;

static yyconst flex_int16_t yy_nxt[1048] =
    {   0,
       14,   15,   16,   15,   14,   17,   18,   14,   14,   19,
       20,   14,   14,   21,   21,   14,   22,   23,   24,   25,
       26,   21,   27,   21,   21,   21,   21,   28,   21,   21,
       29,   21,   30,   31,   21,   21,   21,   21,   21,   32,
       35,   36,   37,   36,   38,   35,   39,   40,   35,   41,
       42,   35,   43,   44,   44,   35,   45,   44,   44,   46,
       47,   44,   48,   44,   49,   50,   44,   44,   51,   52,
       53,   44,   44,   44,   44,   44,   44,   54,   44,   44,
       35,   36,   37,   36,   38,   35,   39,   40,   35,   41,
       42,   35,   43,   55,   55,   35,   56,   55,   55,   57,

       58,   55,   59,   55,   60,   61,   55,   55,   62,   63,
       64,   55,   55,   55,   55,   55,   55,   65,   55,   55,
       66,   66,   66,   66,   66,   66,   66,   66,   66,   66,
       66,   66,   66,   79,   79,   66,   68,   68,   69,   68,
       68,   68,   68,   68,   68,   68,   68,   68,   68,   81,
       82,   68,   68,   68,   69,   68,   68,   68,   68,   68,
       68,   68,   68,   68,   68,   72,   73,   68,   74,   72,
       73,   73,   74,   79,   75,   73,   75,   79,   79,   79,
       79,   79,   87,   79,   83,   79,   79,   75,   84,   75,
       90,   89,   91,   86,   80,   98,   85,   88,   98,   98,

       98,   98,   94,   98,  104,   98,   92,  105,   99,   79,
       93,  101,   98,  100,  102,  103,   98,  108,   98,  109,
      113,  107,  114,  131,  113,  106,  114,  110,  111,  113,
      137,  114,  113,  113,  114,  114,  115,  113,  120,  114,
      113,  116,  114,  113,  113,  114,  114,  117,  118,  119,
      121,  113,  113,  114,  114,  127,   79,  125,  124,  138,
       79,  122,  123,   79,  129,  126,  130,  135,  135,   75,
      136,   75,   79,  135,   79,   79,  139,   79,   79,  141,
      140,  143,   79,   79,   79,   79,   98,   98,  149,  146,
      142,  144,   79,   79,   98,   98,   98,   98,   98,   97,

      147,  145,  148,  152,  153,   98,  150,  159,  151,  155,
      157,  154,  158,   98,   98,  155,  161,   98,  160,  156,
      113,  162,  114,  113,  113,  114,  114,  113,  163,  114,
       98,  113,  165,  114,  167,  113,  113,  114,  114,  192,
      167,  164,   78,  113,  168,  114,  113,  113,  114,  114,
      166,  113,  169,  114,  113,  170,  113,  113,  114,  114,
      113,  129,  114,  130,   79,   79,  174,   79,  135,  135,
      171,  136,   79,  175,  135,  172,   79,  173,  180,   79,
       79,   79,   79,  177,  178,   79,  181,   79,  179,  184,
       79,  183,  185,  182,  187,  186,   79,   79,   79,   98,

       98,   98,  193,  188,  196,  191,   98,   98,   98,   98,
      113,  190,  199,   79,   79,  189,  197,   98,  113,  213,
      114,  194,  113,  198,  114,  212,  195,  200,   79,  202,
      201,  113,  113,  114,  114,  113,  203,  114,  113,  113,
      114,  114,  113,  206,  114,  113,  113,  114,  114,   79,
      207,  209,  113,  256,  114,  204,  113,   79,  114,   79,
      205,   79,   79,  217,  208,   79,  216,  220,  214,   79,
       79,  211,  215,  210,  218,   79,   79,  222,  223,   79,
       79,   98,  227,  219,   79,   98,  224,  226,  228,   98,
      221,   98,  230,   98,  232,  235,  233,  225,   98,   98,

       98,   98,  229,  234,   98,   79,  113,  231,  238,  113,
      237,  114,   79,  113,  239,  114,  250,  113,  236,  114,
      260,  113,  241,  114,  243,  113,  113,  114,  114,  113,
      244,  114,   79,  246,  245,  113,  240,  114,  113,  242,
      114,  113,  251,  114,   79,  252,  248,   79,   79,   79,
      249,   79,  258,  254,   79,  253,  247,   79,  255,  261,
       79,   79,   98,   98,   98,   98,  264,   98,  263,  265,
      268,   98,   98,   98,   98,   98,  257,  269,  259,  266,
      235,  262,  271,  113,   98,  114,  113,  267,  113,  289,
      114,  272,  270,  273,  113,  113,  114,  114,   79,  113,

      274,  114,  277,  113,  113,  114,  114,  113,  113,  114,
      114,  278,  275,  246,  113,  113,  114,  114,   79,   79,
      281,  276,  282,  280,   79,  284,   79,   79,   79,  279,
      283,   79,  290,  287,   98,  285,   98,   98,   98,   98,
      292,   98,   98,  286,  297,  407,   98,  291,   98,  293,
      288,  406,  113,  296,  114,  390,  299,  295,  113,  294,
      114,  113,  113,  114,  114,   79,  113,  301,  114,  113,
      298,  114,  113,  113,  114,  114,  300,   79,  306,  302,
      113,  308,  114,   79,   98,   79,  305,   79,   79,   98,
      304,  303,  309,   98,  310,  311,  315,  318,  307,   98,

      113,  319,  322,  320,  314,  113,  401,  114,  312,  113,
      317,  114,  113,  321,  325,  113,   79,  114,  324,  113,
      327,  114,  113,  113,  328,  114,  329,  323,  113,   79,
      114,  332,  326,  333,   98,   79,  331,  334,  335,   79,
       79,  336,   98,   79,   98,  337,   98,   98,  399,  113,
      330,  114,  113,  339,  341,  343,  113,  113,  114,  114,
      364,  338,  344,  340,  342,  113,  113,  114,  114,  113,
      351,  114,   79,   98,  346,  348,  352,  345,   79,   98,
       98,   98,  350,   98,  347,  349,  113,   98,  114,  354,
      113,   98,  114,  113,  355,  114,  357,  113,  353,  356,

       98,  113,  358,  114,  113,  113,  114,  114,  359,  113,
      360,  114,  352,   98,   79,   98,  366,   98,  113,  113,
      365,  362,  361,  113,  367,  369,  363,  113,  113,  114,
      114,  368,  113,  113,  114,  114,  370,   98,   98,   98,
       98,  372,  113,  113,  114,  114,  371,  113,  113,  114,
      114,  373,  374,  376,  375,   98,   98,  377,  378,   98,
       98,   98,  379,  380,   98,   98,  382,  381,   98,   98,
      383,  384,  385,  113,  113,  114,  114,  113,  113,  114,
      114,  391,   98,   98,  393,  398,  386,  387,  316,   98,
      388,  389,  392,  113,  113,  114,  114,  113,  113,  114,

      114,  113,  313,  114,  394,  400,   79,  113,  396,  403,
       98,  113,  395,  114,   98,  113,  397,  405,  113,  402,
      408,  113,   98,  409,   98,  176,  132,  129,  113,  404,
       33,   33,   33,   33,   33,   33,   66,   66,   66,   66,
       66,   66,   67,   67,   67,   67,   67,   67,   70,   70,
       70,   70,   70,   70,   71,   71,   71,   71,   71,   71,
       76,   98,   76,   76,   76,   76,   95,   95,   95,   98,
       95,   95,  112,  112,  128,  128,  133,   98,   79,  133,
      133,  133,  134,  134,  134,  134,  134,  134,  135,  135,
      135,  135,  135,  135,   77,  132,   98,   77,   77,   96,

       79,   77,   77,  410,   34,   34,   13,  410,  410,  410,
      410,  410,  410,  410,  410,  410,  410,  410,  410,  410,
      410,  410,  410,  410,  410,  410,  410,  410,  410,  410,
      410,  410,  410,  410,  410,  410,  410,  410,  410,  410,
      410,  410,  410,  410,  410,  410,  410
    } ;

static yyconst flex_int16_t yy_chk[1048] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    6,

        6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        8,    8,    8,    8,    8,    8,    8,    8,    8,    8,
        8,    8,    8,   23,   24,    8,    9,    9,    9,    9,
        9,    9,    9,    9,    9,    9,    9,    9,    9,   23,
       24,    9,   10,   10,   10,   10,   10,   10,   10,   10,
       10,   10,   10,   10,   10,   11,   11,   10,   11,   12,
       12,   11,   12,   22,   15,   12,   15,   25,   26,   27,
       29,   28,   27,   30,   25,   31,   32,   36,   25,   36,
       30,   29,   31,   26,   22,   46,   25,   28,   45,   49,

       47,   48,   32,   50,   48,   51,   31,   49,   45,   80,
       31,   46,   52,   45,   47,   47,   53,   52,   54,   53,
       55,   51,   55,  422,   56,   50,   56,   53,   54,   57,
       80,   57,   58,   59,   58,   59,   56,   61,   59,   61,
       60,   56,   60,   65,   62,   65,   62,   57,   58,   58,
       60,   63,   64,   63,   64,   65,   81,   64,   63,   81,
       84,   61,   62,   82,   67,   64,   67,   74,   74,   75,
       74,   75,   83,   74,   85,   86,   82,   87,   88,   84,
       83,   86,   89,   90,   91,   92,  107,   99,   92,   89,
       85,   87,   93,   94,  102,  104,  108,  109,  100,  419,

       90,   88,   91,   99,  100,  106,   93,  107,   94,  103,
      104,  102,  106,  103,  110,  103,  109,  111,  108,  103,
      112,  110,  112,  115,  116,  115,  116,  117,  111,  117,
      152,  118,  116,  118,  119,  120,  119,  120,  119,  152,
      119,  115,  417,  121,  119,  121,  122,  123,  122,  123,
      118,  124,  120,  124,  409,  122,  125,  126,  125,  126,
      127,  128,  127,  128,  137,  138,  126,  140,  134,  134,
      123,  134,  139,  127,  134,  124,  142,  125,  140,  141,
      143,  148,  144,  137,  138,  145,  141,  147,  139,  144,
      146,  143,  145,  142,  147,  146,  149,  150,  151,  154,

      155,  157,  154,  148,  157,  151,  160,  158,  162,  161,
      408,  150,  161,  178,  177,  149,  158,  163,  164,  178,
      164,  155,  165,  160,  165,  177,  155,  162,  219,  164,
      163,  166,  167,  166,  167,  168,  166,  168,  169,  170,
      169,  170,  171,  169,  171,  172,  173,  172,  173,  179,
      170,  173,  174,  219,  174,  167,  175,  180,  175,  183,
      167,  181,  184,  182,  172,  182,  181,  185,  179,  185,
      186,  175,  180,  174,  183,  187,  189,  186,  187,  188,
      190,  193,  191,  184,  191,  192,  188,  190,  192,  194,
      185,  195,  194,  197,  196,  199,  197,  189,  196,  199,

      198,  201,  193,  198,  200,  224,  405,  195,  201,  202,
      200,  202,  212,  203,  202,  203,  212,  204,  199,  204,
      224,  205,  204,  205,  206,  207,  206,  207,  206,  208,
      207,  208,  216,  209,  208,  209,  203,  209,  210,  205,
      210,  211,  213,  211,  213,  214,  210,  214,  215,  218,
      211,  221,  222,  216,  222,  215,  209,  223,  218,  225,
      226,  225,  228,  229,  231,  230,  229,  232,  228,  230,
      233,  234,  235,  263,  233,  237,  221,  234,  223,  231,
      236,  226,  237,  239,  236,  239,  403,  232,  240,  263,
      240,  239,  235,  240,  241,  242,  241,  242,  250,  243,

      241,  243,  244,  245,  244,  245,  244,  246,  249,  246,
      249,  245,  242,  247,  248,  247,  248,  247,  256,  254,
      250,  243,  253,  248,  253,  255,  257,  255,  260,  246,
      254,  262,  264,  260,  265,  256,  264,  266,  267,  268,
      266,  269,  270,  257,  271,  400,  382,  265,  271,  267,
      262,  398,  272,  270,  272,  382,  273,  269,  273,  268,
      273,  274,  275,  274,  275,  283,  276,  275,  276,  277,
      272,  277,  278,  279,  278,  279,  274,  281,  280,  276,
      280,  283,  280,  288,  290,  285,  279,  286,  287,  291,
      278,  277,  285,  297,  286,  287,  291,  295,  281,  294,

      298,  295,  298,  295,  290,  299,  393,  299,  288,  300,
      294,  300,  301,  297,  301,  302,  308,  302,  300,  303,
      304,  303,  304,  305,  304,  305,  304,  299,  306,  307,
      306,  308,  303,  309,  314,  309,  307,  310,  311,  310,
      311,  312,  315,  312,  321,  314,  318,  320,  391,  323,
      306,  323,  369,  318,  320,  321,  324,  326,  324,  326,
      354,  315,  323,  318,  320,  327,  329,  327,  329,  330,
      331,  330,  331,  338,  327,  329,  332,  324,  332,  339,
      340,  341,  330,  342,  327,  329,  344,  343,  344,  338,
      345,  337,  345,  346,  339,  346,  341,  328,  332,  340,

      356,  347,  342,  347,  348,  349,  348,  349,  345,  350,
      346,  350,  353,  355,  353,  358,  356,  357,  325,  322,
      355,  348,  347,  359,  357,  359,  349,  360,  361,  360,
      361,  358,  362,  363,  362,  363,  360,  366,  365,  367,
      368,  362,  370,  371,  370,  371,  361,  372,  373,  372,
      373,  363,  365,  367,  366,  374,  317,  368,  370,  375,
      376,  377,  371,  372,  296,  383,  374,  373,  385,  390,
      375,  376,  377,  378,  379,  378,  379,  380,  381,  380,
      381,  383,  293,  384,  385,  390,  378,  379,  292,  392,
      380,  381,  384,  386,  387,  386,  387,  388,  389,  388,

      389,  394,  289,  394,  386,  392,  259,  395,  388,  395,
      238,  396,  387,  396,  159,  397,  389,  397,  402,  394,
      402,  404,  156,  404,  153,  135,  131,  130,  114,  396,
      411,  411,  411,  411,  411,  411,  412,  412,  412,  412,
      412,  412,  413,  413,  413,  413,  413,  413,  414,  414,
      414,  414,  414,  414,  415,  415,  415,  415,  415,  415,
      416,  105,  416,  416,  416,  416,  418,  418,  418,  101,
      418,  418,  420,  420,  421,  421,  423,   97,   78,  423,
      423,  423,  424,  424,  424,  424,  424,  424,  425,  425,
      425,  425,  425,  425,   77,   70,   44,   42,   41,   40,

       21,   20,   19,   13,    4,    3,  410,  410,  410,  410,
      410,  410,  410,  410,  410,  410,  410,  410,  410,  410,
      410,  410,  410,  410,  410,  410,  410,  410,  410,  410,
      410,  410,  410,  410,  410,  410,  410,  410,  410,  410,
      410,  410,  410,  410,  410,  410,  410
    } ;

/* Table of booleans, true if rule could match eol. */
static yyconst flex_int32_t yy_rule_can_match_eol[66] =
    {   0,
0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 
    1, 0, 0, 0, 0, 0,     };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int qgz_flex_debug;
int qgz_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *qgztext;
#line 1 "qgames_scanner.l"
#line 2 "qgames_scanner.l"

#include <stdio.h>
#include "symtable.h"
#include "qgames_parser.h"
#include "qgames.h"

/*
 * Crea una definicion (para substitucion)
 * */
void   create_define( char* d );
void   generate_define( );
int    add_parameter_to_def( char* p );
void   init_scanner();
int    defined( char* d );
int    switch_to_define( );


symtable*  symt = NULL;
char*  defactual = NULL;
#define  MAXPARMS  16
char*  defparms[MAXPARMS];
char*  define_body;
int    define_created;
int    define_bodyc = 0;
int    parmcount = 0;
int    totalparm;

#define  MAXBUFFSTACK  16
YY_BUFFER_STATE  buffers[MAXBUFFSTACK];
int        line_buffer[MAXBUFFSTACK];
char*      newdata_buffer[MAXBUFFSTACK];
char*      defname_buffer[MAXBUFFSTACK];
int        sp_buffer = 0;



#line 901 "qgames_scanner.c"

#define INITIAL 0
#define string 1
#define code 2
#define define 3
#define define_head 4
#define params 5

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int qgzwrap (void );
#else
extern int qgzwrap (void );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  );
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO fwrite( qgztext, qgzleng, 1, qgzout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( qgzin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( qgzin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, qgzin))==0 && ferror(qgzin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(qgzin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int qgzlex (void);

#define YY_DECL int qgzlex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after qgztext and qgzleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	if ( qgzleng > 0 ) \
		YY_CURRENT_BUFFER_LVALUE->yy_at_bol = \
				(qgztext[qgzleng - 1] == '\n'); \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 46 "qgames_scanner.l"




#line 1067 "qgames_scanner.c"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! qgzin )
			qgzin = stdin;

		if ( ! qgzout )
			qgzout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			qgzensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				qgz_create_buffer(qgzin,YY_BUF_SIZE );
		}

		qgz_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of qgztext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
		yy_current_state += YY_AT_BOL();
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 411 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_current_state != 410 );
		yy_cp = (yy_last_accepting_cpos);
		yy_current_state = (yy_last_accepting_state);

yy_find_action:
		yy_act = yy_accept[yy_current_state];

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			int yyl;
			for ( yyl = 0; yyl < qgzleng; ++yyl )
				if ( qgztext[yyl] == '\n' )
					   
    qgzlineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 50 "qgames_scanner.l"
{ BEGIN(string); }
	YY_BREAK
case 2:
/* rule 2 can match eol */
YY_RULE_SETUP
#line 51 "qgames_scanner.l"
{ qgzlval = (long)strdup(qgztext); 
                  return TOK_STRING;
                }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 54 "qgames_scanner.l"
{ BEGIN(INITIAL); }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 57 "qgames_scanner.l"
{ BEGIN(INITIAL); yyless(0); return  TOK_SEPARATOR; }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 58 "qgames_scanner.l"
{ generate_define(); BEGIN(INITIAL); yyless(0); return  TOK_SEPARATOR; }
	YY_BREAK
case 6:
/* rule 6 can match eol */
YY_RULE_SETUP
#line 59 "qgames_scanner.l"
{ define_body[define_bodyc++] = qgztext[0]; }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 61 "qgames_scanner.l"
{ if( !define_created) 
                          create_define( qgztext );
                      else{
                          if( !add_parameter_to_def( qgztext ) ) yyterminate();
                      }
                    } ;
	YY_BREAK
case 8:
/* rule 8 can match eol */
YY_RULE_SETUP
#line 67 "qgames_scanner.l"
{ BEGIN(define); }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 68 "qgames_scanner.l"

	YY_BREAK
case 10:
YY_RULE_SETUP
#line 71 "qgames_scanner.l"
{ return TOK_ATTR;      }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 72 "qgames_scanner.l"
{ return TOK_BOARD ;    }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 73 "qgames_scanner.l"
{ return TOK_COLOR;     }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 74 "qgames_scanner.l"
{ return TOK_DIRECTION; }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 75 "qgames_scanner.l"
{ return TOK_DROP;      }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 76 "qgames_scanner.l"
{ return TOK_ENDING;    }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 77 "qgames_scanner.l"
{ return TOK_GAMETYPE;  }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 78 "qgames_scanner.l"
{ return TOK_MOVE;      }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 79 "qgames_scanner.l"
{ return TOK_MOVETYPE;  }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 80 "qgames_scanner.l"
{ return TOK_PIECE;     }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 81 "qgames_scanner.l"
{ return TOK_REPEAT;    }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 82 "qgames_scanner.l"
{ return TOK_SEQUENCE;  }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 83 "qgames_scanner.l"
{ return TOK_SYMMETRY;  }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 84 "qgames_scanner.l"
{ return TOK_START;     }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 85 "qgames_scanner.l"
{ return TOK_ZONE;      }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 87 "qgames_scanner.l"
{ define_created = 0; BEGIN(define_head);   }
	YY_BREAK
case 26:
/* rule 26 can match eol */
YY_RULE_SETUP
#line 89 "qgames_scanner.l"
{ if( !add_parameter_to_def( qgztext ) ) yyterminate();
                            if( parmcount == totalparm ){
                                if( ! switch_to_define( )) yyterminate();
                            }
                          }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 94 "qgames_scanner.l"
{ if( !add_parameter_to_def( qgztext ) ) yyterminate();
                            if( parmcount == totalparm ){
                                if( ! switch_to_define( ) )yyterminate();
                            }
                          }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 99 "qgames_scanner.l"
// No hago nada!
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 102 "qgames_scanner.l"
{ return TOK_AHOGADO;   }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 103 "qgames_scanner.l"
{ return TOK_AND;       }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 104 "qgames_scanner.l"
{ return TOK_AND;       }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 105 "qgames_scanner.l"
{ return TOK_NOT;       }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 106 "qgames_scanner.l"
{ return TOK_NOT;       }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 107 "qgames_scanner.l"
{ return TOK_DO;        }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 108 "qgames_scanner.l"
{ return TOK_EMPATA;    }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 109 "qgames_scanner.l"
{ return TOK_EMPATA_SI; }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 110 "qgames_scanner.l"
{ return TOK_ENTABLERO;   }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 111 "qgames_scanner.l"
{ return TOK_ENZONA;    }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 112 "qgames_scanner.l"
{ return TOK_END;       }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 113 "qgames_scanner.l"
{ return TOK_GANA;      }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 114 "qgames_scanner.l"
{ return TOK_GANA_SI;   }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 115 "qgames_scanner.l"
{ return TOK_JUEGA;     } 
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 116 "qgames_scanner.l"
{ return TOK_JUEGA_SI;  }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 117 "qgames_scanner.l"
{ return TOK_IF;        }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 118 "qgames_scanner.l"
{ return TOK_OCUPADO;   }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 119 "qgames_scanner.l"
{ return TOK_OCUPADOENEMIGO;   }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 120 "qgames_scanner.l"
{ return TOK_OCUPADOPROPIO;   }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 121 "qgames_scanner.l"
{ return TOK_OCUPADOENEMIGO;   }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 122 "qgames_scanner.l"
{ return TOK_OCUPADOPROPIO;   }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 123 "qgames_scanner.l"
{ return  TOK_PARA;        }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 124 "qgames_scanner.l"
{ return  TOK_PARA_SI;     }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 125 "qgames_scanner.l"
{ return  TOK_PIERDE;      }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 126 "qgames_scanner.l"
{ return  TOK_PIERDE_SI;   }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 127 "qgames_scanner.l"
{ return  TOK_WHILE;       }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 130 "qgames_scanner.l"
{ 
                  qgzlval = atol(qgztext); 
                  return TOK_NUMBER;
                }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 135 "qgames_scanner.l"
{ 
                  qgzlval = (long)strdup(qgztext); 
                  ((char*)(long)qgzlval)[qgzleng] = 0;
                  qgzprintf( "WORD: %s", (char*)(long)qgzlval  );
                  return  TOK_WORD; 
                }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 142 "qgames_scanner.l"
/* ignore whitespace */
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 143 "qgames_scanner.l"
/* ignora comentario */
	YY_BREAK
case 59:
/* rule 59 can match eol */
YY_RULE_SETUP
#line 146 "qgames_scanner.l"
{ return  TOK_SEPARATOR ; }
	YY_BREAK
case 60:
/* rule 60 can match eol */
YY_RULE_SETUP
#line 148 "qgames_scanner.l"
{ return  TOK_SEPCODE; }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 149 "qgames_scanner.l"
{ return  TOK_SEPCODE; }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 150 "qgames_scanner.l"
{
                  int  argc = ( symt ? symtable_argc( symt, qgztext ) : -1 );
                  if( argc == 0 ){
                      parmcount = 0;
                      defactual = strdup( qgztext );
                      switch_to_define( );
                  } else if( argc >= 0 ){
                      parmcount = 0;
                      totalparm = argc;
                      defactual = strdup( qgztext );
                      BEGIN(params);
                  } else {
                      qgzlval = (long)strdup(qgztext); 
                      ((char*)(long)qgzlval)[qgzleng] = 0;
                      return  TOK_WORD; 
                  }
                }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 167 "qgames_scanner.l"
{ return (int) qgztext[0]; }
	YY_BREAK
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(string):
case YY_STATE_EOF(code):
case YY_STATE_EOF(define):
case YY_STATE_EOF(define_head):
case YY_STATE_EOF(params):
#line 169 "qgames_scanner.l"
{ if( sp_buffer == 0 ){
                      yyterminate();
                  } else {  
                      sp_buffer --;
                      if( newdata_buffer[sp_buffer] ) free( newdata_buffer[sp_buffer] );
                      if( defname_buffer[sp_buffer] ) free( defname_buffer[sp_buffer] );
                      qgz_delete_buffer(YY_CURRENT_BUFFER );
                      qgz_switch_to_buffer(buffers[sp_buffer] );
                      qgzlineno = line_buffer[sp_buffer] ;
                  }
                }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 181 "qgames_scanner.l"

	YY_BREAK
case 65:
YY_RULE_SETUP
#line 184 "qgames_scanner.l"
ECHO;
	YY_BREAK
#line 1546 "qgames_scanner.c"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed qgzin at a new source and called
			 * qgzlex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = qgzin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_last_accepting_cpos);
				yy_current_state = (yy_last_accepting_state);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( qgzwrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * qgztext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of qgzlex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					qgzrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), (size_t) num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			qgzrestart(qgzin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) qgzrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);
	yy_current_state += YY_AT_BOL();

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 411 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 411 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 410);

	return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp )
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up qgztext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

    if ( c == '\n' ){
        --qgzlineno;
    }

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					qgzrestart(qgzin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( qgzwrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve qgztext */
	(yy_hold_char) = *++(yy_c_buf_p);

	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = (c == '\n');
	if ( YY_CURRENT_BUFFER_LVALUE->yy_at_bol )
		   
    qgzlineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void qgzrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        qgzensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            qgz_create_buffer(qgzin,YY_BUF_SIZE );
	}

	qgz_init_buffer(YY_CURRENT_BUFFER,input_file );
	qgz_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void qgz_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		qgzpop_buffer_state();
	 *		qgzpush_buffer_state(new_buffer);
     */
	qgzensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	qgz_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (qgzwrap()) processing, but the only time this flag
	 * is looked at is after qgzwrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void qgz_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	qgzin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE qgz_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) qgzalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in qgz_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) qgzalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in qgz_create_buffer()" );

	b->yy_is_our_buffer = 1;

	qgz_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with qgz_create_buffer()
 * 
 */
    void qgz_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		qgzfree((void *) b->yy_ch_buf  );

	qgzfree((void *) b  );
}

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a qgzrestart() or at EOF.
 */
    static void qgz_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	qgz_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then qgz_init_buffer was _probably_
     * called from qgzrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void qgz_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		qgz_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void qgzpush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	qgzensure_buffer_stack();

	/* This block is copied from qgz_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from qgz_switch_to_buffer. */
	qgz_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void qgzpop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	qgz_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		qgz_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void qgzensure_buffer_stack (void)
{
	int num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)qgzalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in qgzensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)qgzrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in qgzensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE qgz_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) qgzalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in qgz_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	qgz_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to qgzlex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       qgz_scan_bytes() instead.
 */
YY_BUFFER_STATE qgz_scan_string (yyconst char * yystr )
{
    
	return qgz_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to qgzlex() will
 * scan from a @e copy of @a bytes.
 * @param bytes the byte buffer to scan
 * @param len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE qgz_scan_bytes  (yyconst char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) qgzalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in qgz_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = qgz_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in qgz_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up qgztext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		qgztext[qgzleng] = (yy_hold_char); \
		(yy_c_buf_p) = qgztext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		qgzleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int qgzget_lineno  (void)
{
        
    return qgzlineno;
}

/** Get the input stream.
 * 
 */
FILE *qgzget_in  (void)
{
        return qgzin;
}

/** Get the output stream.
 * 
 */
FILE *qgzget_out  (void)
{
        return qgzout;
}

/** Get the length of the current token.
 * 
 */
int qgzget_leng  (void)
{
        return qgzleng;
}

/** Get the current token.
 * 
 */

char *qgzget_text  (void)
{
        return qgztext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void qgzset_lineno (int  line_number )
{
    
    qgzlineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see qgz_switch_to_buffer
 */
void qgzset_in (FILE *  in_str )
{
        qgzin = in_str ;
}

void qgzset_out (FILE *  out_str )
{
        qgzout = out_str ;
}

int qgzget_debug  (void)
{
        return qgz_flex_debug;
}

void qgzset_debug (int  bdebug )
{
        qgz_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from qgzlex_destroy(), so don't allocate here.
     */

    /* We do not touch qgzlineno unless the option is enabled. */
    qgzlineno =  1;
    
    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    qgzin = stdin;
    qgzout = stdout;
#else
    qgzin = (FILE *) 0;
    qgzout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * qgzlex_init()
     */
    return 0;
}

/* qgzlex_destroy is for both reentrant and non-reentrant scanners. */
int qgzlex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		qgz_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		qgzpop_buffer_state();
	}

	/* Destroy the stack itself. */
	qgzfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * qgzlex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *qgzalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *qgzrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void qgzfree (void * ptr )
{
	free( (char *) ptr );	/* see qgzrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 184 "qgames_scanner.l"




void   init_scanner(){
    if( symt ){
        symtable_free( symt );
        symt = NULL;
    }
    define_created = 0;
    parmcount = 0;
    sp_buffer = 0;
   
}

void   change_to_code_mode(){
    BEGIN(code);
}

int    defined( char* d ){
    if( !symt ) return 0;
    return  symtable_search( symt, d );
}


void   create_define( char* d ){
    define_created = 1;    
    defactual     = strdup( d );
    define_body   = ALLOC( 1024 );
    define_body[0] = 0;
    define_bodyc  = 0;
    parmcount     = 0;
}

int    add_parameter_to_def( char* p ){
    defparms[parmcount++] = strdup( p );   
    if( parmcount >= MAXPARMS ){ 
        qgzerror( "Se alcanzo el maximo de parametros admitidos" );
        return 0;
    }
    return 1;
}


void   generate_define( ){
    int i;
    if( !symt ) symt = symtable_init( );
    define_body[define_bodyc] = 0;
    symtable_adddef( symt, defactual    , parmcount, defparms, define_body );
    free( define_body );
    free( defactual );
    for( i = 0 ; i < parmcount; i ++ ){ free( defparms[i] ); }
}


int    switch_to_define( ){
    if( !symt ){
        qgzerror( "Error resolviendo symt" );
        return 0;
    }

    if( sp_buffer + 1 >= MAXBUFFSTACK ){
        qgzerror( "Maximo alcanzado en stack buffer de defines" );
        return 0;
    }

    char*  data; 
    int i;
    if (!symtable_resolve( symt, defactual, parmcount, defparms, &data ) ){
        qgzerror( "Error resolviendo define" );
        return 0;
    }

       
    // buffers[sp_buffer] = yybuffer
    buffers[sp_buffer] = YY_CURRENT_BUFFER;
    line_buffer[sp_buffer] = qgzlineno;
    qgzlineno = 1;
    newdata_buffer[sp_buffer] = data;
    defname_buffer[sp_buffer] = strdup( defactual );
    sp_buffer ++;

    for( i = 0; i < parmcount ; i ++ ){
        free( defparms[i] );
    }
    free( defactual );

    qgz_scan_string(data );
    BEGIN(code);

    return 1;
    
}


char*  defname_actual( ){
    if( sp_buffer == 0 ) return NULL;
    return( defname_buffer[sp_buffer-1] );
}



