#line 2 "qgames_scanner.c"

#line 4 "qgames_scanner.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define yy_create_buffer qgz_create_buffer
#define yy_delete_buffer qgz_delete_buffer
#define yy_flex_debug qgz_flex_debug
#define yy_init_buffer qgz_init_buffer
#define yy_flush_buffer qgz_flush_buffer
#define yy_load_buffer_state qgz_load_buffer_state
#define yy_switch_to_buffer qgz_switch_to_buffer
#define yyin qgzin
#define yyleng qgzleng
#define yylex qgzlex
#define yylineno qgzlineno
#define yyout qgzout
#define yyrestart qgzrestart
#define yytext qgztext
#define yywrap qgzwrap
#define yyalloc qgzalloc
#define yyrealloc qgzrealloc
#define yyfree qgzfree

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 34
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;
#endif /* ! C99 */

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE qgzrestart(qgzin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#define YY_BUF_SIZE 16384
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

extern int qgzleng;

extern FILE *qgzin, *qgzout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE qgzlex. 
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-qgzlineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < qgzleng; ++yyl )\
                    if ( qgztext[yyl] == '\n' )\
                        --qgzlineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up qgztext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up qgztext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 * Given that the standard has decreed that size_t exists since 1989,
 * I guess we can afford to depend on it. Manoj.
 */

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via qgzrestart()), so that the user can continue scanning by
	 * just pointing qgzin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when qgztext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int qgzleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow qgzwrap()'s to do buffer switches
 * instead of setting up a fresh qgzin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void qgzrestart (FILE *input_file  );
void qgz_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE qgz_create_buffer (FILE *file,int size  );
void qgz_delete_buffer (YY_BUFFER_STATE b  );
void qgz_flush_buffer (YY_BUFFER_STATE b  );
void qgzpush_buffer_state (YY_BUFFER_STATE new_buffer  );
void qgzpop_buffer_state (void );

static void qgzensure_buffer_stack (void );
static void qgz_load_buffer_state (void );
static void qgz_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER qgz_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE qgz_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE qgz_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE qgz_scan_bytes (yyconst char *bytes,int len  );

void *qgzalloc (yy_size_t  );
void *qgzrealloc (void *,yy_size_t  );
void qgzfree (void *  );

#define yy_new_buffer qgz_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        qgzensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            qgz_create_buffer(qgzin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        qgzensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            qgz_create_buffer(qgzin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

typedef unsigned char YY_CHAR;

FILE *qgzin = (FILE *) 0, *qgzout = (FILE *) 0;

typedef int yy_state_type;

extern int qgzlineno;

int qgzlineno = 1;

extern char *qgztext;
#define yytext_ptr qgztext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up qgztext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	qgzleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 81
#define YY_END_OF_BUFFER 82
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[580] =
    {   0,
        0,    0,    2,    2,    5,    5,    0,    0,    0,    0,
        0,    0,    0,    0,   82,   80,   73,   75,    1,   74,
        4,   80,   71,   72,   72,   72,   72,   72,   72,   72,
       72,   72,   72,   72,   72,   72,   72,   72,    2,    3,
        5,    6,   79,   73,   76,   43,    1,   74,   79,    4,
       79,   71,   77,   78,   78,   78,   78,   78,   78,   78,
       78,   78,   78,   78,   78,   78,   78,   78,   78,   78,
       78,   78,   78,   78,   78,   78,   78,   78,   78,    9,
        9,   12,   11,   10,   39,   81,   40,   39,   39,   73,
       74,   71,   72,   72,   72,   72,   72,   72,   72,   72,

       72,   72,   72,   72,   72,   72,   72,   72,   72,   72,
       72,   72,   72,   72,   72,    2,    5,   42,   78,   78,
       78,   78,   78,   78,   67,   78,   78,   78,   68,   78,
       78,   78,   78,   78,   78,   78,   78,   78,    7,   78,
       78,   78,   78,   78,   67,   78,   78,   78,   68,   78,
       78,   78,   78,   78,   78,   78,   78,    0,    8,    0,
       10,   10,   39,   39,    0,   38,   39,    0,   37,   72,
       72,   72,   72,   72,   72,   72,   72,   72,   72,   72,
       72,   72,   72,   72,   72,   72,   72,   72,   72,   72,
       78,   41,   78,   78,   78,   78,   69,   78,   78,   78,

       44,   78,   78,   78,   78,   78,   78,   41,   78,   78,
       78,   78,   69,   78,   78,   78,   44,   78,   78,   78,
       78,   78,   38,   37,   72,   72,   72,   72,   72,   72,
       72,   72,   72,   72,   22,   72,   72,   72,   72,   72,
       72,   72,   72,   72,   72,   72,   78,   78,   78,   78,
       78,   78,   52,   78,   78,   78,   62,   78,   78,   78,
       78,   78,   78,   78,   78,   78,   52,   78,   78,   78,
       62,   78,   78,   78,   72,   72,   72,   72,   72,   72,
       72,   19,   72,   72,   23,   72,   72,   72,   72,   72,
       72,   72,   72,   72,   72,   35,   78,   78,   78,   78,

       78,   78,   78,   78,   55,   78,   78,   62,   78,   78,
       70,   78,   78,   78,   78,   78,   78,   78,   78,   55,
       78,   78,   62,   78,   78,   70,   72,   14,   72,   16,
       72,   72,   72,   72,   72,   72,   72,   72,   26,   28,
       72,   30,   72,   33,   72,   34,   78,   78,   78,   48,
       78,   78,   78,   78,   78,   78,   78,   64,   78,   78,
       78,   78,   48,   78,   78,   78,   78,   78,   78,   78,
       64,   78,   72,   72,   17,   36,   72,   20,   72,   72,
       72,   72,   72,   72,   72,   45,   78,   78,   78,   78,
       51,   53,   78,   78,   57,   63,   78,   78,   45,   78,

       78,   78,   78,   51,   53,   78,   78,   57,   63,   78,
       78,   72,   72,   72,   72,   72,   72,   27,   72,   72,
       72,   45,   78,   78,   78,   78,   51,   78,   56,   78,
       57,   78,   78,   78,   45,   78,   78,   78,   78,   51,
       78,   56,   78,   57,   78,   78,   78,   72,   72,   72,
       21,   24,   25,   72,   31,   32,   78,   78,   49,   78,
       54,   78,   78,   78,   78,   65,   78,   78,   78,   49,
       78,   54,   78,   78,   78,   78,   65,   78,   13,   72,
       18,   72,   29,   78,   78,   50,   54,   78,   78,   78,
       78,   66,   78,   78,   50,   54,   78,   78,   78,   78,

       66,   72,   78,   78,   50,   78,   78,   78,   78,   66,
       78,   78,   50,   78,   78,   78,   78,   66,   72,   78,
       78,   78,   78,   78,   78,   78,   78,   78,   78,   78,
       78,   15,   78,   78,   78,   78,   78,   78,   78,   78,
       78,   78,   78,   78,   78,   78,   78,   61,   78,   59,
       78,   78,   78,   61,   78,   59,   46,   78,   60,   61,
       58,   59,   46,   78,   60,   61,   58,   59,   46,   78,
       60,   58,   46,   78,   60,   58,   47,   47,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    5,    6,    7,    1,    1,    8,    9,    1,
        1,    1,    1,   10,   11,    1,    1,   12,   12,   12,
       12,   12,   12,   12,   12,   12,   12,   13,   14,    1,
        1,    1,   15,    1,   16,   16,   16,   16,   16,   16,
       16,   16,   16,   16,   16,   16,   16,   16,   16,   16,
       16,   16,   16,   16,   16,   16,   16,   16,   16,   16,
        1,    1,    1,    1,   17,    1,   18,   19,   20,   21,

       22,   23,   24,   25,   26,   27,   28,   29,   30,   31,
       32,   33,   34,   35,   36,   37,   38,   39,   40,   16,
       41,   42,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[43] =
    {   0,
        1,    1,    2,    3,    1,    4,    1,    1,    5,    3,
        6,    6,    7,    1,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    6
    } ;

static yyconst flex_int16_t yy_base[599] =
    {   0,
        0,    0, 1411, 1410, 1406, 1405,   42,   84,    0,  126,
      143,  160,  172,  180, 1413, 1418,  183, 1418, 1418,    0,
     1418, 1400, 1399, 1395,  143,  127,  173,  177,  164,  178,
      179,  183,  185,  187,  186,  192,  191,  189,    0, 1418,
        0, 1418, 1418,  215, 1418, 1418, 1418,    0, 1401, 1418,
     1396, 1395, 1418, 1391,  203,  207,  195,  208,  217,  221,
      227,  209,  211,  228,  215,  222,  236,  242,  243,  249,
      253,  256,  257,  272,  262,  273,  282,  263,  276, 1418,
      289, 1418, 1418, 1390,    0, 1418, 1418,  303,  308,  301,
        0, 1392, 1388, 1418,  245,  281,  299,  300,  301,  304,

      305,  238,  233,  306,  307,  308,  312,  310,  311,  315,
      316,  320,  313,  319,  325,    0,    0, 1418, 1387, 1418,
      327,  334,  342,  329, 1386,  336,  347,  346, 1385,  337,
      348,  338,  351,  352,  357,  358,  359,  365, 1418, 1386,
      368,  369,  373,  379,  380,  383,  386,  389,  393,  396,
      397,  408,  409,  413,  412,  418,  424,  425, 1418, 1385,
     1382, 1418,    0,  448, 1390,    0,  452, 1386,    0,  414,
      428,  398,  427,  442,  431,  399,  449,  450,  390,  451,
      426,  452,  454,  456,  455,  464,  465,  466,  467,  468,
      469, 1379,  472,  471,  470,  474, 1378,  480,  479,  484,

     1377,  486,  488,  489,  490,  494,  505,  497,  512,  500,
      515,  521,  522,  525,  526,  529,  532,  533,  536,  537,
      542,  546, 1418, 1418,  541,  547,  545,  550,  554,  555,
      556,  564,  559,  563, 1376,  567,  566,  569,  572,  492,
      573,  574,  578,  579,  584,  582,  590,  592,  594,  596,
      598,  597,  603,  602,  604,  610,  615,  606,  605,  616,
      619,  627,  631,  634,  638,  642,  648,  651,  652,  662,
      668,  663,  672,  673,  620,  639,  633,  676,  643,  621,
      667, 1418,  507,  675, 1418,  677,  679,  647,  678,  683,
      682,  684,  697,  686,  687, 1418,  692,  696,  691,  707,

      711,  706,  699,  712,  717,  718,  714,  723,  721,  725,
     1375,  731,  732,  736,  741,  742,  745,  749,  753,  756,
      757,  760,  766,  767,  771,  775,  759, 1418,  776, 1418,
      726,  780,  777,  786,  772,  785,  787,  789, 1374, 1418,
      791, 1373,  793, 1418,  794, 1372,  795,  796,  799,  801,
      802,  805,  800,  815,  809,  810,  817,  823,  820,  824,
      831,  835,  836,  840,  846,  845,  852,  853,  859,  860,
      865,  864,  825,  866, 1371, 1418,  867, 1418,  868,  870,
      869,  873,  879,  880,  878, 1338,  890,  883,  888,  889,
     1337, 1329,  891,  894,  897, 1321,  898,  900,  908,  914,

      917,  923,  924,  927,  928,  932,  935,  938,  941,  945,
      949,  911,  948,  942,  953,  957,  961, 1312,  952,  962,
      965, 1418,  964,  956,  968,  970, 1418,  974, 1267,  975,
     1418,  976,  977,  972, 1268,  991,  980, 1001,  986, 1267,
     1002, 1005, 1010, 1266, 1013, 1016, 1021, 1024,  992, 1025,
     1418, 1418, 1418, 1026, 1418, 1418, 1018, 1039, 1263, 1015,
     1262, 1029, 1030, 1037, 1038, 1261, 1040, 1044, 1059, 1049,
     1054, 1064, 1065, 1068, 1069, 1072, 1075, 1076, 1418, 1048,
     1418, 1080, 1260, 1077,  985, 1259, 1418, 1082, 1083, 1086,
     1087, 1090, 1096, 1097, 1101, 1260, 1107, 1111, 1115, 1118,

     1119, 1106, 1112, 1120, 1418, 1123,  821, 1125, 1124, 1256,
     1131, 1132, 1253, 1143, 1147, 1151, 1152, 1155, 1121, 1091,
     1133, 1156, 1157, 1160, 1161, 1164, 1176, 1179, 1180, 1183,
     1184, 1240,  995,  902, 1154, 1169, 1188, 1185, 1198, 1201,
     1205, 1210, 1211, 1215, 1200, 1193, 1212, 1231, 1216, 1230,
     1221, 1224, 1225, 1228, 1236, 1239, 1218, 1189, 1137, 1418,
     1098, 1418, 1243, 1246, 1247, 1058, 1250,  931, 1418, 1159,
     1418, 1418,  903, 1254,  828,  718,  402, 1257, 1418, 1283,
     1290, 1297, 1304, 1311, 1318, 1325,  286, 1332, 1339,  246,
     1341, 1343,  135, 1350, 1357, 1364, 1371, 1378

    } ;

static yyconst flex_int16_t yy_def[599] =
    {   0,
      579,    1,  580,  580,  581,  581,  579,  579,  582,  583,
      584,  584,  585,  585,  579,  579,  579,  579,  579,  586,
      579,  579,  579,  587,  587,  587,  587,  587,  587,  587,
      587,  587,  587,  587,  587,  587,  587,  587,  588,  579,
      589,  579,  579,  579,  579,  579,  579,  586,  579,  579,
      579,  579,  579,  590,  590,  590,  590,  590,  590,  590,
      590,  590,  590,  590,  590,  590,  591,  591,  591,  591,
      591,  591,  591,  591,  591,  591,  591,  591,  591,  579,
      592,  579,  579,  593,  594,  579,  579,  595,  596,  579,
      586,  579,  587,  579,  587,  587,  587,  587,  587,  587,

      587,  587,  587,  587,  587,  587,  587,  587,  587,  587,
      587,  587,  587,  587,  587,  588,  589,  579,  590,  579,
      590,  590,  590,  590,  590,  590,  590,  590,  590,  590,
      590,  590,  590,  590,  590,  590,  590,  591,  579,  579,
      591,  591,  591,  591,  591,  591,  591,  591,  591,  591,
      591,  591,  591,  591,  591,  591,  591,  592,  579,  579,
      593,  579,  594,  595,  597,  594,  596,  598,  594,  587,
      587,  587,  587,  587,  587,  587,  587,  587,  587,  587,
      587,  587,  587,  587,  587,  587,  587,  587,  587,  587,
      590,  590,  590,  590,  590,  590,  590,  590,  590,  590,

      590,  590,  590,  590,  590,  590,  591,  591,  591,  591,
      591,  591,  591,  591,  591,  591,  591,  591,  591,  591,
      591,  591,  579,  579,  587,  587,  587,  587,  587,  587,
      587,  587,  587,  587,  587,  587,  587,  587,  587,  587,
      587,  587,  587,  587,  587,  587,  590,  590,  590,  590,
      590,  590,  590,  590,  590,  590,  590,  590,  590,  590,
      591,  591,  591,  591,  591,  591,  591,  591,  591,  591,
      591,  591,  591,  591,  587,  587,  587,  587,  587,  587,
      587,  579,  587,  587,  579,  587,  587,  587,  587,  587,
      587,  587,  587,  587,  587,  579,  590,  590,  590,  590,

      590,  590,  590,  590,  590,  590,  590,  590,  590,  590,
      590,  591,  591,  591,  591,  591,  591,  591,  591,  591,
      591,  591,  591,  591,  591,  591,  587,  579,  587,  579,
      587,  587,  587,  587,  587,  587,  587,  587,  587,  579,
      587,  587,  587,  579,  587,  587,  590,  590,  590,  590,
      590,  590,  590,  590,  590,  590,  590,  590,  590,  591,
      591,  591,  591,  591,  591,  591,  591,  591,  591,  591,
      591,  591,  587,  587,  587,  579,  587,  579,  587,  587,
      587,  587,  587,  587,  587,  590,  590,  590,  590,  590,
      590,  590,  590,  590,  590,  590,  590,  590,  591,  591,

      591,  591,  591,  591,  591,  591,  591,  591,  591,  591,
      591,  587,  587,  587,  587,  587,  587,  587,  587,  587,
      587,  579,  590,  590,  590,  590,  579,  590,  590,  590,
      579,  590,  590,  590,  579,  591,  591,  591,  591,  579,
      591,  591,  591,  579,  591,  591,  591,  587,  587,  587,
      579,  579,  579,  587,  579,  579,  590,  590,  590,  590,
      590,  590,  590,  590,  590,  590,  590,  591,  591,  591,
      591,  591,  591,  591,  591,  591,  591,  591,  579,  587,
      579,  587,  587,  590,  590,  590,  579,  590,  590,  590,
      590,  590,  591,  591,  591,  579,  591,  591,  591,  591,

      591,  587,  590,  590,  579,  590,  590,  590,  590,  590,
      591,  591,  579,  591,  591,  591,  591,  591,  587,  590,
      590,  590,  590,  590,  590,  591,  591,  591,  591,  591,
      591,  587,  590,  590,  590,  590,  590,  590,  591,  591,
      591,  591,  591,  591,  590,  590,  590,  590,  590,  590,
      591,  591,  591,  591,  591,  591,  590,  590,  590,  579,
      590,  579,  591,  591,  591,  579,  591,  579,  579,  590,
      579,  579,  579,  591,  579,  579,  590,  591,    0,  579,
      579,  579,  579,  579,  579,  579,  579,  579,  579,  579,
      579,  579,  579,  579,  579,  579,  579,  579

    } ;

static yyconst flex_int16_t yy_nxt[1461] =
    {   0,
       16,   17,   18,   17,   16,   19,   20,   16,   21,   16,
       22,   23,   16,   16,   24,   24,   16,   25,   26,   27,
       28,   29,   24,   30,   24,   24,   24,   24,   24,   31,
       32,   33,   34,   24,   35,   36,   37,   24,   24,   24,
       24,   38,   43,   44,   45,   44,   46,   47,   48,   49,
       50,   43,   51,   52,   43,   53,   54,   54,   43,   55,
       54,   56,   57,   58,   54,   59,   54,   60,   61,   54,
       54,   54,   62,   63,   64,   54,   54,   54,   65,   54,
       54,   66,   54,   54,   43,   44,   45,   44,   46,   47,
       48,   49,   50,   43,   51,   52,   43,   53,   67,   67,

       43,   68,   67,   69,   70,   71,   67,   72,   67,   73,
       74,   67,   67,   67,   75,   76,   77,   67,   67,   67,
       78,   67,   67,   79,   67,   67,   80,   80,   80,   80,
       80,   80,   80,   80,   80,   80,   80,   80,   80,   80,
      161,   94,   80,   82,   82,   83,   82,   82,   82,   82,
       82,   82,   82,   82,   82,   82,   82,   94,   96,   82,
       82,   82,   83,   82,   82,   82,   82,   82,   82,   82,
       82,   82,   82,   82,   86,   87,   82,   88,   94,   95,
       89,   87,   86,   87,   90,   88,   90,   94,   89,   87,
       97,   94,   94,   94,  102,  103,  104,   94,   99,   94,

       94,   94,  100,   94,   98,   94,   94,  110,  114,  120,
      105,  101,  109,  111,  106,  107,   90,  120,   90,  108,
      115,  120,  120,  120,  124,  120,  125,  121,  112,  120,
      133,  120,  113,  122,  128,  120,  120,  126,  127,  123,
      132,  120,  120,  129,  130,  134,  137,   94,  139,  136,
      140,  119,   94,  135,  139,  139,  140,  140,  177,   94,
      144,  139,  178,  140,  131,  139,  141,  140,  139,  139,
      140,  140,  142,  148,  139,  139,  140,  140,  143,  149,
      145,  170,  146,  147,  139,  139,  140,  140,  139,  150,
      140,   93,  153,  152,  139,   94,  140,  156,  171,  154,

      157,  159,   90,  160,   90,  165,  165,  155,  166,  151,
      168,  168,  165,   94,   94,   94,  169,  168,   94,   94,
       94,   94,   94,  174,   94,   94,   94,   94,  173,   94,
       94,  172,  184,   94,   94,  183,  176,  187,  175,   94,
      179,  120,  188,  120,  181,  180,  182,  185,  120,  186,
      120,  120,  120,  189,  192,  190,  120,  196,  191,  193,
      120,  120,  120,  196,  194,  120,  120,  197,  195,  200,
      199,  120,  120,  120,  201,  205,  198,  139,  204,  140,
      139,  139,  140,  140,  206,  139,  203,  140,  202,  208,
      209,  139,  139,  140,  140,  139,  212,  140,  139,  207,

      140,  139,  212,  140,   94,  139,  213,  140,  139,  139,
      140,  140,   94,   94,  210,  211,  120,  235,  216,  214,
      139,  139,  140,  140,  139,  139,  140,  140,   94,  215,
      139,  232,  140,  220,  227,  221,  139,  159,  140,  160,
       94,   94,   94,  237,  217,   94,  218,  219,  225,  222,
      165,  165,  231,  166,  168,  168,   94,  165,  228,  229,
      169,  168,  226,   94,   94,   94,   94,  230,   94,   94,
       94,  234,  236,  238,  233,  240,  241,  239,   94,   94,
       94,   94,   94,  120,  120,  120,  120,  250,  120,  246,
      245,  248,  247,  120,  120,  244,  249,  253,  120,  243,

      120,  242,  120,  120,  120,  257,   94,  255,  120,  139,
      251,  140,  139,  290,  140,  252,  254,  139,  256,  140,
      259,   94,  260,  258,  139,  263,  140,  139,  261,  140,
      334,  262,  264,  139,  139,  140,  140,  139,  139,  140,
      140,  139,  267,  140,  139,  139,  140,  140,  139,  139,
      140,  140,  269,  271,  139,   94,  140,  265,  139,   94,
      140,   94,  266,  268,   94,  270,  275,  276,   94,   94,
       94,  272,  273,   94,  274,  281,  282,   94,   94,  285,
       94,   94,  277,   94,  278,  280,   94,   94,   94,  283,
      291,  279,   94,   94,  296,  292,   94,  289,   94,  284,

      294,  288,  287,  286,  120,  295,  120,  297,  120,  298,
      120,  120,  120,  303,  293,  301,  120,  120,  120,  120,
      120,  305,  299,  304,  120,  307,  309,  306,  302,  120,
      120,  139,  300,  140,   94,   94,  312,  311,  327,  139,
      310,  140,  332,  139,  313,  140,  139,   94,  140,  308,
      139,  328,  140,   94,  139,  316,  140,   94,  318,  314,
      139,   94,  140,  139,  139,  140,  140,  329,  338,  320,
      315,  331,  319,  317,  139,  139,  140,  140,  322,  321,
      139,   94,  140,  324,  139,  139,  140,  140,  330,   94,
       94,   94,   94,   94,  326,  340,   94,   94,   94,  341,

       94,   94,  323,  333,  337,  120,  120,  325,  339,  344,
      120,   94,  347,  120,  343,  335,  348,  336,  342,  349,
      120,  120,  345,  346,  350,  120,  120,  355,  120,  351,
      139,  120,  120,  307,  353,  120,  352,  120,  356,  120,
       94,  354,  358,  139,  139,  140,  140,  359,  139,  357,
      140,  360,  361,  139,  139,  140,  140,  139,  363,  140,
      364,  139,  375,  140,  362,  139,  368,  140,  139,  139,
      140,  140,  139,   94,  140,  365,  322,  369,  139,  139,
      140,  140,  367,  139,  366,  140,   94,  139,  371,  140,
       94,   94,  376,  372,   94,  370,  373,  374,  378,   94,

       94,   94,  377,   94,  379,   94,  382,   94,   94,  120,
      120,  389,  384,  120,  120,  120,  120,  380,  381,  120,
      388,  383,  391,  120,  120,  392,  386,  387,  385,  120,
      390,  120,  393,  397,  120,  120,  139,  120,  140,   94,
      139,  395,  396,  139,  394,  140,  402,  139,  139,  140,
      140,  398,  139,  523,  140,  399,  401,  139,  139,  140,
      140,  412,  400,  404,  139,  139,  140,  140,  403,  406,
      405,  139,  139,  140,  140,  410,  139,  139,  140,  140,
       94,   94,   94,   94,   94,  409,  413,   94,  407,  415,
      408,  416,   94,   94,   94,  411,  419,  120,  414,  417,

      423,  420,  120,  120,  120,  120,  423,  430,  120,  418,
      426,  431,  120,  432,  120,  139,  120,  424,  421,  429,
      139,  546,  435,  425,  436,   94,  139,  428,  140,  139,
      436,  140,  448,  433,  434,  139,  139,  140,  140,  139,
      139,  440,  140,  139,  139,  439,  140,  139,  443,  140,
      139,  437,  444,  139,  445,  140,   94,  139,  438,  140,
      442,  139,   94,  140,  449,  451,   94,   94,  441,  452,
      120,   94,  450,  453,  455,   94,   94,  456,  120,   94,
      446,  454,  120,  447,  120,  457,  120,  458,  120,  120,
      120,  120,  139,  459,  140,  461,  462,  464,  139,  120,

      140,  467,  466,  139,  460,  140,   94,  463,  465,  120,
      504,  469,  468,  139,  139,  140,  140,  139,  545,  140,
      471,  480,  139,  472,  140,  139,  470,  140,  139,  120,
      140,  473,  120,  139,  475,  140,  479,  481,   94,   94,
       94,  477,  474,  120,  120,  476,  486,  483,  484,  485,
      478,  120,  120,  120,  120,  485,  139,  492,  140,  488,
      482,  139,   94,  140,  489,  502,  139,  490,  140,  494,
      139,  139,  491,  140,  493,  494,  139,  139,  496,  140,
      139,  139,  140,  140,  139,  495,  140,  139,  139,  140,
      140,  120,  481,  501,   94,  497,  120,  120,  503,  499,

      120,  120,  498,  506,  120,  120,  500,  508,  139,  139,
      140,  140,  572,  139,  507,  513,  533,  511,  509,  139,
       94,  140,  512,  139,  510,  140,  120,  139,  514,  140,
      139,  139,  140,  140,  120,   94,  516,  120,  120,  120,
      519,  520,  515,  139,  139,  140,  140,  120,  532,  517,
      521,  571,  522,  518,  524,  139,  525,  140,  534,  139,
      526,  140,  527,  139,  139,  140,  140,  139,  120,  140,
      120,  120,  528,  120,  120,  120,  139,  547,  140,  529,
      530,  535,  536,  120,  531,  537,  538,  577,  139,  539,
      140,  139,  139,  140,  140,  139,  139,  140,  140,  120,

      548,  540,  120,  120,  541,  542,  570,  120,  543,  544,
      139,  549,  140,  139,  120,  140,  550,  139,  558,  140,
      552,  551,  139,  139,  140,  140,  120,  139,  553,  140,
      120,  557,  569,  139,  555,  140,  139,  139,  140,  140,
      139,  554,  566,  559,  562,  560,  556,  561,  139,  564,
      140,  139,  563,  568,   94,  139,  565,  573,  139,  139,
      140,  575,  139,  574,  576,  139,  139,  567,  140,  139,
      120,  140,  139,  505,   94,  120,  487,  120,  139,  139,
      139,  120,  578,   39,   39,   39,   39,   39,   39,   39,
       41,   41,   41,   41,   41,   41,   41,   80,   80,   80,

       80,   80,   80,   80,   81,   81,   81,   81,   81,   81,
       81,   84,   84,   84,   84,   84,   84,   84,   85,   85,
       85,   85,   85,   85,   85,   91,   94,   91,   91,   91,
       91,   91,  116,  116,  116,  120,  116,  116,  116,  117,
      117,  117,  117,  120,  117,  117,  138,  138,  158,  158,
      163,  427,  422,  163,  163,  163,  163,  164,  164,  164,
      164,  164,  164,  164,  167,  167,  167,  167,  167,  167,
      167,  165,  165,  165,  165,  165,  165,  165,  168,  168,
      168,  168,  168,  168,  168,   94,   94,   94,   94,  120,
       94,  120,  120,  120,  224,  223,  162,  159,  139,  120,

      120,  120,   94,   92,  162,  120,   92,   92,  118,   94,
       92,   92,  579,   42,   42,   40,   40,   15,  579,  579,
      579,  579,  579,  579,  579,  579,  579,  579,  579,  579,
      579,  579,  579,  579,  579,  579,  579,  579,  579,  579,
      579,  579,  579,  579,  579,  579,  579,  579,  579,  579,
      579,  579,  579,  579,  579,  579,  579,  579,  579,  579
    } ;

static yyconst flex_int16_t yy_chk[1461] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    8,    8,    8,    8,    8,    8,
        8,    8,    8,    8,    8,    8,    8,    8,    8,    8,

        8,    8,    8,    8,    8,    8,    8,    8,    8,    8,
        8,    8,    8,    8,    8,    8,    8,    8,    8,    8,
        8,    8,    8,    8,    8,    8,   10,   10,   10,   10,
       10,   10,   10,   10,   10,   10,   10,   10,   10,   10,
      593,   26,   10,   11,   11,   11,   11,   11,   11,   11,
       11,   11,   11,   11,   11,   11,   11,   25,   26,   11,
       12,   12,   12,   12,   12,   12,   12,   12,   12,   12,
       12,   12,   12,   12,   13,   13,   12,   13,   29,   25,
       13,   13,   14,   14,   17,   14,   17,   27,   14,   14,
       27,   28,   30,   31,   29,   30,   31,   32,   28,   33,

       35,   34,   28,   38,   27,   37,   36,   35,   37,   57,
       31,   28,   34,   36,   32,   33,   44,   55,   44,   33,
       38,   56,   58,   62,   56,   63,   57,   55,   36,   65,
       63,   59,   36,   55,   59,   60,   66,   58,   58,   55,
       62,   61,   64,   60,   61,   64,   66,  103,   67,   65,
       67,  590,  102,   64,   68,   69,   68,   69,  102,   95,
       69,   70,  103,   70,   61,   71,   68,   71,   72,   73,
       72,   73,   68,   72,   75,   78,   75,   78,   68,   73,
       70,   95,   71,   71,   74,   76,   74,   76,   79,   74,
       79,  587,   76,   75,   77,   96,   77,   78,   96,   77,

       79,   81,   90,   81,   90,   88,   88,   77,   88,   74,
       89,   89,   88,   97,   98,   99,   89,   89,  100,  101,
      104,  105,  106,   99,  108,  109,  107,  113,   98,  110,
      111,   97,  109,  114,  112,  108,  101,  112,  100,  115,
      104,  121,  113,  124,  106,  105,  107,  110,  122,  111,
      126,  130,  132,  114,  122,  115,  123,  127,  121,  123,
      128,  127,  131,  127,  124,  133,  134,  127,  126,  131,
      130,  135,  136,  137,  132,  136,  128,  138,  135,  138,
      141,  142,  141,  142,  137,  143,  134,  143,  133,  142,
      143,  144,  145,  144,  145,  146,  147,  146,  147,  141,

      147,  148,  147,  148,  179,  149,  147,  149,  150,  151,
      150,  151,  172,  176,  144,  146,  577,  179,  151,  148,
      152,  153,  152,  153,  155,  154,  155,  154,  170,  150,
      156,  176,  156,  155,  172,  156,  157,  158,  157,  158,
      181,  173,  171,  181,  152,  175,  153,  154,  170,  157,
      164,  164,  175,  164,  167,  167,  174,  164,  173,  174,
      167,  167,  171,  177,  178,  180,  182,  174,  183,  185,
      184,  178,  180,  182,  177,  184,  185,  183,  186,  187,
      188,  189,  190,  191,  195,  194,  193,  195,  196,  190,
      189,  193,  191,  199,  198,  188,  194,  198,  200,  187,

      202,  186,  203,  204,  205,  203,  240,  200,  206,  208,
      196,  208,  210,  240,  210,  196,  199,  207,  202,  207,
      205,  283,  206,  204,  209,  210,  209,  211,  207,  211,
      283,  209,  211,  212,  213,  212,  213,  214,  215,  214,
      215,  216,  214,  216,  217,  218,  217,  218,  219,  220,
      219,  220,  216,  219,  221,  225,  221,  212,  222,  227,
      222,  226,  212,  215,  228,  218,  225,  226,  229,  230,
      231,  220,  221,  233,  222,  231,  232,  234,  232,  236,
      237,  236,  227,  238,  228,  230,  239,  241,  242,  233,
      241,  229,  243,  244,  246,  242,  246,  239,  245,  234,

      244,  238,  237,  236,  247,  245,  248,  247,  249,  248,
      250,  252,  251,  253,  243,  251,  254,  253,  255,  259,
      258,  255,  249,  254,  256,  257,  258,  256,  252,  257,
      260,  261,  250,  261,  275,  280,  261,  260,  275,  262,
      259,  262,  280,  263,  262,  263,  264,  277,  264,  257,
      265,  276,  265,  276,  266,  265,  266,  279,  267,  263,
      267,  288,  267,  268,  269,  268,  269,  277,  288,  269,
      264,  279,  268,  266,  270,  272,  270,  272,  271,  270,
      271,  281,  271,  272,  273,  274,  273,  274,  278,  284,
      278,  286,  289,  287,  274,  290,  291,  290,  292,  290,

      294,  295,  271,  281,  287,  299,  297,  273,  289,  293,
      298,  293,  297,  303,  292,  284,  298,  286,  291,  299,
      302,  300,  294,  295,  300,  301,  304,  305,  307,  301,
      576,  305,  306,  308,  303,  309,  302,  308,  306,  310,
      331,  304,  309,  312,  313,  312,  313,  310,  314,  307,
      314,  312,  313,  315,  316,  315,  316,  317,  315,  317,
      316,  318,  331,  318,  314,  319,  320,  319,  320,  321,
      320,  321,  322,  327,  322,  317,  323,  321,  323,  324,
      323,  324,  319,  325,  318,  325,  335,  326,  324,  326,
      329,  333,  332,  325,  332,  322,  327,  329,  334,  336,

      334,  337,  333,  338,  335,  341,  338,  343,  345,  347,
      348,  350,  343,  349,  353,  350,  351,  336,  337,  352,
      349,  341,  352,  355,  356,  353,  347,  348,  345,  354,
      351,  357,  354,  358,  359,  507,  360,  358,  360,  373,
      575,  356,  357,  361,  355,  361,  363,  362,  363,  362,
      363,  359,  364,  507,  364,  360,  362,  366,  365,  366,
      365,  373,  361,  365,  367,  368,  367,  368,  364,  367,
      366,  369,  370,  369,  370,  371,  372,  371,  372,  371,
      374,  377,  379,  381,  380,  370,  374,  382,  368,  379,
      369,  380,  385,  383,  384,  372,  383,  388,  377,  381,

      387,  384,  389,  390,  387,  393,  387,  395,  394,  382,
      390,  395,  397,  395,  398,  573,  534,  388,  385,  394,
      399,  534,  399,  389,  400,  412,  400,  393,  400,  401,
      400,  401,  412,  397,  398,  402,  403,  402,  403,  404,
      405,  404,  405,  568,  406,  403,  406,  407,  408,  407,
      408,  401,  408,  409,  408,  409,  414,  410,  402,  410,
      407,  411,  413,  411,  413,  415,  419,  415,  406,  416,
      424,  416,  414,  417,  420,  417,  420,  421,  423,  421,
      410,  419,  425,  411,  426,  423,  434,  424,  428,  430,
      432,  433,  437,  425,  437,  428,  430,  432,  439,  485,

      439,  434,  433,  436,  426,  436,  449,  430,  432,  533,
      485,  437,  436,  438,  441,  438,  441,  442,  533,  442,
      439,  449,  443,  441,  443,  445,  438,  445,  446,  460,
      446,  443,  457,  447,  445,  447,  448,  450,  448,  450,
      454,  446,  443,  462,  463,  445,  460,  454,  457,  458,
      447,  464,  465,  458,  467,  458,  468,  467,  468,  462,
      450,  470,  480,  470,  463,  480,  471,  464,  471,  469,
      566,  469,  465,  469,  468,  469,  472,  473,  472,  473,
      474,  475,  474,  475,  476,  471,  476,  477,  478,  477,
      478,  484,  482,  478,  482,  473,  488,  489,  484,  475,

      490,  491,  474,  488,  492,  520,  476,  490,  493,  494,
      493,  494,  561,  495,  489,  495,  520,  493,  491,  497,
      502,  497,  494,  498,  492,  498,  503,  499,  497,  499,
      500,  501,  500,  501,  504,  519,  499,  506,  509,  508,
      502,  503,  498,  511,  512,  511,  512,  521,  519,  500,
      504,  559,  506,  501,  508,  514,  509,  514,  521,  515,
      511,  515,  512,  516,  517,  516,  517,  518,  535,  518,
      522,  523,  514,  570,  524,  525,  526,  535,  526,  515,
      516,  522,  523,  536,  517,  524,  525,  570,  527,  526,
      527,  528,  529,  528,  529,  530,  531,  530,  531,  538,

      536,  527,  537,  558,  528,  529,  558,  546,  530,  531,
      539,  537,  539,  540,  545,  540,  538,  541,  546,  541,
      540,  539,  542,  543,  542,  543,  547,  544,  541,  544,
      549,  545,  557,  551,  543,  551,  552,  553,  552,  553,
      554,  542,  554,  547,  550,  548,  544,  549,  555,  552,
      555,  556,  551,  556,  532,  563,  553,  563,  564,  565,
      564,  565,  567,  564,  567,  513,  574,  555,  574,  578,
      510,  578,  496,  486,  483,  466,  461,  459,  444,  440,
      435,  429,  574,  580,  580,  580,  580,  580,  580,  580,
      581,  581,  581,  581,  581,  581,  581,  582,  582,  582,

      582,  582,  582,  582,  583,  583,  583,  583,  583,  583,
      583,  584,  584,  584,  584,  584,  584,  584,  585,  585,
      585,  585,  585,  585,  585,  586,  418,  586,  586,  586,
      586,  586,  588,  588,  588,  396,  588,  588,  588,  589,
      589,  589,  589,  392,  589,  589,  591,  591,  592,  592,
      594,  391,  386,  594,  594,  594,  594,  595,  595,  595,
      595,  595,  595,  595,  596,  596,  596,  596,  596,  596,
      596,  597,  597,  597,  597,  597,  597,  597,  598,  598,
      598,  598,  598,  598,  598,  375,  346,  342,  339,  311,
      235,  201,  197,  192,  168,  165,  161,  160,  140,  129,

      125,  119,   93,   92,   84,   54,   52,   51,   49,   24,
       23,   22,   15,    6,    5,    4,    3,  579,  579,  579,
      579,  579,  579,  579,  579,  579,  579,  579,  579,  579,
      579,  579,  579,  579,  579,  579,  579,  579,  579,  579,
      579,  579,  579,  579,  579,  579,  579,  579,  579,  579,
      579,  579,  579,  579,  579,  579,  579,  579,  579,  579
    } ;

/* Table of booleans, true if rule could match eol. */
static yyconst flex_int32_t yy_rule_can_match_eol[82] =
    {   0,
0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 
    0, 0,     };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int qgz_flex_debug;
int qgz_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *qgztext;
#line 1 "qgames_scanner.l"
#line 2 "qgames_scanner.l"

#include <stdio.h>
#include "symtable.h"
#include "qgames_parser.h"
#include "qgames.h"

/*
 * Crea una definicion (para substitucion)
 * */
void   create_define( char* d );
void   generate_define( );
int    add_parameter_to_def( char* p );
void   init_scanner();
int    defined( char* d );
int    switch_to_define( );


symtable*  symt = NULL;
char*  defactual = NULL;
#define  MAXPARMS  16
char*  defparms[MAXPARMS];
char*  define_body;
int    define_created;
int    define_bodyc = 0;
int    parmcount = 0;
int    totalparm;

#define  MAXBUFFSTACK  16
YY_BUFFER_STATE  buffers[MAXBUFFSTACK];
int        line_buffer[MAXBUFFSTACK];
char*      newdata_buffer[MAXBUFFSTACK];
char*      defname_buffer[MAXBUFFSTACK];
int        sp_buffer = 0;

char       string_ret ; // donde retorna




#line 1052 "qgames_scanner.c"

#define INITIAL 0
#define string 1
#define string2 2
#define code 3
#define define 4
#define define_head 5
#define params 6

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int qgzwrap (void );
#else
extern int qgzwrap (void );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  );
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO fwrite( qgztext, qgzleng, 1, qgzout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( qgzin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( qgzin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, qgzin))==0 && ferror(qgzin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(qgzin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int qgzlex (void);

#define YY_DECL int qgzlex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after qgztext and qgzleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	if ( qgzleng > 0 ) \
		YY_CURRENT_BUFFER_LVALUE->yy_at_bol = \
				(qgztext[qgzleng - 1] == '\n'); \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 50 "qgames_scanner.l"




#line 1219 "qgames_scanner.c"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! qgzin )
			qgzin = stdin;

		if ( ! qgzout )
			qgzout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			qgzensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				qgz_create_buffer(qgzin,YY_BUF_SIZE );
		}

		qgz_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of qgztext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
		yy_current_state += YY_AT_BOL();
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 580 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_current_state != 579 );
		yy_cp = (yy_last_accepting_cpos);
		yy_current_state = (yy_last_accepting_state);

yy_find_action:
		yy_act = yy_accept[yy_current_state];

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			int yyl;
			for ( yyl = 0; yyl < qgzleng; ++yyl )
				if ( qgztext[yyl] == '\n' )
					   
    qgzlineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 54 "qgames_scanner.l"
{ string_ret = YYSTATE; BEGIN(string); qgzlval = 0; }
	YY_BREAK
case 2:
/* rule 2 can match eol */
YY_RULE_SETUP
#line 55 "qgames_scanner.l"
{ qgzlval = (long)strdup(qgztext); 
                      return TOK_STRING;
                    }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 58 "qgames_scanner.l"
{ BEGIN(string_ret); 
                      if( !qgzlval ){ 
                          qgzlval = (long)strdup(""); 
                          return TOK_STRING; }  
                    }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 64 "qgames_scanner.l"
{ string_ret = YYSTATE; BEGIN(string2); qgzlval = 0;  }
	YY_BREAK
case 5:
/* rule 5 can match eol */
YY_RULE_SETUP
#line 65 "qgames_scanner.l"
{ qgzlval = (long)strdup(qgztext); 
                      return TOK_STRING;
                    }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 68 "qgames_scanner.l"
{ BEGIN(string_ret); 
                      if( !qgzlval ){ 
                          qgzlval = (long)strdup(""); 
                          return TOK_STRING; }  
                    }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 75 "qgames_scanner.l"
{ BEGIN(INITIAL); yyless(0); return  TOK_SEPARATOR; }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 76 "qgames_scanner.l"
{ generate_define(); BEGIN(INITIAL); yyless(0); return  TOK_SEPARATOR; }
	YY_BREAK
case 9:
/* rule 9 can match eol */
YY_RULE_SETUP
#line 77 "qgames_scanner.l"
{ define_body[define_bodyc++] = qgztext[0]; }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 79 "qgames_scanner.l"
{ if( !define_created) 
                          create_define( qgztext );
                      else{
                          if( !add_parameter_to_def( qgztext ) ) yyterminate();
                      }
                    } ;
	YY_BREAK
case 11:
/* rule 11 can match eol */
YY_RULE_SETUP
#line 85 "qgames_scanner.l"
{ BEGIN(define); }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 86 "qgames_scanner.l"

	YY_BREAK
case 13:
YY_RULE_SETUP
#line 89 "qgames_scanner.l"
{ return TOK_ATTR;      }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 90 "qgames_scanner.l"
{ return TOK_BOARD ;    }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 91 "qgames_scanner.l"
{ return TOK_CAPTURED_MARK; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 92 "qgames_scanner.l"
{ return TOK_COLOR;     }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 93 "qgames_scanner.l"
{ return TOK_DEFAULT;   }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 94 "qgames_scanner.l"
{ return TOK_DIRECTION; }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 95 "qgames_scanner.l"
{ return TOK_DROP;      }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 96 "qgames_scanner.l"
{ return TOK_ENDING;    }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 97 "qgames_scanner.l"
{ return TOK_GAMETYPE;  }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 98 "qgames_scanner.l"
{ return TOK_MARK;      }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 99 "qgames_scanner.l"
{ return TOK_MOVE;      }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 100 "qgames_scanner.l"
{ return TOK_MOVETYPE;  }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 101 "qgames_scanner.l"
{ return TOK_NOTATION;  }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 102 "qgames_scanner.l"
{ return TOK_ORIGIN;    }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 103 "qgames_scanner.l"
{ return TOK_ONREPEAT;  }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 104 "qgames_scanner.l"
{ return TOK_PIECE;     }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 105 "qgames_scanner.l"
{ return TOK_PIECE_NAME; }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 106 "qgames_scanner.l"
{ return TOK_REPEAT;    }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 107 "qgames_scanner.l"
{ return TOK_SEQUENCE;  }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 108 "qgames_scanner.l"
{ return TOK_SYMMETRY;  }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 109 "qgames_scanner.l"
{ return TOK_START;     }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 110 "qgames_scanner.l"
{ return TOK_TARGET;    }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 111 "qgames_scanner.l"
{ return TOK_ZONE;      }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 113 "qgames_scanner.l"
{ define_created = 0; BEGIN(define_head);   }
	YY_BREAK
case 37:
/* rule 37 can match eol */
YY_RULE_SETUP
#line 115 "qgames_scanner.l"
{ 
                            char* str = strdup( ((char*)qgztext) + 1 );
                            str[qgzleng - 2] = 0;
                            
                            if( !add_parameter_to_def( str ) ) yyterminate();
                            if( parmcount == totalparm ){
                                if( ! switch_to_define( )) yyterminate();
                            }
                            free( str );
                          }
	YY_BREAK
case 38:
/* rule 38 can match eol */
YY_RULE_SETUP
#line 125 "qgames_scanner.l"
{ 
                            char* str = strdup( ((char*)qgztext) + 1 );
                            str[qgzleng - 2] = 0;
                            
                            if( !add_parameter_to_def( str ) ) yyterminate();
                            if( parmcount == totalparm ){
                                if( ! switch_to_define( )) yyterminate();
                            }
                            free( str );
                          }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 135 "qgames_scanner.l"
{ if( !add_parameter_to_def( qgztext ) ) yyterminate();
                            if( parmcount == totalparm ){
                                if( ! switch_to_define( ) )yyterminate();
                            }
                          }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 140 "qgames_scanner.l"
// No hago nada!
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 143 "qgames_scanner.l"
{ return TOK_AND;       }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 144 "qgames_scanner.l"
{ return TOK_AND;       }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 145 "qgames_scanner.l"
{ return TOK_NOT;       }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 146 "qgames_scanner.l"
{ return TOK_NOT;       }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 148 "qgames_scanner.l"
{ return  TOK_AHOGADO;   }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 149 "qgames_scanner.l"
{ return  TOK_ATACADO_ENEMIGO; }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 150 "qgames_scanner.l"
{ return  TOK_CASILLERO_INICIAL; }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 151 "qgames_scanner.l"
{ return TOK_EMPATA;    }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 152 "qgames_scanner.l"
{ return TOK_EMPATA_SI; }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 153 "qgames_scanner.l"
{ return TOK_ENTABLERO;   }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 154 "qgames_scanner.l"
{ return TOK_ENZONA;    }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 155 "qgames_scanner.l"
{ return TOK_GANA;      }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 156 "qgames_scanner.l"
{ return TOK_GANA_SI;   }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 157 "qgames_scanner.l"
{ return TOK_JAQUEMATE; }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 158 "qgames_scanner.l"
{ return TOK_JUEGA;     } 
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 159 "qgames_scanner.l"
{ return TOK_JUEGA_SI;  }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 160 "qgames_scanner.l"
{ return TOK_OCUPADO;   }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 161 "qgames_scanner.l"
{ return TOK_OCUPADOENEMIGO;   }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 162 "qgames_scanner.l"
{ return TOK_OCUPADOPROPIO;   }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 163 "qgames_scanner.l"
{ return TOK_OCUPADOENEMIGO;   }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 164 "qgames_scanner.l"
{ return TOK_OCUPADOPROPIO;   }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 165 "qgames_scanner.l"
{ return  TOK_PARA;        }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 166 "qgames_scanner.l"
{ return  TOK_PARA_SI;     }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 167 "qgames_scanner.l"
{ return  TOK_PIERDE;      }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 168 "qgames_scanner.l"
{ return  TOK_PIERDE_SI;   }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 169 "qgames_scanner.l"
{ return  TOK_TRANSFORMA;  }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 171 "qgames_scanner.l"
{ return TOK_DO;        }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 172 "qgames_scanner.l"
{ return TOK_IF;        }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 173 "qgames_scanner.l"
{ return TOK_END;       }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 174 "qgames_scanner.l"
{ return  TOK_WHILE;       }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 177 "qgames_scanner.l"
{ 
                  qgzlval = atol(qgztext); 
                  return TOK_NUMBER;
                }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 182 "qgames_scanner.l"
{ 
                  qgzlval = (long)strdup(qgztext); 
                  ((char*)(long)qgzlval)[qgzleng] = 0;
                  qgzprintf( "WORD: %s", (char*)(long)qgzlval  );
                  return  TOK_WORD; 
                }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 189 "qgames_scanner.l"
/* ignore whitespace */
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 190 "qgames_scanner.l"
/* ignora comentario */
	YY_BREAK
case 75:
/* rule 75 can match eol */
YY_RULE_SETUP
#line 193 "qgames_scanner.l"
{ return  TOK_SEPARATOR ; }
	YY_BREAK
case 76:
/* rule 76 can match eol */
YY_RULE_SETUP
#line 195 "qgames_scanner.l"
{ return  TOK_SEPCODE; }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 196 "qgames_scanner.l"
{ return  TOK_SEPCODE; }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 197 "qgames_scanner.l"
{
                  int  argc = ( symt ? symtable_argc( symt, qgztext ) : -1 );
                  if( argc == 0 ){
                      parmcount = 0;
                      defactual = strdup( qgztext );
                      switch_to_define( );
                  } else if( argc >= 0 ){
                      parmcount = 0;
                      totalparm = argc;
                      defactual = strdup( qgztext );
                      BEGIN(params);
                  } else {
                      qgzlval = (long)strdup(qgztext); 
                      ((char*)(long)qgzlval)[qgzleng] = 0;
                      return  TOK_WORD; 
                  }
                }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 214 "qgames_scanner.l"
{ return (int) qgztext[0]; }
	YY_BREAK
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(string):
case YY_STATE_EOF(string2):
case YY_STATE_EOF(code):
case YY_STATE_EOF(define):
case YY_STATE_EOF(define_head):
case YY_STATE_EOF(params):
#line 216 "qgames_scanner.l"
{ if( sp_buffer == 0 ){
                      yyterminate();
                  } else {  
                      sp_buffer --;
                      if( newdata_buffer[sp_buffer] ) free( newdata_buffer[sp_buffer] );
                      if( defname_buffer[sp_buffer] ) free( defname_buffer[sp_buffer] );
                      qgz_delete_buffer(YY_CURRENT_BUFFER );
                      qgz_switch_to_buffer(buffers[sp_buffer] );
                      qgzlineno = line_buffer[sp_buffer]  ;
                  }
                }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 228 "qgames_scanner.l"

	YY_BREAK
case 81:
YY_RULE_SETUP
#line 231 "qgames_scanner.l"
ECHO;
	YY_BREAK
#line 1805 "qgames_scanner.c"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed qgzin at a new source and called
			 * qgzlex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = qgzin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_last_accepting_cpos);
				yy_current_state = (yy_last_accepting_state);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( qgzwrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * qgztext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of qgzlex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					qgzrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), (size_t) num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			qgzrestart(qgzin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) qgzrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);
	yy_current_state += YY_AT_BOL();

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 580 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 580 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 579);

	return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp )
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up qgztext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

    if ( c == '\n' ){
        --qgzlineno;
    }

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					qgzrestart(qgzin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( qgzwrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve qgztext */
	(yy_hold_char) = *++(yy_c_buf_p);

	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = (c == '\n');
	if ( YY_CURRENT_BUFFER_LVALUE->yy_at_bol )
		   
    qgzlineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void qgzrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        qgzensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            qgz_create_buffer(qgzin,YY_BUF_SIZE );
	}

	qgz_init_buffer(YY_CURRENT_BUFFER,input_file );
	qgz_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void qgz_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		qgzpop_buffer_state();
	 *		qgzpush_buffer_state(new_buffer);
     */
	qgzensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	qgz_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (qgzwrap()) processing, but the only time this flag
	 * is looked at is after qgzwrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void qgz_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	qgzin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE qgz_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) qgzalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in qgz_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) qgzalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in qgz_create_buffer()" );

	b->yy_is_our_buffer = 1;

	qgz_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with qgz_create_buffer()
 * 
 */
    void qgz_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		qgzfree((void *) b->yy_ch_buf  );

	qgzfree((void *) b  );
}

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a qgzrestart() or at EOF.
 */
    static void qgz_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	qgz_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then qgz_init_buffer was _probably_
     * called from qgzrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void qgz_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		qgz_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void qgzpush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	qgzensure_buffer_stack();

	/* This block is copied from qgz_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from qgz_switch_to_buffer. */
	qgz_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void qgzpop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	qgz_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		qgz_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void qgzensure_buffer_stack (void)
{
	int num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)qgzalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in qgzensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)qgzrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in qgzensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE qgz_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) qgzalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in qgz_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	qgz_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to qgzlex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       qgz_scan_bytes() instead.
 */
YY_BUFFER_STATE qgz_scan_string (yyconst char * yystr )
{
    
	return qgz_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to qgzlex() will
 * scan from a @e copy of @a bytes.
 * @param bytes the byte buffer to scan
 * @param len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE qgz_scan_bytes  (yyconst char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) qgzalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in qgz_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = qgz_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in qgz_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up qgztext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		qgztext[qgzleng] = (yy_hold_char); \
		(yy_c_buf_p) = qgztext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		qgzleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int qgzget_lineno  (void)
{
        
    return qgzlineno;
}

/** Get the input stream.
 * 
 */
FILE *qgzget_in  (void)
{
        return qgzin;
}

/** Get the output stream.
 * 
 */
FILE *qgzget_out  (void)
{
        return qgzout;
}

/** Get the length of the current token.
 * 
 */
int qgzget_leng  (void)
{
        return qgzleng;
}

/** Get the current token.
 * 
 */

char *qgzget_text  (void)
{
        return qgztext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void qgzset_lineno (int  line_number )
{
    
    qgzlineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see qgz_switch_to_buffer
 */
void qgzset_in (FILE *  in_str )
{
        qgzin = in_str ;
}

void qgzset_out (FILE *  out_str )
{
        qgzout = out_str ;
}

int qgzget_debug  (void)
{
        return qgz_flex_debug;
}

void qgzset_debug (int  bdebug )
{
        qgz_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from qgzlex_destroy(), so don't allocate here.
     */

    /* We do not touch qgzlineno unless the option is enabled. */
    qgzlineno =  1;
    
    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    qgzin = stdin;
    qgzout = stdout;
#else
    qgzin = (FILE *) 0;
    qgzout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * qgzlex_init()
     */
    return 0;
}

/* qgzlex_destroy is for both reentrant and non-reentrant scanners. */
int qgzlex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		qgz_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		qgzpop_buffer_state();
	}

	/* Destroy the stack itself. */
	qgzfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * qgzlex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *qgzalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *qgzrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void qgzfree (void * ptr )
{
	free( (char *) ptr );	/* see qgzrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 231 "qgames_scanner.l"




void   init_scanner(){
    if( symt ){
        symtable_free( symt );
        symt = NULL;
    }
    define_created = 0;
    parmcount = 0;
    sp_buffer = 0;
   
}

void   change_to_code_mode(){
    BEGIN(code);
}

int    defined( char* d ){
    if( !symt ) return 0;
    return  symtable_search( symt, d );
}


void   create_define( char* d ){
    define_created = 1;    
    defactual     = strdup( d );
    define_body   = ALLOC( 1024 );
    define_body[0] = 0;
    define_bodyc  = 0;
    parmcount     = 0;
}

int    add_parameter_to_def( char* p ){
    defparms[parmcount++] = strdup( p );   
    if( parmcount >= MAXPARMS ){ 
        qgzerror( "Se alcanzo el maximo de parametros admitidos" );
        return 0;
    }
    return 1;
}


void   generate_define( ){
    int i;
    if( !symt ) symt = symtable_init( );
    define_body[define_bodyc] = 0;
    symtable_adddef( symt, defactual    , parmcount, defparms, define_body );
    free( define_body );
    free( defactual );
    for( i = 0 ; i < parmcount; i ++ ){ free( defparms[i] ); }
}


int    switch_to_define( ){
    if( !symt ){
        qgzerror( "Error resolviendo symt" );
        return 0;
    }

    if( sp_buffer + 1 >= MAXBUFFSTACK ){
        qgzerror( "Maximo alcanzado en stack buffer de defines" );
        return 0;
    }

    char*  data; 
    int i;
    if (!symtable_resolve( symt, defactual, parmcount, defparms, &data ) ){
        qgzerror( "Error resolviendo define" );
        return 0;
    }

       
    // buffers[sp_buffer] = yybuffer
    buffers[sp_buffer] = YY_CURRENT_BUFFER;
    line_buffer[sp_buffer] = qgzlineno;
    qgzlineno = 1;
    newdata_buffer[sp_buffer] = data;
    defname_buffer[sp_buffer] = strdup( defactual );
    sp_buffer ++;

    for( i = 0; i < parmcount ; i ++ ){
        free( defparms[i] );
    }
    free( defactual );

    qgz_scan_string(data );
    BEGIN(code);

    return 1;
    
}


char*  defname_actual( ){
    if( sp_buffer == 0 ) return NULL;
    return( defname_buffer[sp_buffer-1] );
}



