#line 2 "qgames_scanner.c"

#line 4 "qgames_scanner.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define yy_create_buffer qgz_create_buffer
#define yy_delete_buffer qgz_delete_buffer
#define yy_flex_debug qgz_flex_debug
#define yy_init_buffer qgz_init_buffer
#define yy_flush_buffer qgz_flush_buffer
#define yy_load_buffer_state qgz_load_buffer_state
#define yy_switch_to_buffer qgz_switch_to_buffer
#define yyin qgzin
#define yyleng qgzleng
#define yylex qgzlex
#define yylineno qgzlineno
#define yyout qgzout
#define yyrestart qgzrestart
#define yytext qgztext
#define yywrap qgzwrap
#define yyalloc qgzalloc
#define yyrealloc qgzrealloc
#define yyfree qgzfree

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 34
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;
#endif /* ! C99 */

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE qgzrestart(qgzin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#define YY_BUF_SIZE 16384
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

extern int qgzleng;

extern FILE *qgzin, *qgzout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE qgzlex. 
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-qgzlineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < qgzleng; ++yyl )\
                    if ( qgztext[yyl] == '\n' )\
                        --qgzlineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up qgztext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up qgztext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 * Given that the standard has decreed that size_t exists since 1989,
 * I guess we can afford to depend on it. Manoj.
 */

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via qgzrestart()), so that the user can continue scanning by
	 * just pointing qgzin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when qgztext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int qgzleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow qgzwrap()'s to do buffer switches
 * instead of setting up a fresh qgzin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void qgzrestart (FILE *input_file  );
void qgz_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE qgz_create_buffer (FILE *file,int size  );
void qgz_delete_buffer (YY_BUFFER_STATE b  );
void qgz_flush_buffer (YY_BUFFER_STATE b  );
void qgzpush_buffer_state (YY_BUFFER_STATE new_buffer  );
void qgzpop_buffer_state (void );

static void qgzensure_buffer_stack (void );
static void qgz_load_buffer_state (void );
static void qgz_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER qgz_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE qgz_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE qgz_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE qgz_scan_bytes (yyconst char *bytes,int len  );

void *qgzalloc (yy_size_t  );
void *qgzrealloc (void *,yy_size_t  );
void qgzfree (void *  );

#define yy_new_buffer qgz_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        qgzensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            qgz_create_buffer(qgzin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        qgzensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            qgz_create_buffer(qgzin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

typedef unsigned char YY_CHAR;

FILE *qgzin = (FILE *) 0, *qgzout = (FILE *) 0;

typedef int yy_state_type;

extern int qgzlineno;

int qgzlineno = 1;

extern char *qgztext;
#define yytext_ptr qgztext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up qgztext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	qgzleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 87
#define YY_END_OF_BUFFER 88
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[642] =
    {   0,
        0,    0,    2,    2,    5,    5,    0,    0,    0,    0,
        0,    0,    0,    0,   88,   86,   79,   81,    1,   80,
        4,   86,   77,   78,   78,   78,   78,   78,   78,   78,
       78,   78,   78,   78,   78,   78,   78,   78,    2,    3,
        5,    6,   85,   79,   82,   45,    1,   80,   85,    4,
       85,   77,   83,   43,   84,   84,   84,   84,   84,   84,
       84,   84,   84,   84,   84,   84,   84,   84,   84,   84,
       84,   84,   84,   84,   84,   84,   84,   84,   84,   84,
       84,   84,    9,    9,   12,   11,   10,   39,   87,   40,
       39,   39,   79,   80,   77,   78,   78,   78,   78,   78,

       78,   78,   78,   78,   78,   78,   78,   78,   78,   78,
       78,   78,   78,   78,   78,   78,   78,   78,    2,    5,
       44,   42,   84,   84,   84,   84,   84,   84,   73,   84,
       84,   84,   74,   84,   84,   84,   84,   84,   84,   84,
       84,   84,   84,    7,   84,   84,   84,   84,   84,   73,
       84,   84,   84,   74,   84,   84,   84,   84,   84,   84,
       84,   84,   84,    0,    8,    0,   10,   10,   39,   39,
        0,   38,   39,    0,   37,   78,   78,   78,   78,   78,
       78,   78,   78,   78,   78,   78,   78,   78,   78,   78,
       78,   78,   78,   78,   78,   78,   84,   41,   84,   84,

       84,   84,   84,   75,   84,   84,   84,   84,   84,   46,
       84,   84,   84,   84,   84,   84,   84,   41,   84,   84,
       84,   84,   84,   75,   84,   84,   84,   84,   84,   46,
       84,   84,   84,   84,   84,   84,   38,   37,   78,   78,
       78,   78,   78,   78,   78,   78,   78,   78,   22,   78,
       78,   78,   78,   78,   78,   78,   78,   78,   78,   78,
       84,   84,   84,   84,   84,   84,   84,   57,   84,   84,
       84,   67,   84,   84,   84,   84,   84,   84,   84,   84,
       84,   84,   84,   57,   84,   84,   84,   67,   84,   84,
       84,   84,   78,   78,   78,   78,   78,   78,   78,   19,

       78,   78,   23,   78,   78,   78,   78,   78,   78,   78,
       78,   78,   78,   35,   84,   84,   84,   84,   84,   84,
       84,   84,   84,   84,   60,   84,   84,   67,   84,   84,
       84,   84,   76,   84,   84,   84,   84,   84,   84,   84,
       84,   84,   84,   60,   84,   84,   67,   84,   84,   84,
       84,   76,   78,   14,   78,   16,   78,   78,   78,   78,
       78,   78,   78,   78,   26,   78,   28,   78,   30,   78,
       33,   78,   34,   84,   84,   84,   84,   53,   84,   56,
       58,   84,   84,   84,   84,   68,   69,   84,   84,   84,
       84,   84,   84,   53,   84,   56,   58,   84,   84,   84,

       84,   68,   69,   84,   84,   78,   78,   17,   36,   78,
       20,   78,   78,   78,   78,   78,   78,   78,   47,   84,
       84,   84,   84,   84,   56,   84,   61,   62,   84,   84,
       84,   84,   84,   47,   84,   84,   84,   84,   84,   56,
       84,   61,   62,   84,   84,   84,   84,   84,   78,   78,
       78,   78,   78,   78,   27,   78,   78,   78,   47,   84,
       84,   84,   84,   84,   84,   84,   84,   62,   84,   84,
       70,   84,   84,   47,   84,   84,   84,   84,   84,   84,
       84,   84,   62,   84,   84,   70,   84,   84,   78,   78,
       78,   78,   21,   24,   25,   29,   31,   32,   84,   84,

       84,   84,   54,   55,   59,   84,   84,   84,   84,   84,
       84,   84,   84,   54,   55,   59,   84,   84,   84,   84,
       13,   78,   18,   78,   84,   84,   84,   84,   55,   59,
       84,   84,   84,   71,   84,   84,   84,   84,   55,   59,
       84,   84,   84,   71,   78,   84,   84,   84,   84,   84,
       84,   71,   84,   84,   84,   84,   84,   84,   71,   15,
       84,   84,   84,   84,   84,   84,   84,   84,   84,   84,
       84,   84,   84,   84,   84,   84,   64,   84,   84,   84,
       84,   84,   64,   84,   48,   49,   84,   63,   64,   72,
       48,   49,   84,   63,   64,   72,   48,   84,   49,   84,

       84,   84,   63,   72,   48,   84,   49,   84,   84,   84,
       63,   72,   84,   84,   52,   84,   84,   52,   84,   84,
       84,   84,   84,   84,   84,   84,   84,   84,   84,   84,
       84,   50,   84,   50,   51,   50,   51,   50,   51,   51,
        0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    5,    6,    7,    1,    1,    8,    9,    1,
        1,    1,    1,   10,   11,    1,    1,   12,   12,   12,
       12,   12,   12,   12,   12,   12,   12,   13,   14,    1,
       15,    1,   16,    1,   17,   17,   17,   17,   17,   17,
       17,   17,   17,   17,   17,   17,   17,   17,   17,   17,
       17,   17,   17,   17,   17,   17,   17,   17,   17,   17,
        1,    1,    1,    1,   18,    1,   19,   20,   21,   22,

       23,   24,   25,   26,   27,   28,   29,   30,   31,   32,
       33,   34,   35,   36,   37,   38,   39,   40,   41,   17,
       42,   43,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[44] =
    {   0,
        1,    1,    2,    3,    1,    4,    1,    1,    5,    3,
        6,    6,    7,    1,    1,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    6
    } ;

static yyconst flex_int16_t yy_base[661] =
    {   0,
        0,    0, 1621, 1620, 1616, 1615,   43,   86,    0,  129,
      147,  165,  178,  186, 1623, 1628,  189, 1628, 1628,    0,
     1628, 1610, 1609, 1604,  147,  170,  178,  182,  183,  185,
      191,  184,  190,  186,  196,  198,  204,  192,    0, 1628,
        0, 1628, 1628,  225, 1628, 1628, 1628,    0, 1611, 1628,
     1606, 1605, 1628, 1601, 1599,  212,  214,  215,  221,  216,
      218,  227,  223,  233,  241,  235,  225,  229,  246,  251,
      256,  257,  263,  265,  258,  272,  280,  284,  285,  286,
      290,  294, 1628,  301, 1628, 1628, 1598,    0, 1628, 1628,
      312,  320,  261,    0, 1601, 1596, 1628,  270,  309,  130,

      303,  311,  305,  315,  316,  318,  320,  321,  324,  323,
      326,  264,  329,  330,  328,  327,  334,  335,    0,    0,
     1628, 1628, 1595, 1628,  336,  338,  352,  341, 1594,  348,
      361,  358, 1593,  350,  364,  359,  368,  360,  365,  375,
      370,  376,  382, 1628, 1595,  389,  395,  397,  399,  405,
      407,  431,  411,  412,  413,  417,  419,  421,  439,  438,
      443,  449,  451,  450, 1628, 1594, 1590, 1628,    0,  476,
     1599,    0,  480, 1595,    0,  378,  403,  434,  454,  469,
      377,  442,  465,  422,  475,  477,  478,  479,  482,  385,
      483,  485,  487,  489,  492,  493,  494, 1587,  497,  495,

      498,  496,  505, 1586,  510,  506,  511,  512,  515, 1585,
      516,  518,  519,  520,  522,  526,  528,  533,  544,  545,
      546,  550,  553,  554,  561,  563,  565,  569,  573,  574,
      575,  581,  579,  586,  588,  594, 1628, 1628,  587,  589,
      529,  536,  577,  590,  596,  605,  603,  607, 1584,  612,
      610,  613,  611,  614,  615,  616,  617,  620,  626,  628,
      635,  637,  630,  636,  624,  643,  642,  649,  645,  653,
      654,  660,  659,  661,  648,  664,  675,  676,  666,  685,
      687,  689,  691,  695,  701,  703,  714,  718,  722,  705,
      724,  726,  725,  734,  674,  735,  696,  730,  736, 1628,

      740,  741, 1628,  742,  743,  744,  746,  753,  752,  747,
      759,  757,  760, 1628,  764,  765,  766,  761,  773,  777,
      778,  780,  783,  784,  790,  787,  786,  800,  797,  789,
      798,  704, 1551,  806,  813,  817,  818,  825,  827,  833,
      829,  834,  838,  842,  843,  851,  857,  858,  864,  868,
      873,  877,  856, 1628,  809, 1628,  860,  883,  876,  888,
      866,  886,  889,  890, 1550,  788, 1628,  891, 1542,  862,
     1628,  892, 1534,  896,  897,  895,  900,  908,  902, 1525,
     1480,  915,  899,  905,  910, 1479,  922,  926,  919,  932,
      933,  934,  938,  951,  955,  942,  956,  957,  961,  966,

      967,  968,  974,  978,  986,  901,  941, 1478, 1628,  970,
     1628,  972,  981,  985,  989,  925,  990,  820, 1475,  998,
     1002,  992,  994,  999, 1628,  991, 1474, 1014, 1004, 1006,
     1010, 1007, 1018, 1023, 1034, 1033, 1040, 1045, 1047, 1476,
     1046, 1051, 1055, 1056, 1061, 1074, 1078, 1079, 1063, 1085,
     1049, 1084, 1086, 1091, 1472, 1082, 1093, 1097, 1628, 1096,
     1098, 1106, 1102, 1104, 1105, 1109, 1110, 1628, 1107, 1111,
     1471, 1112, 1054, 1473, 1129, 1121, 1130, 1138, 1142, 1143,
     1144, 1149, 1472, 1150, 1157, 1161, 1162, 1171, 1172, 1163,
     1170, 1179, 1628, 1628, 1628, 1467, 1628, 1628, 1113, 1134,

     1164, 1185, 1465, 1400, 1341, 1174, 1165, 1184, 1188, 1192,
     1193, 1197, 1207, 1201, 1206, 1213, 1215, 1217, 1219, 1223,
     1628, 1205, 1628, 1224, 1227, 1228, 1229, 1231, 1628, 1628,
     1233, 1232, 1022, 1236, 1244, 1246, 1252, 1254, 1316, 1283,
     1258, 1260, 1264, 1265, 1266, 1271,  430, 1272, 1275, 1276,
     1277, 1274, 1284, 1292, 1293, 1294, 1299, 1300, 1301, 1268,
     1026, 1303, 1059, 1307, 1308, 1309, 1315, 1317, 1330, 1331,
     1321, 1332, 1322, 1302, 1333, 1334, 1267, 1336, 1345, 1346,
     1350, 1356, 1357, 1358, 1239, 1364, 1360, 1237, 1628, 1145,
     1368, 1381, 1372, 1380,  962, 1387, 1628, 1379, 1628, 1385,

     1370, 1389, 1628, 1628,  914, 1395,  850, 1394, 1396, 1407,
      671,  670, 1238, 1398,  455, 1411, 1409, 1417, 1405, 1412,
     1422, 1427, 1337, 1423, 1428, 1432, 1431, 1433, 1438, 1449,
     1441, 1442, 1451, 1456, 1455,  339, 1460, 1462,  276, 1464,
     1628, 1497, 1504, 1511, 1518, 1525, 1532, 1539,  241, 1546,
     1553,  210, 1555, 1557,  139, 1564, 1571, 1578, 1585, 1592
    } ;

static yyconst flex_int16_t yy_def[661] =
    {   0,
      641,    1,  642,  642,  643,  643,  641,  641,  644,  645,
      646,  646,  647,  647,  641,  641,  641,  641,  641,  648,
      641,  641,  641,  649,  649,  649,  649,  649,  649,  649,
      649,  649,  649,  649,  649,  649,  649,  649,  650,  641,
      651,  641,  641,  641,  641,  641,  641,  648,  641,  641,
      641,  641,  641,  641,  652,  652,  652,  652,  652,  652,
      652,  652,  652,  652,  652,  652,  652,  652,  653,  653,
      653,  653,  653,  653,  653,  653,  653,  653,  653,  653,
      653,  653,  641,  654,  641,  641,  655,  656,  641,  641,
      657,  658,  641,  648,  641,  649,  641,  649,  649,  649,

      649,  649,  649,  649,  649,  649,  649,  649,  649,  649,
      649,  649,  649,  649,  649,  649,  649,  649,  650,  651,
      641,  641,  652,  641,  652,  652,  652,  652,  652,  652,
      652,  652,  652,  652,  652,  652,  652,  652,  652,  652,
      652,  652,  653,  641,  641,  653,  653,  653,  653,  653,
      653,  653,  653,  653,  653,  653,  653,  653,  653,  653,
      653,  653,  653,  654,  641,  641,  655,  641,  656,  657,
      659,  656,  658,  660,  656,  649,  649,  649,  649,  649,
      649,  649,  649,  649,  649,  649,  649,  649,  649,  649,
      649,  649,  649,  649,  649,  649,  652,  652,  652,  652,

      652,  652,  652,  652,  652,  652,  652,  652,  652,  652,
      652,  652,  652,  652,  652,  652,  653,  653,  653,  653,
      653,  653,  152,  653,  653,  653,  653,  653,  653,  653,
      653,  653,  653,  653,  653,  653,  641,  641,  649,  649,
      649,  649,  649,  649,  649,  649,  649,  649,  649,  649,
      649,  649,  649,  649,  649,  649,  649,  649,  649,  649,
      652,  652,  652,  652,  652,  652,  652,  652,  652,  652,
      652,  652,  652,  652,  652,  652,  653,  653,  653,  653,
      653,  653,  653,  653,  653,  653,  653,  653,  653,  653,
      653,  653,  649,  649,  649,  649,  649,  649,  649,  641,

      649,  649,  641,  649,  649,  649,  649,  649,  649,  649,
      649,  649,  649,  641,  652,  652,  652,  652,  652,  652,
      652,  652,  652,  652,  652,  652,  652,  652,  652,  652,
      652,  652,  652,  653,  653,  653,  653,  653,  653,  653,
      653,  653,  653,  653,  653,  653,  653,  653,  653,  653,
      653,  653,  649,  641,  649,  641,  649,  649,  649,  649,
      649,  649,  649,  649,  649,  649,  641,  649,  649,  649,
      641,  649,  649,  652,  652,  652,  652,  652,  652,  652,
      652,  652,  652,  652,  652,  652,  652,  652,  652,  653,
      653,  653,  653,  653,  653,  653,  653,  653,  653,  653,

      653,  653,  653,  653,  653,  649,  649,  649,  641,  649,
      641,  649,  649,  649,  649,  649,  649,  649,  652,  652,
      652,  652,  652,  652,  641,  652,  652,  652,  652,  652,
      652,  652,  652,  653,  653,  653,  653,  653,  653,  641,
      653,  653,  653,  653,  653,  653,  653,  653,  649,  649,
      649,  649,  649,  649,  649,  649,  649,  649,  641,  652,
      652,  652,  652,  652,  652,  652,  652,  641,  652,  652,
      652,  652,  652,  641,  653,  653,  653,  653,  653,  653,
      653,  653,  641,  653,  653,  653,  653,  653,  649,  649,
      649,  649,  641,  641,  641,  649,  641,  641,  652,  652,

      652,  652,  652,  652,  652,  652,  652,  652,  652,  653,
      653,  653,  653,  653,  653,  653,  653,  653,  653,  653,
      641,  649,  641,  649,  652,  652,  652,  652,  641,  641,
      652,  652,  652,  652,  653,  653,  653,  653,  641,  641,
      653,  653,  653,  653,  649,  652,  652,  652,  652,  652,
      652,  652,  653,  653,  653,  653,  653,  653,  653,  649,
      652,  652,  652,  652,  652,  652,  653,  653,  653,  653,
      653,  653,  652,  652,  652,  652,  652,  652,  653,  653,
      653,  653,  653,  653,  652,  652,  652,  652,  641,  652,
      653,  653,  653,  653,  641,  653,  641,  652,  641,  652,

      652,  652,  641,  641,  641,  653,  641,  653,  653,  653,
      641,  641,  652,  652,  652,  653,  653,  653,  652,  652,
      653,  653,  652,  652,  653,  653,  652,  652,  653,  653,
      652,  652,  653,  653,  652,  652,  653,  653,  652,  653,
        0,  641,  641,  641,  641,  641,  641,  641,  641,  641,
      641,  641,  641,  641,  641,  641,  641,  641,  641,  641
    } ;

static yyconst flex_int16_t yy_nxt[1672] =
    {   0,
       16,   17,   18,   17,   16,   19,   20,   16,   21,   16,
       22,   23,   16,   16,   16,   24,   24,   16,   25,   26,
       27,   28,   29,   24,   30,   24,   24,   24,   24,   24,
       31,   32,   33,   34,   24,   35,   36,   37,   24,   24,
       24,   24,   38,   43,   44,   45,   44,   46,   47,   48,
       49,   50,   43,   51,   52,   43,   53,   54,   55,   55,
       43,   56,   55,   57,   58,   59,   55,   60,   55,   61,
       62,   55,   55,   55,   63,   64,   65,   55,   66,   55,
       67,   55,   55,   68,   55,   55,   43,   44,   45,   44,
       46,   47,   48,   49,   50,   43,   51,   52,   43,   53,

       54,   69,   69,   43,   70,   69,   71,   72,   73,   69,
       74,   69,   75,   76,   69,   69,   69,   77,   78,   79,
       69,   80,   69,   81,   69,   69,   82,   69,   69,   83,
       83,   83,   83,   83,   83,   83,   83,   83,   83,   83,
       83,   83,   83,   83,  167,   97,   83,   85,   85,   86,
       85,   85,   85,   85,   85,   85,   85,   85,   85,   85,
       85,   85,   97,  178,   85,   85,   85,   86,   85,   85,
       85,   85,   85,   85,   85,   85,   85,   85,   85,   85,
       89,   90,   85,   91,   98,   97,   92,   90,   89,   90,
       93,   91,   93,   97,   92,   90,  100,   97,   97,   97,

       97,   97,   99,  106,  102,   97,   97,   97,  103,  107,
      101,   97,  112,   97,  105,  123,  109,  104,  113,   97,
      114,  110,  117,  108,  118,  111,   93,  124,   93,  124,
      124,  124,  128,  124,  132,  115,  124,  125,  124,  116,
      124,  133,  124,  126,  124,  134,   96,  129,  124,  127,
      124,  130,  131,  137,  142,  136,  124,  140,  144,  138,
      141,  145,   93,  144,   93,  135,  145,  139,  144,  144,
      144,  145,  145,  145,  149,  144,  146,  144,  145,   97,
      145,  154,  147,  153,  144,   97,  190,  145,  148,  150,
      155,  124,  144,  151,  152,  145,  144,  144,  144,  145,

      145,  145,  144,  159,  158,  145,  144,  176,  161,  145,
      156,  160,  157,  165,  171,  171,  166,  172,   97,  163,
       97,  171,  174,  174,   97,  162,   97,  177,  175,  174,
       97,   97,  179,   97,  180,   97,   97,  183,   97,   97,
      181,   97,   97,   97,   97,   97,  193,  182,  184,   97,
       97,  124,  189,  124,  124,  185,  124,  194,  188,  198,
      186,  187,  191,  124,  192,  124,  196,  124,  197,  195,
      199,  203,  200,  124,  124,  124,  124,  201,  203,  124,
      124,  202,  204,  124,  208,  124,  209,  213,  215,  207,
      124,  124,   97,   97,  144,  212,  210,  145,  205,  245,

       97,  144,  216,  206,  145,  254,  211,  144,  214,  144,
      145,  144,  145,  239,  145,  219,  218,  144,   97,  144,
      145,  217,  145,  144,  144,  144,  145,  145,  145,  144,
      220,  144,  145,  144,  145,  221,  145,   97,  240,  229,
      222,  223,  227,  144,  248,  124,  145,  228,  223,   97,
      144,  144,  224,  145,  145,  144,  230,   97,  145,  231,
      233,  144,  165,  144,  145,  166,  145,  235,  225,   97,
      124,  241,  562,  226,  232,  246,  234,  236,  171,  171,
       97,  172,  174,  174,   97,  171,  242,  243,  175,  174,
       97,  247,   97,   97,   97,  244,  251,   97,   97,  250,

       97,  252,   97,  249,   97,  255,  253,   97,   97,  124,
      124,  124,  124,  124,  265,  260,  259,  262,  261,  258,
      124,  124,  257,  256,  264,  124,  124,  124,  266,  268,
      124,  124,  263,  124,  124,  124,  272,  124,  267,  270,
      144,  124,  205,  145,   97,  144,  274,  206,  145,  271,
      269,   97,  277,  275,  273,  276,  144,  144,  144,  145,
      145,  145,  144,  143,  278,  145,  144,  295,  281,  145,
      143,  296,  280,  144,  143,  144,  145,  144,  145,  282,
      145,  144,  279,  284,  145,  144,  144,  144,  145,  145,
      145,  144,   97,  144,  145,  283,  145,  286,  144,  288,

      144,  145,   97,  145,   97,   97,  144,  285,  287,  145,
      294,   97,  290,  293,  289,  297,  299,  300,   97,  291,
       97,  298,   97,  292,  303,   97,   97,   97,   97,   97,
       97,   97,   97,  309,  301,   97,  308,  307,  310,  124,
      314,   97,  312,   97,  302,  124,  306,  305,  313,  304,
      124,  124,  124,  315,  311,  316,  317,  124,  124,  322,
      124,  319,  320,  124,  124,  318,  322,  324,  124,  124,
      327,  325,  326,  321,  124,  124,  124,  327,  144,  124,
      330,  145,  144,  144,  332,  323,  333,  144,  144,   97,
      145,  145,  336,  334,  335,  328,  329,  144,  331,  144,

      145,  144,  145,  144,  145,  341,  145,  144,  339,  355,
      145,   97,  341,  144,  337,  144,  145,  144,  145,  124,
      145,  344,  340,  343,  338,  357,  144,  389,  346,  145,
      144,  342,  345,  145,  144,  346,  144,  145,  144,  145,
       97,  145,  350,  349,  353,   97,  354,  356,  352,   97,
       97,   97,  358,  347,  348,   97,   97,   97,   97,   97,
      351,   97,   97,  366,  360,  367,  364,   97,   97,  363,
      366,  371,   97,  359,   97,   97,  124,  365,  370,  124,
      124,  124,  361,  362,  368,  374,  375,  376,  124,  369,
      377,  378,  124,  124,  372,  124,  380,  373,  124,  124,

      383,  124,  124,   97,  124,  124,  379,  383,  385,  381,
      327,  387,  124,  124,  382,  124,  323,  327,  144,  368,
      388,  145,  329,  386,   97,  144,  384,  390,  145,  144,
      144,  407,  145,  145,  391,   97,  329,  144,  392,  144,
      145,  144,  145,  394,  145,  144,  144,  393,  145,  145,
      144,  396,  399,  145,  144,  144,  395,  145,  145,  399,
      397,  458,  144,  144,  401,  342,  145,  346,  398,  144,
      144,   97,  145,  145,  346,   97,  144,   97,  400,  145,
      144,   97,  417,  145,  402,  144,  403,  348,  145,  144,
      404,   97,  145,  348,  406,  409,  405,  408,   97,  412,

      411,   97,  410,   97,   97,   97,   97,   97,  415,  416,
      124,  124,  124,  421,  124,  124,   97,  124,  423,  413,
      124,  414,  422,  124,  424,  124,  144,  418,  419,  420,
      124,  427,  429,  426,  124,  384,  431,  124,  449,  429,
       97,  124,  428,  431,  144,  144,  144,  145,  145,  145,
      144,  433,  436,  145,  144,  456,   97,  440,  430,  432,
      437,  438,  450,  144,  434,  435,  145,  144,  144,  144,
      145,  145,  145,  144,  144,  441,  145,  439,  144,  144,
      144,  145,  145,  145,  444,   97,  144,   97,  446,  145,
      144,  444,  442,  145,  452,  446,   97,  400,  144,  443,

       97,  145,  451,  453,   97,   97,  124,  124,  460,  124,
      445,  447,  457,  124,  124,  460,  454,  124,  448,  124,
      461,  124,  124,  462,  467,  124,  455,  463,  466,  468,
      464,  467,  471,  124,  465,  144,  469,  124,  474,  472,
      430,  124,  551,  432,  475,  144,  144,  470,  145,  145,
      573,  475,  144,  473,  477,  145,  476,  144,  144,  144,
      145,  145,  145,  144,   97,  482,  145,  144,  144,  124,
      483,  145,  482,  144,  124,  478,  145,  484,   97,  575,
      492,  479,  480,  481,  509,  489,  144,  486,  485,  145,
      144,  144,  445,  145,  145,  490,  493,   97,  494,   97,

       97,   97,  490,  495,  496,  497,   97,  447,   97,  498,
      487,  124,   97,  124,  488,  491,  500,  124,  461,  124,
      124,  124,  124,  500,  124,  124,  124,  124,  124,  499,
      503,  505,  469,  144,  502,  525,  145,  504,  506,  501,
      511,  144,  144,  470,  145,  145,  507,  511,  508,  124,
      144,  476,  510,  145,  144,  144,  144,  145,  145,  145,
      604,  144,  144,  512,  145,  145,  516,  501,  514,  144,
      513,  484,  145,  144,  144,  515,  145,  145,   97,  124,
      124,  517,  485,  144,  521,   97,  145,   97,  522,  124,
      526,  523,  518,  491,   97,  527,  531,  532,  519,  124,

      124,  520,  527,  124,  144,  144,  534,  145,  145,  144,
      533,  528,  145,  144,  535,  524,  145,  537,  144,  144,
       97,  539,  145,  536,  537,  144,  512,  144,  540,  144,
      145,  144,  145,  538,  145,  144,  523,  541,  145,   97,
      545,  544,  124,  124,  124,  543,  124,  124,  124,  542,
      547,  124,  603,  124,  597,  528,  144,  546,  144,  145,
      619,  145,  548,  549,  144,  550,  144,  145,  554,  145,
      144,  552,  144,  145,  553,  145,  144,  144,  538,  145,
      145,   97,  589,   97,  558,  555,  124,  124,  556,  124,
      124,  124,  124,  557,  560,  144,  144,  561,  563,  145,

      559,  564,  565,  566,  144,  144,  144,  145,  145,  145,
      567,  144,  144,  144,  145,  145,  145,  124,  124,  569,
      570,  574,  124,  124,  124,  571,  572,  144,  144,  144,
      145,  576,  145,  144,  568,  580,  145,  124,  586,  579,
      577,  578,  144,  144,  144,  145,  145,  145,  124,  124,
      581,  124,  124,  583,  585,  582,  530,  144,  144,  587,
      145,  145,  144,  627,  584,  145,  588,  590,  144,  144,
      144,  145,  595,  145,  598,  124,  593,  591,  602,  599,
      144,  598,  592,  605,  144,  124,  600,  145,  594,  596,
      610,  606,  144,  144,  124,  611,  607,  601,  606,  144,

      124,  600,  612,  608,  124,  614,  144,  144,  144,  145,
      145,  145,  601,  124,  609,  529,  613,  608,  615,  144,
      124,  144,  145,  144,  145,  616,  145,  124,  609,  144,
      620,  617,  145,  621,  144,  623,  618,  145,  124,  144,
      144,  622,  145,  145,  144,  624,  124,  145,  124,  628,
      144,  632,  625,  145,  629,  631,  124,  124,  630,  635,
      626,  144,  633,  144,  145,  632,  145,  634,  144,  637,
      124,  145,  144,  635,  144,  145,  144,  145,  636,  145,
      124,  634,   97,  637,  144,  144,  124,   97,  144,  124,
      459,  639,  638,   97,  124,  124,  640,   39,   39,   39,

       39,   39,   39,   39,   41,   41,   41,   41,   41,   41,
       41,   83,   83,   83,   83,   83,   83,   83,   84,   84,
       84,   84,   84,   84,   84,   87,   87,   87,   87,   87,
       87,   87,   88,   88,   88,   88,   88,   88,   88,   94,
      425,   94,   94,   94,   94,   94,  119,  119,  119,   97,
      119,  119,  119,  120,  120,  120,  120,   97,  120,  120,
      143,  143,  164,  164,  169,   97,  124,  169,  169,  169,
      169,  170,  170,  170,  170,  170,  170,  170,  173,  173,
      173,  173,  173,  173,  173,  171,  171,  171,  171,  171,
      171,  171,  174,  174,  174,  174,  174,  174,  174,   97,

      124,  124,  124,  238,  237,  168,  165,  144,  124,  124,
      124,   97,   95,  168,  124,  122,   95,   95,  121,   97,
       95,   95,  641,   42,   42,   40,   40,   15,  641,  641,
      641,  641,  641,  641,  641,  641,  641,  641,  641,  641,
      641,  641,  641,  641,  641,  641,  641,  641,  641,  641,
      641,  641,  641,  641,  641,  641,  641,  641,  641,  641,
      641,  641,  641,  641,  641,  641,  641,  641,  641,  641,
      641
    } ;

static yyconst flex_int16_t yy_chk[1672] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    8,    8,    8,    8,
        8,    8,    8,    8,    8,    8,    8,    8,    8,    8,

        8,    8,    8,    8,    8,    8,    8,    8,    8,    8,
        8,    8,    8,    8,    8,    8,    8,    8,    8,    8,
        8,    8,    8,    8,    8,    8,    8,    8,    8,   10,
       10,   10,   10,   10,   10,   10,   10,   10,   10,   10,
       10,   10,   10,   10,  655,  100,   10,   11,   11,   11,
       11,   11,   11,   11,   11,   11,   11,   11,   11,   11,
       11,   11,   25,  100,   11,   12,   12,   12,   12,   12,
       12,   12,   12,   12,   12,   12,   12,   12,   12,   12,
       13,   13,   12,   13,   25,   26,   13,   13,   14,   14,
       17,   14,   17,   27,   14,   14,   27,   28,   29,   32,

       30,   34,   26,   30,   28,   33,   31,   38,   28,   31,
       27,   35,   34,   36,   29,  652,   32,   28,   35,   37,
       36,   33,   37,   31,   38,   33,   44,   56,   44,   57,
       58,   60,   57,   61,   60,   36,   59,   56,   63,   36,
       67,   61,   62,   56,   68,   62,  649,   58,   64,   56,
       66,   59,   59,   64,   68,   63,   65,   66,   69,   65,
       67,   69,   93,   70,   93,   62,   70,   65,   71,   72,
       75,   71,   72,   75,   71,   73,   70,   74,   73,  112,
       74,   75,   70,   74,   76,   98,  112,   76,   70,   72,
       76,  639,   77,   73,   73,   77,   78,   79,   80,   78,

       79,   80,   81,   79,   78,   81,   82,   98,   80,   82,
       76,   79,   77,   84,   91,   91,   84,   91,  101,   82,
      103,   91,   92,   92,   99,   81,  102,   99,   92,   92,
      104,  105,  101,  106,  102,  107,  108,  105,  110,  109,
      103,  111,  116,  115,  113,  114,  115,  104,  106,  117,
      118,  125,  111,  126,  636,  107,  128,  116,  110,  126,
      108,  109,  113,  130,  114,  134,  118,  127,  125,  117,
      127,  131,  128,  132,  136,  138,  131,  128,  131,  135,
      139,  130,  131,  137,  134,  141,  135,  139,  141,  132,
      140,  142,  181,  176,  143,  138,  136,  143,  131,  181,

      190,  146,  142,  131,  146,  190,  137,  147,  140,  148,
      147,  149,  148,  176,  149,  148,  147,  150,  177,  151,
      150,  146,  151,  153,  154,  155,  153,  154,  155,  156,
      149,  157,  156,  158,  157,  149,  158,  184,  177,  156,
      151,  152,  153,  152,  184,  547,  152,  155,  152,  178,
      160,  159,  152,  160,  159,  161,  157,  182,  161,  158,
      160,  162,  164,  163,  162,  164,  163,  162,  152,  179,
      615,  178,  547,  152,  159,  182,  161,  163,  170,  170,
      183,  170,  173,  173,  180,  170,  179,  180,  173,  173,
      185,  183,  186,  187,  188,  180,  187,  189,  191,  186,

      192,  188,  193,  185,  194,  191,  189,  195,  196,  197,
      200,  202,  199,  201,  202,  196,  195,  199,  197,  194,
      203,  206,  193,  192,  201,  205,  207,  208,  205,  207,
      209,  211,  200,  212,  213,  214,  212,  215,  206,  209,
      217,  216,  203,  217,  241,  218,  214,  203,  218,  211,
      208,  242,  217,  215,  213,  216,  219,  220,  221,  219,
      220,  221,  222,  223,  219,  222,  224,  241,  222,  224,
      223,  242,  221,  225,  223,  226,  225,  227,  226,  225,
      227,  228,  220,  227,  228,  229,  230,  231,  229,  230,
      231,  233,  243,  232,  233,  226,  232,  229,  234,  232,

      235,  234,  239,  235,  240,  244,  236,  228,  231,  236,
      240,  245,  234,  239,  233,  243,  245,  246,  247,  235,
      246,  244,  248,  236,  250,  251,  253,  250,  252,  254,
      255,  256,  257,  255,  247,  258,  254,  253,  256,  265,
      260,  259,  258,  260,  248,  263,  252,  251,  259,  250,
      261,  264,  262,  261,  257,  262,  263,  267,  266,  268,
      269,  265,  266,  275,  268,  264,  268,  269,  270,  271,
      272,  270,  271,  267,  273,  272,  274,  272,  279,  276,
      273,  279,  612,  611,  275,  268,  276,  277,  278,  295,
      277,  278,  279,  277,  278,  272,  272,  280,  274,  281,

      280,  282,  281,  283,  282,  284,  283,  284,  282,  295,
      284,  297,  284,  285,  280,  286,  285,  290,  286,  332,
      290,  286,  283,  285,  281,  297,  287,  332,  288,  287,
      288,  284,  287,  288,  289,  288,  291,  289,  292,  291,
      293,  292,  290,  289,  293,  298,  294,  296,  292,  294,
      296,  299,  298,  288,  288,  301,  302,  304,  305,  306,
      291,  307,  310,  308,  301,  308,  306,  309,  308,  305,
      308,  311,  312,  299,  311,  313,  318,  307,  310,  315,
      316,  317,  302,  304,  308,  315,  316,  317,  319,  309,
      318,  319,  320,  321,  312,  322,  321,  313,  323,  324,

      325,  327,  326,  366,  330,  325,  320,  325,  326,  323,
      328,  330,  329,  331,  324,  328,  322,  328,  334,  366,
      331,  334,  327,  329,  355,  335,  325,  334,  335,  336,
      337,  355,  336,  337,  335,  418,  328,  338,  336,  339,
      338,  341,  339,  338,  341,  340,  342,  337,  340,  342,
      343,  340,  344,  343,  344,  345,  339,  344,  345,  344,
      342,  418,  607,  346,  345,  341,  346,  347,  343,  347,
      348,  353,  347,  348,  347,  357,  349,  370,  344,  349,
      350,  361,  370,  350,  348,  351,  349,  346,  351,  352,
      350,  359,  352,  347,  353,  358,  351,  357,  358,  361,

      360,  362,  359,  360,  363,  364,  368,  372,  364,  368,
      376,  374,  375,  376,  383,  377,  406,  379,  378,  362,
      384,  363,  377,  378,  379,  385,  605,  372,  374,  375,
      382,  384,  387,  382,  389,  383,  388,  387,  406,  387,
      416,  388,  385,  388,  390,  391,  392,  390,  391,  392,
      393,  389,  392,  393,  396,  416,  407,  396,  387,  388,
      393,  394,  407,  394,  390,  391,  394,  395,  397,  398,
      395,  397,  398,  399,  595,  398,  399,  395,  400,  401,
      402,  400,  401,  402,  403,  410,  403,  412,  404,  403,
      404,  403,  400,  404,  412,  404,  413,  399,  405,  401,

      414,  405,  410,  413,  415,  417,  426,  422,  420,  423,
      403,  404,  417,  420,  424,  420,  414,  421,  405,  429,
      420,  430,  432,  421,  428,  431,  415,  422,  426,  428,
      423,  428,  430,  433,  424,  434,  428,  533,  434,  432,
      429,  561,  533,  431,  435,  436,  435,  428,  436,  435,
      561,  435,  437,  433,  436,  437,  435,  438,  441,  439,
      438,  441,  439,  442,  451,  443,  442,  443,  444,  473,
      443,  444,  443,  445,  563,  437,  445,  443,  449,  563,
      451,  438,  439,  441,  473,  449,  446,  445,  443,  446,
      447,  448,  444,  447,  448,  450,  452,  456,  453,  452,

      450,  453,  450,  454,  456,  457,  454,  446,  457,  458,
      447,  460,  458,  461,  448,  450,  462,  463,  460,  464,
      465,  462,  469,  462,  466,  467,  470,  472,  499,  461,
      464,  466,  467,  476,  463,  499,  476,  465,  469,  462,
      477,  475,  477,  467,  475,  477,  470,  477,  472,  500,
      478,  475,  476,  478,  479,  480,  481,  479,  480,  481,
      590,  482,  484,  477,  482,  484,  481,  500,  479,  485,
      478,  482,  485,  486,  487,  480,  486,  487,  490,  501,
      507,  484,  482,  488,  489,  491,  488,  489,  491,  506,
      501,  492,  485,  490,  492,  502,  506,  507,  487,  508,

      502,  488,  502,  509,  510,  511,  509,  510,  511,  512,
      508,  502,  512,  514,  510,  492,  514,  513,  515,  513,
      522,  515,  513,  512,  513,  516,  511,  517,  516,  518,
      517,  519,  518,  513,  519,  520,  524,  517,  520,  524,
      522,  520,  525,  526,  527,  519,  528,  532,  531,  518,
      526,  534,  588,  613,  585,  527,  535,  525,  536,  535,
      613,  536,  528,  531,  537,  532,  538,  537,  536,  538,
      541,  534,  542,  541,  535,  542,  543,  544,  537,  543,
      544,  545,  577,  560,  543,  538,  546,  548,  541,  552,
      549,  550,  551,  542,  545,  540,  553,  546,  548,  553,

      544,  549,  550,  551,  554,  555,  556,  554,  555,  556,
      553,  557,  558,  559,  557,  558,  559,  574,  562,  555,
      556,  562,  564,  565,  566,  557,  558,  567,  539,  568,
      567,  564,  568,  571,  554,  568,  571,  573,  574,  567,
      565,  566,  569,  570,  572,  569,  570,  572,  575,  576,
      569,  578,  623,  571,  573,  570,  505,  579,  580,  575,
      579,  580,  581,  623,  572,  581,  576,  578,  582,  583,
      584,  582,  583,  584,  586,  587,  581,  579,  587,  586,
      591,  586,  580,  591,  593,  601,  586,  593,  582,  584,
      593,  592,  594,  592,  598,  594,  592,  586,  592,  596,

      600,  598,  596,  592,  602,  601,  608,  606,  609,  608,
      606,  609,  598,  614,  592,  504,  600,  606,  602,  610,
      619,  617,  610,  616,  617,  608,  616,  620,  606,  618,
      614,  609,  618,  616,  621,  619,  610,  621,  624,  622,
      625,  617,  622,  625,  626,  620,  627,  626,  628,  624,
      629,  628,  621,  629,  625,  627,  631,  632,  626,  631,
      622,  630,  629,  633,  630,  628,  633,  630,  634,  633,
      635,  634,  637,  631,  638,  637,  640,  638,  632,  640,
      503,  630,  496,  633,  483,  474,  471,  455,  440,  427,
      419,  635,  634,  408,  386,  381,  637,  642,  642,  642,

      642,  642,  642,  642,  643,  643,  643,  643,  643,  643,
      643,  644,  644,  644,  644,  644,  644,  644,  645,  645,
      645,  645,  645,  645,  645,  646,  646,  646,  646,  646,
      646,  646,  647,  647,  647,  647,  647,  647,  647,  648,
      380,  648,  648,  648,  648,  648,  650,  650,  650,  373,
      650,  650,  650,  651,  651,  651,  651,  369,  651,  651,
      653,  653,  654,  654,  656,  365,  333,  656,  656,  656,
      656,  657,  657,  657,  657,  657,  657,  657,  658,  658,
      658,  658,  658,  658,  658,  659,  659,  659,  659,  659,
      659,  659,  660,  660,  660,  660,  660,  660,  660,  249,

      210,  204,  198,  174,  171,  167,  166,  145,  133,  129,
      123,   96,   95,   87,   55,   54,   52,   51,   49,   24,
       23,   22,   15,    6,    5,    4,    3,  641,  641,  641,
      641,  641,  641,  641,  641,  641,  641,  641,  641,  641,
      641,  641,  641,  641,  641,  641,  641,  641,  641,  641,
      641,  641,  641,  641,  641,  641,  641,  641,  641,  641,
      641,  641,  641,  641,  641,  641,  641,  641,  641,  641,
      641
    } ;

/* Table of booleans, true if rule could match eol. */
static yyconst flex_int32_t yy_rule_can_match_eol[88] =
    {   0,
0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 1, 1, 0, 0, 0, 0, 0,     };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int qgz_flex_debug;
int qgz_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *qgztext;
#line 1 "qgames_scanner.l"
#line 2 "qgames_scanner.l"

#include <stdio.h>
#include "symtable.h"
#include "qgames_parser.h"
#include "qgames.h"

/*
 * Crea una definicion (para substitucion)
 * */
void   create_define( char* d );
void   generate_define( );
int    add_parameter_to_def( char* p );
void   init_scanner();
int    defined( char* d );
int    switch_to_define( );


symtable*  symt = NULL;
char*  defactual = NULL;
#define  MAXPARMS  16
char*  defparms[MAXPARMS];
char*  define_body;
int    define_created;
int    define_bodyc = 0;
int    parmcount = 0;
int    totalparm;

#define  MAXBUFFSTACK  16
YY_BUFFER_STATE  buffers[MAXBUFFSTACK];
int        line_buffer[MAXBUFFSTACK];
char*      newdata_buffer[MAXBUFFSTACK];
char*      defname_buffer[MAXBUFFSTACK];
int        sp_buffer = 0;

char       string_ret ; // donde retorna




#line 1120 "qgames_scanner.c"

#define INITIAL 0
#define string 1
#define string2 2
#define code 3
#define define 4
#define define_head 5
#define params 6

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int qgzwrap (void );
#else
extern int qgzwrap (void );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  );
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO fwrite( qgztext, qgzleng, 1, qgzout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( qgzin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( qgzin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, qgzin))==0 && ferror(qgzin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(qgzin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int qgzlex (void);

#define YY_DECL int qgzlex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after qgztext and qgzleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	if ( qgzleng > 0 ) \
		YY_CURRENT_BUFFER_LVALUE->yy_at_bol = \
				(qgztext[qgzleng - 1] == '\n'); \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 51 "qgames_scanner.l"




#line 1287 "qgames_scanner.c"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! qgzin )
			qgzin = stdin;

		if ( ! qgzout )
			qgzout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			qgzensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				qgz_create_buffer(qgzin,YY_BUF_SIZE );
		}

		qgz_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of qgztext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
		yy_current_state += YY_AT_BOL();
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 642 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_current_state != 641 );
		yy_cp = (yy_last_accepting_cpos);
		yy_current_state = (yy_last_accepting_state);

yy_find_action:
		yy_act = yy_accept[yy_current_state];

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			int yyl;
			for ( yyl = 0; yyl < qgzleng; ++yyl )
				if ( qgztext[yyl] == '\n' )
					   
    qgzlineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 55 "qgames_scanner.l"
{ string_ret = YYSTATE; BEGIN(string); qgzlval = 0; }
	YY_BREAK
case 2:
/* rule 2 can match eol */
YY_RULE_SETUP
#line 56 "qgames_scanner.l"
{ qgzlval = (long)strdup(qgztext); 
                      return TOK_STRING;
                    }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 59 "qgames_scanner.l"
{ BEGIN(string_ret); 
                      if( !qgzlval ){ 
                          qgzlval = (long)strdup(""); 
                          return TOK_STRING; }  
                    }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 65 "qgames_scanner.l"
{ string_ret = YYSTATE; BEGIN(string2); qgzlval = 0;  }
	YY_BREAK
case 5:
/* rule 5 can match eol */
YY_RULE_SETUP
#line 66 "qgames_scanner.l"
{ qgzlval = (long)strdup(qgztext); 
                      return TOK_STRING;
                    }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 69 "qgames_scanner.l"
{ BEGIN(string_ret); 
                      if( !qgzlval ){ 
                          qgzlval = (long)strdup(""); 
                          return TOK_STRING; }  
                    }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 76 "qgames_scanner.l"
{ BEGIN(INITIAL); yyless(0); return  TOK_SEPARATOR; }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 77 "qgames_scanner.l"
{ generate_define(); BEGIN(INITIAL); yyless(0); return  TOK_SEPARATOR; }
	YY_BREAK
case 9:
/* rule 9 can match eol */
YY_RULE_SETUP
#line 78 "qgames_scanner.l"
{ define_body[define_bodyc++] = qgztext[0]; }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 80 "qgames_scanner.l"
{ if( !define_created) 
                          create_define( qgztext );
                      else{
                          if( !add_parameter_to_def( qgztext ) ) yyterminate();
                      }
                    } ;
	YY_BREAK
case 11:
/* rule 11 can match eol */
YY_RULE_SETUP
#line 86 "qgames_scanner.l"
{ BEGIN(define); }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 87 "qgames_scanner.l"

	YY_BREAK
case 13:
YY_RULE_SETUP
#line 90 "qgames_scanner.l"
{ return TOK_ATTR;      }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 91 "qgames_scanner.l"
{ return TOK_BOARD ;    }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 92 "qgames_scanner.l"
{ return TOK_CAPTURED_MARK; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 93 "qgames_scanner.l"
{ return TOK_COLOR;     }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 94 "qgames_scanner.l"
{ return TOK_DEFAULT;   }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 95 "qgames_scanner.l"
{ return TOK_DIRECTION; }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 96 "qgames_scanner.l"
{ return TOK_DROP;      }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 97 "qgames_scanner.l"
{ return TOK_ENDING;    }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 98 "qgames_scanner.l"
{ return TOK_GAMETYPE;  }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 99 "qgames_scanner.l"
{ return TOK_MARK;      }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 100 "qgames_scanner.l"
{ return TOK_MOVE;      }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 101 "qgames_scanner.l"
{ return TOK_MOVETYPE;  }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 102 "qgames_scanner.l"
{ return TOK_NOTATION;  }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 103 "qgames_scanner.l"
{ return TOK_ORIGIN;    }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 104 "qgames_scanner.l"
{ return TOK_ONREPEAT;  }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 105 "qgames_scanner.l"
{ return TOK_PIECE;     }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 106 "qgames_scanner.l"
{ return TOK_PIECE_NAME; }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 107 "qgames_scanner.l"
{ return TOK_REPEAT;    }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 108 "qgames_scanner.l"
{ return TOK_SEQUENCE;  }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 109 "qgames_scanner.l"
{ return TOK_SYMMETRY;  }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 110 "qgames_scanner.l"
{ return TOK_START;     }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 111 "qgames_scanner.l"
{ return TOK_TARGET;    }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 112 "qgames_scanner.l"
{ return TOK_ZONE;      }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 114 "qgames_scanner.l"
{ define_created = 0; BEGIN(define_head);   }
	YY_BREAK
case 37:
/* rule 37 can match eol */
YY_RULE_SETUP
#line 116 "qgames_scanner.l"
{ 
                            char* str = strdup( ((char*)qgztext) + 1 );
                            str[qgzleng - 2] = 0;
                            
                            if( !add_parameter_to_def( str ) ) yyterminate();
                            if( parmcount == totalparm ){
                                if( ! switch_to_define( )) yyterminate();
                            }
                            free( str );
                          }
	YY_BREAK
case 38:
/* rule 38 can match eol */
YY_RULE_SETUP
#line 126 "qgames_scanner.l"
{ 
                            char* str = strdup( ((char*)qgztext) + 1 );
                            str[qgzleng - 2] = 0;
                            
                            if( !add_parameter_to_def( str ) ) yyterminate();
                            if( parmcount == totalparm ){
                                if( ! switch_to_define( )) yyterminate();
                            }
                            free( str );
                          }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 136 "qgames_scanner.l"
{ if( !add_parameter_to_def( qgztext ) ) yyterminate();
                            if( parmcount == totalparm ){
                                if( ! switch_to_define( ) )yyterminate();
                            }
                          }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 141 "qgames_scanner.l"
// No hago nada!
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 144 "qgames_scanner.l"
{ return TOK_AND;       }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 145 "qgames_scanner.l"
{ return TOK_DEQUAL;    }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 146 "qgames_scanner.l"
{ return TOK_EQUAL;     }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 147 "qgames_scanner.l"
{ return TOK_AND;       }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 148 "qgames_scanner.l"
{ return TOK_NOT;       }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 149 "qgames_scanner.l"
{ return TOK_NOT;       }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 151 "qgames_scanner.l"
{ return  TOK_AHOGADO;   }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 152 "qgames_scanner.l"
{ return  TOK_ATACADO_ENEMIGO; }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 153 "qgames_scanner.l"
{ return  TOK_CANTIDAD_PIEZAS; }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 154 "qgames_scanner.l"
{ return  TOK_CANTIDAD_PIEZAS_PROPIAS; }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 155 "qgames_scanner.l"
{ return  TOK_CANTIDAD_PIEZAS_ENEMIGAS; }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 156 "qgames_scanner.l"
{ return  TOK_CASILLERO_INICIAL; }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 157 "qgames_scanner.l"
{ return TOK_EMPATA;    }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 158 "qgames_scanner.l"
{ return TOK_EMPATA_SI; }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 159 "qgames_scanner.l"
{ return TOK_ENTABLERO; }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 160 "qgames_scanner.l"
{ return TOK_ENZONA;    }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 161 "qgames_scanner.l"
{ return TOK_GANA;      }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 162 "qgames_scanner.l"
{ return TOK_GANA_SI;   }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 163 "qgames_scanner.l"
{ return TOK_JAQUEMATE; }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 164 "qgames_scanner.l"
{ return TOK_JUEGA;     } 
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 165 "qgames_scanner.l"
{ return TOK_JUEGA_SI;  }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 166 "qgames_scanner.l"
{ return TOK_OCUPADO;   }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 167 "qgames_scanner.l"
{ return TOK_OCUPADOENEMIGO;   }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 168 "qgames_scanner.l"
{ return TOK_OCUPADOPROPIO;   }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 169 "qgames_scanner.l"
{ return TOK_OCUPADOENEMIGO;   }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 170 "qgames_scanner.l"
{ return TOK_OCUPADOPROPIO;   }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 171 "qgames_scanner.l"
{ return  TOK_PARA;        }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 172 "qgames_scanner.l"
{ return  TOK_PARA_SI;     }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 173 "qgames_scanner.l"
{ return  TOK_PIERDE;      }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 174 "qgames_scanner.l"
{ return  TOK_PIERDE_SI;   }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 175 "qgames_scanner.l"
{ return  TOK_TRANSFORMA;  }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 176 "qgames_scanner.l"
{ return  TOK_REPITEPOS; }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 178 "qgames_scanner.l"
{ return TOK_DO;        }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 179 "qgames_scanner.l"
{ return TOK_IF;        }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 180 "qgames_scanner.l"
{ return TOK_END;       }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 181 "qgames_scanner.l"
{ return  TOK_WHILE;       }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 184 "qgames_scanner.l"
{ 
                  qgzlval = atol(qgztext); 
                  return TOK_NUMBER;
                }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 189 "qgames_scanner.l"
{ 
                  qgzlval = (long)strdup(qgztext); 
                  ((char*)(long)qgzlval)[qgzleng] = 0;
                  qgzprintf( "WORD: %s", (char*)(long)qgzlval  );
                  return  TOK_WORD; 
                }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 196 "qgames_scanner.l"
/* ignore whitespace */
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 197 "qgames_scanner.l"
/* ignora comentario */
	YY_BREAK
case 81:
/* rule 81 can match eol */
YY_RULE_SETUP
#line 200 "qgames_scanner.l"
{ return  TOK_SEPARATOR ; }
	YY_BREAK
case 82:
/* rule 82 can match eol */
YY_RULE_SETUP
#line 202 "qgames_scanner.l"
{ return  TOK_SEPCODE; }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 203 "qgames_scanner.l"
{ return  TOK_SEPCODE; }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 204 "qgames_scanner.l"
{
                  int  argc = ( symt ? symtable_argc( symt, qgztext ) : -1 );
                  if( argc == 0 ){
                      parmcount = 0;
                      defactual = strdup( qgztext );
                      switch_to_define( );
                  } else if( argc >= 0 ){
                      parmcount = 0;
                      totalparm = argc;
                      defactual = strdup( qgztext );
                      BEGIN(params);
                  } else {
                      qgzlval = (long)strdup(qgztext); 
                      ((char*)(long)qgzlval)[qgzleng] = 0;
                      return  TOK_WORD; 
                  }
                }
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 221 "qgames_scanner.l"
{ return (int) qgztext[0]; }
	YY_BREAK
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(string):
case YY_STATE_EOF(string2):
case YY_STATE_EOF(code):
case YY_STATE_EOF(define):
case YY_STATE_EOF(define_head):
case YY_STATE_EOF(params):
#line 223 "qgames_scanner.l"
{ if( sp_buffer == 0 ){
                      yyterminate();
                  } else {  
                      sp_buffer --;
                      if( newdata_buffer[sp_buffer] ) free( newdata_buffer[sp_buffer] );
                      if( defname_buffer[sp_buffer] ) free( defname_buffer[sp_buffer] );
                      qgz_delete_buffer(YY_CURRENT_BUFFER );
                      qgz_switch_to_buffer(buffers[sp_buffer] );
                      qgzlineno = line_buffer[sp_buffer]  ;
                  }
                }
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 235 "qgames_scanner.l"

	YY_BREAK
case 87:
YY_RULE_SETUP
#line 238 "qgames_scanner.l"
ECHO;
	YY_BREAK
#line 1903 "qgames_scanner.c"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed qgzin at a new source and called
			 * qgzlex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = qgzin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_last_accepting_cpos);
				yy_current_state = (yy_last_accepting_state);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( qgzwrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * qgztext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of qgzlex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					qgzrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), (size_t) num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			qgzrestart(qgzin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) qgzrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);
	yy_current_state += YY_AT_BOL();

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 642 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 642 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 641);

	return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp )
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up qgztext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

    if ( c == '\n' ){
        --qgzlineno;
    }

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					qgzrestart(qgzin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( qgzwrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve qgztext */
	(yy_hold_char) = *++(yy_c_buf_p);

	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = (c == '\n');
	if ( YY_CURRENT_BUFFER_LVALUE->yy_at_bol )
		   
    qgzlineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void qgzrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        qgzensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            qgz_create_buffer(qgzin,YY_BUF_SIZE );
	}

	qgz_init_buffer(YY_CURRENT_BUFFER,input_file );
	qgz_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void qgz_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		qgzpop_buffer_state();
	 *		qgzpush_buffer_state(new_buffer);
     */
	qgzensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	qgz_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (qgzwrap()) processing, but the only time this flag
	 * is looked at is after qgzwrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void qgz_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	qgzin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE qgz_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) qgzalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in qgz_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) qgzalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in qgz_create_buffer()" );

	b->yy_is_our_buffer = 1;

	qgz_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with qgz_create_buffer()
 * 
 */
    void qgz_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		qgzfree((void *) b->yy_ch_buf  );

	qgzfree((void *) b  );
}

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a qgzrestart() or at EOF.
 */
    static void qgz_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	qgz_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then qgz_init_buffer was _probably_
     * called from qgzrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void qgz_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		qgz_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void qgzpush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	qgzensure_buffer_stack();

	/* This block is copied from qgz_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from qgz_switch_to_buffer. */
	qgz_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void qgzpop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	qgz_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		qgz_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void qgzensure_buffer_stack (void)
{
	int num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)qgzalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in qgzensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)qgzrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in qgzensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE qgz_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) qgzalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in qgz_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	qgz_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to qgzlex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       qgz_scan_bytes() instead.
 */
YY_BUFFER_STATE qgz_scan_string (yyconst char * yystr )
{
    
	return qgz_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to qgzlex() will
 * scan from a @e copy of @a bytes.
 * @param bytes the byte buffer to scan
 * @param len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE qgz_scan_bytes  (yyconst char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) qgzalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in qgz_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = qgz_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in qgz_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up qgztext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		qgztext[qgzleng] = (yy_hold_char); \
		(yy_c_buf_p) = qgztext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		qgzleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int qgzget_lineno  (void)
{
        
    return qgzlineno;
}

/** Get the input stream.
 * 
 */
FILE *qgzget_in  (void)
{
        return qgzin;
}

/** Get the output stream.
 * 
 */
FILE *qgzget_out  (void)
{
        return qgzout;
}

/** Get the length of the current token.
 * 
 */
int qgzget_leng  (void)
{
        return qgzleng;
}

/** Get the current token.
 * 
 */

char *qgzget_text  (void)
{
        return qgztext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void qgzset_lineno (int  line_number )
{
    
    qgzlineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see qgz_switch_to_buffer
 */
void qgzset_in (FILE *  in_str )
{
        qgzin = in_str ;
}

void qgzset_out (FILE *  out_str )
{
        qgzout = out_str ;
}

int qgzget_debug  (void)
{
        return qgz_flex_debug;
}

void qgzset_debug (int  bdebug )
{
        qgz_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from qgzlex_destroy(), so don't allocate here.
     */

    /* We do not touch qgzlineno unless the option is enabled. */
    qgzlineno =  1;
    
    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    qgzin = stdin;
    qgzout = stdout;
#else
    qgzin = (FILE *) 0;
    qgzout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * qgzlex_init()
     */
    return 0;
}

/* qgzlex_destroy is for both reentrant and non-reentrant scanners. */
int qgzlex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		qgz_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		qgzpop_buffer_state();
	}

	/* Destroy the stack itself. */
	qgzfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * qgzlex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *qgzalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *qgzrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void qgzfree (void * ptr )
{
	free( (char *) ptr );	/* see qgzrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 238 "qgames_scanner.l"




void   init_scanner(){
    if( symt ){
        symtable_free( symt );
        symt = NULL;
    }
    define_created = 0;
    parmcount = 0;
    sp_buffer = 0;
   
}

void   change_to_code_mode(){
    BEGIN(code);
}

int    defined( char* d ){
    if( !symt ) return 0;
    return  symtable_search( symt, d );
}


void   create_define( char* d ){
    define_created = 1;    
    defactual     = strdup( d );
    define_body   = ALLOC( 1024 );
    define_body[0] = 0;
    define_bodyc  = 0;
    parmcount     = 0;
}

int    add_parameter_to_def( char* p ){
    defparms[parmcount++] = strdup( p );   
    if( parmcount >= MAXPARMS ){ 
        qgzerror( "Se alcanzo el maximo de parametros admitidos" );
        return 0;
    }
    return 1;
}


void   generate_define( ){
    int i;
    if( !symt ) symt = symtable_init( );
    define_body[define_bodyc] = 0;
    symtable_adddef( symt, defactual    , parmcount, defparms, define_body );
    free( define_body );
    free( defactual );
    for( i = 0 ; i < parmcount; i ++ ){ free( defparms[i] ); }
}


int    switch_to_define( ){
    if( !symt ){
        qgzerror( "Error resolviendo symt" );
        return 0;
    }

    if( sp_buffer + 1 >= MAXBUFFSTACK ){
        qgzerror( "Maximo alcanzado en stack buffer de defines" );
        return 0;
    }

    char*  data; 
    int i;
    if (!symtable_resolve( symt, defactual, parmcount, defparms, &data ) ){
        qgzerror( "Error resolviendo define" );
        return 0;
    }

       
    // buffers[sp_buffer] = yybuffer
    buffers[sp_buffer] = YY_CURRENT_BUFFER;
    line_buffer[sp_buffer] = qgzlineno;
    qgzlineno = 1;
    newdata_buffer[sp_buffer] = data;
    defname_buffer[sp_buffer] = strdup( defactual );
    sp_buffer ++;

    for( i = 0; i < parmcount ; i ++ ){
        free( defparms[i] );
    }
    free( defactual );

    qgz_scan_string(data );
    BEGIN(code);

    return 1;
    
}


char*  defname_actual( ){
    if( sp_buffer == 0 ) return NULL;
    return( defname_buffer[sp_buffer-1] );
}



