#line 2 "qgames_scanner.c"

#line 4 "qgames_scanner.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define yy_create_buffer qgz_create_buffer
#define yy_delete_buffer qgz_delete_buffer
#define yy_flex_debug qgz_flex_debug
#define yy_init_buffer qgz_init_buffer
#define yy_flush_buffer qgz_flush_buffer
#define yy_load_buffer_state qgz_load_buffer_state
#define yy_switch_to_buffer qgz_switch_to_buffer
#define yyin qgzin
#define yyleng qgzleng
#define yylex qgzlex
#define yylineno qgzlineno
#define yyout qgzout
#define yyrestart qgzrestart
#define yytext qgztext
#define yywrap qgzwrap
#define yyalloc qgzalloc
#define yyrealloc qgzrealloc
#define yyfree qgzfree

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 34
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;
#endif /* ! C99 */

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE qgzrestart(qgzin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#define YY_BUF_SIZE 16384
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

extern int qgzleng;

extern FILE *qgzin, *qgzout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE qgzlex. 
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-qgzlineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < qgzleng; ++yyl )\
                    if ( qgztext[yyl] == '\n' )\
                        --qgzlineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up qgztext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up qgztext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 * Given that the standard has decreed that size_t exists since 1989,
 * I guess we can afford to depend on it. Manoj.
 */

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via qgzrestart()), so that the user can continue scanning by
	 * just pointing qgzin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when qgztext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int qgzleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow qgzwrap()'s to do buffer switches
 * instead of setting up a fresh qgzin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void qgzrestart (FILE *input_file  );
void qgz_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE qgz_create_buffer (FILE *file,int size  );
void qgz_delete_buffer (YY_BUFFER_STATE b  );
void qgz_flush_buffer (YY_BUFFER_STATE b  );
void qgzpush_buffer_state (YY_BUFFER_STATE new_buffer  );
void qgzpop_buffer_state (void );

static void qgzensure_buffer_stack (void );
static void qgz_load_buffer_state (void );
static void qgz_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER qgz_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE qgz_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE qgz_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE qgz_scan_bytes (yyconst char *bytes,int len  );

void *qgzalloc (yy_size_t  );
void *qgzrealloc (void *,yy_size_t  );
void qgzfree (void *  );

#define yy_new_buffer qgz_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        qgzensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            qgz_create_buffer(qgzin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        qgzensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            qgz_create_buffer(qgzin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

typedef unsigned char YY_CHAR;

FILE *qgzin = (FILE *) 0, *qgzout = (FILE *) 0;

typedef int yy_state_type;

extern int qgzlineno;

int qgzlineno = 1;

extern char *qgztext;
#define yytext_ptr qgztext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up qgztext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	qgzleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 44
#define YY_END_OF_BUFFER 45
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[264] =
    {   0,
        0,    0,    2,    2,    0,    0,    0,    0,    0,    0,
       45,   43,   37,   39,    1,   38,   43,   35,   36,   36,
       36,   36,   36,   36,   36,   36,   36,   36,   36,    2,
        3,   42,   37,   40,   38,   42,   35,   41,   36,   36,
       36,   36,   36,   36,   36,   36,   36,   36,   36,   36,
       36,   36,   36,   36,    7,    6,    7,   10,    9,    8,
       37,   38,   35,   36,   36,   36,   36,   36,   36,   36,
       36,   36,   36,   36,   36,   36,   36,   36,    2,   36,
       36,   36,   29,   36,   36,   36,   36,   36,    4,   36,
       36,   36,   36,   29,   36,   36,   36,   36,    0,    5,

        0,    8,    8,   36,   36,   36,   36,   36,   36,   36,
       36,   36,   36,   36,   36,   36,   36,   36,   36,   36,
       36,   36,   36,   36,   36,   36,   36,   36,   36,   36,
       36,   36,   36,   36,   36,   36,   36,   36,   36,   36,
       36,   36,   36,   36,   36,   27,   36,   36,   33,   36,
       36,   36,   27,   36,   36,   33,   36,   36,   36,   36,
       36,   36,   15,   36,   36,   18,   36,   36,   36,   36,
       23,   36,   36,   28,   36,   33,   36,   36,   36,   28,
       36,   33,   36,   36,   12,   13,   36,   36,   36,   36,
       36,   20,   21,   36,   36,   26,   36,   34,   36,   26,

       36,   34,   36,   24,   36,   16,   36,   36,   36,   25,
       30,   25,   30,   36,   36,   36,   36,   36,   25,   30,
       36,   25,   30,   36,   36,   36,   17,   19,   22,   36,
       36,   36,   36,   11,   14,   36,   36,   36,   36,   36,
       36,   36,   36,   36,   36,   36,   36,   36,   36,   36,
       36,   36,   36,   32,   36,   32,   31,   32,   31,   32,
       31,   31,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    4,    5,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    6,    1,    1,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    8,    9,    1,
        1,    1,   10,    1,   11,   11,   11,   11,   11,   11,
       11,   11,   11,   11,   11,   11,   11,   11,   11,   11,
       11,   11,   11,   11,   11,   11,   11,   11,   11,   11,
        1,    1,    1,    1,   12,    1,   13,   14,   15,   16,

       17,   18,   19,   20,   21,   22,   11,   23,   24,   25,
       26,   27,   11,   28,   29,   30,   31,   32,   11,   11,
       33,   34,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[35] =
    {   0,
        1,    1,    2,    3,    1,    4,    4,    5,    1,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4
    } ;

static yyconst flex_int16_t yy_base[274] =
    {   0,
        0,    0,  619,  618,   34,   68,  618,  102,  114,  126,
      620,  624,  617,  624,  624,    0,  611,  610,  606,  114,
      115,  126,  129,  130,  132,  127,  133,  137,  138,    0,
      624,  624,  613,  624,    0,  607,  606,  624,  596,  139,
      141,  148,  150,  146,  156,  159,  165,  166,  171,  174,
      175,  180,  181,  184,  624,  624,  190,  624,  624,  590,
      575,    0,  569,  565,  624,  189,  191,  192,  196,  193,
      152,  197,  198,  199,  200,  210,  202,  208,    0,  206,
      214,  215,  564,  217,  218,  219,  220,  228,  624,  565,
      234,  235,  238,  242,  247,  243,  248,  251,  257,  624,

      564,  561,  624,  244,  256,  259,  260,  261,  263,  265,
      270,  272,  273,  267,  269,  281,  282,  284,  286,  290,
      292,  293,  294,  297,  300,  304,  310,  313,  317,  316,
      318,  321,  305,  322,  326,  335,  324,  325,  338,  340,
      328,  342,  343,  350,  332,  559,  351,  356,  344,  355,
      365,  366,  369,  372,  373,  379,  382,  225,  383,  387,
      384,  374,  624,  389,  378,  624,  390,  395,  402,  392,
      624,  399,  357,  558,  403,  557,  404,  408,  417,  418,
      421,  424,  425,  407,  624,  624,  431,  426,  435,  430,
      434,  624,  624,  436,  439,  555,  440,  547,  443,  444,

      448,  452,  438,  624,  445,  624,  453,  462,  449,  546,
      463,  468,  473,  467,  470,  478,  479,  482,  624,  624,
      481,  541,  515,  486,  489,  492,  624,  624,  624,  491,
      483,  497,  496,  624,  624,  502,  508,  504,  509,  519,
      396,  505,  523,  526,  499,  518,  527,  530,  531,  532,
      536,  544,  533,  457,  552,  553,  346,  624,  556,  303,
      624,  155,  624,  578,  583,  588,  593,  598,  109,  603,
      605,  607,  108
    } ;

static yyconst flex_int16_t yy_def[274] =
    {   0,
      263,    1,  264,  264,  263,  263,  265,  266,  267,  267,
      263,  263,  263,  263,  263,  268,  263,  263,  269,  269,
      269,  269,  269,  269,  269,  269,  269,  269,  269,  270,
      263,  263,  263,  263,  268,  263,  263,  263,  269,  269,
      269,  269,  269,  269,  269,  269,  271,  271,  271,  271,
      271,  271,  271,  271,  263,  263,  272,  263,  263,  273,
      263,  268,  263,  269,  263,  269,  269,  269,  269,  269,
      269,  269,  269,  269,  269,  269,  269,  269,  270,  269,
      269,  269,  269,  269,  269,  269,  269,  271,  263,  263,
      271,  271,  271,  271,  271,  271,  271,  271,  272,  263,

      263,  273,  263,  269,  269,  269,  269,  269,  269,  269,
      269,  269,  269,  269,  269,  269,  269,  269,  269,  269,
      269,  269,  269,  271,  271,  271,  271,  271,  271,  271,
      269,  269,  269,  269,  269,  269,  269,  269,  269,  269,
      269,  269,  269,  269,  269,  269,  269,  269,  269,  269,
      271,  271,  271,  271,  271,  271,  271,  269,  269,  269,
      269,  269,  263,  269,  269,  263,  269,  269,  269,  269,
      263,  269,  269,  269,  269,  269,  269,  271,  271,  271,
      271,  271,  271,  269,  263,  263,  269,  269,  269,  269,
      269,  263,  263,  269,  269,  269,  269,  269,  271,  271,

      271,  271,  269,  263,  269,  263,  269,  269,  269,  269,
      269,  271,  271,  269,  269,  269,  269,  269,  263,  263,
      269,  263,  263,  271,  269,  269,  263,  263,  263,  269,
      269,  271,  271,  263,  263,  269,  269,  269,  271,  271,
      269,  269,  271,  271,  269,  269,  271,  271,  269,  269,
      271,  271,  269,  269,  271,  271,  269,  263,  271,  263,
      263,  263,    0,  263,  263,  263,  263,  263,  263,  263,
      263,  263,  263
    } ;

static yyconst flex_int16_t yy_nxt[659] =
    {   0,
       12,   13,   14,   15,   16,   17,   18,   12,   12,   19,
       19,   12,   20,   21,   22,   23,   24,   19,   25,   19,
       19,   19,   19,   26,   19,   19,   27,   19,   28,   19,
       19,   19,   19,   29,   32,   33,   34,   32,   35,   36,
       37,   32,   38,   39,   39,   32,   40,   39,   39,   39,
       41,   39,   42,   39,   43,   44,   39,   39,   39,   45,
       46,   39,   39,   39,   39,   39,   39,   39,   32,   33,
       34,   32,   35,   36,   37,   32,   38,   47,   47,   32,
       48,   47,   47,   47,   49,   47,   50,   47,   51,   52,
       47,   47,   47,   53,   54,   47,   47,   47,   47,   47,

       47,   47,   55,   55,   56,   55,   55,   55,   55,   55,
       55,  102,   64,   55,   58,   58,   59,   58,   58,   58,
       58,   58,   58,   65,   65,   58,   58,   58,   59,   58,
       58,   58,   58,   58,   58,   65,   65,   58,   65,   65,
       67,   65,   65,   66,   73,   69,   65,   65,   65,   70,
       65,   68,   74,   75,   72,   65,   71,   65,   80,   65,
       82,   65,   89,   78,   81,   65,   76,   83,   65,   77,
       85,   86,   89,   89,   90,   90,   84,  109,   89,   87,
       90,   89,   89,   90,   90,   91,   93,   89,   89,   90,
       90,   89,   94,   90,   92,   96,   97,  100,   65,  101,

       65,   65,   65,  105,   98,   65,   65,   65,   65,   65,
       95,   65,  110,  107,  106,   65,  113,   65,  104,   65,
      108,  111,  114,   65,   65,  115,   65,   65,   65,   65,
      112,  117,  116,  120,   65,   89,  123,   90,  184,  119,
      118,   89,   89,   90,   90,   89,  122,   90,  121,   89,
       89,   90,   90,   65,   89,   89,   90,   90,   89,  124,
       90,  125,  126,  127,  100,   65,  101,  130,   65,   65,
       65,  131,   65,  128,   65,  129,   65,  135,   65,   65,
      134,   65,   65,  132,  133,  137,  138,  140,  139,  136,
       65,   65,  142,   65,  141,   65,  145,  143,  146,   65,

      144,   65,   65,   65,   89,  149,   90,   89,  147,   90,
       89,   89,  152,   90,   65,  151,  153,   89,  148,   90,
       89,  150,   90,   89,   89,   90,   90,   65,  154,  156,
       65,   65,  160,   65,   65,   65,  159,   65,  158,  155,
      162,   65,  163,  157,   65,  166,  161,   65,  164,   65,
      171,   65,   65,   65,  165,  261,  168,  169,  170,   65,
       65,  173,  172,  174,   65,   65,   65,  167,  175,  196,
      177,  176,   89,   89,   90,   90,   89,  178,   90,   89,
       89,   90,   90,   65,  180,  181,   89,   65,   90,   89,
      185,   90,   65,   65,  186,  179,   65,  183,   65,   65,

      187,   65,  192,  188,   65,   65,  182,  189,   65,  193,
      190,   65,   65,   65,  195,   89,   65,   90,  197,  245,
      198,  194,  191,  199,   89,   89,   90,   90,   89,  200,
       90,   89,   89,   90,   90,   65,  201,  203,  204,   65,
       65,  202,  206,   65,   65,   65,  205,   65,   65,   65,
       89,   89,   90,   90,   65,   89,  207,   90,   65,   89,
      208,   90,   65,  209,  210,  211,  258,  214,  212,  216,
      215,   65,  220,  213,  221,   89,   65,  222,  217,   65,
       89,  218,  223,  225,  224,  227,  228,   65,   65,  229,
       65,   65,   65,   89,  226,   90,  234,  230,   65,  235,

       65,   65,  232,   89,   89,   90,   90,  231,   65,  235,
      238,   65,  233,   65,   65,  237,   89,   65,   90,  249,
      236,  239,   89,  240,  241,  243,   89,   65,   90,  242,
       89,  246,   90,   89,   89,   90,   90,   89,  250,   90,
       65,   65,   65,   89,  244,   90,  247,  251,   89,  253,
      252,   89,  248,   90,  255,  219,   65,  254,  257,   89,
       89,   90,  260,   89,   65,  262,   65,   65,   65,  256,
      103,  100,   89,   65,   65,   63,   61,  259,   30,   30,
       30,   30,   30,   55,   55,   55,   55,   55,   57,   57,
       57,   57,   57,   60,   60,   60,   60,   60,   62,  103,

       62,   62,   62,   79,   79,   65,   79,   79,   88,   88,
       99,   99,   63,   63,   61,   65,   63,   63,   61,  263,
       56,   31,   31,   11,  263,  263,  263,  263,  263,  263,
      263,  263,  263,  263,  263,  263,  263,  263,  263,  263,
      263,  263,  263,  263,  263,  263,  263,  263,  263,  263,
      263,  263,  263,  263,  263,  263,  263,  263
    } ;

static yyconst flex_int16_t yy_chk[659] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    6,

        6,    6,    8,    8,    8,    8,    8,    8,    8,    8,
        8,  273,  269,    8,    9,    9,    9,    9,    9,    9,
        9,    9,    9,   20,   21,    9,   10,   10,   10,   10,
       10,   10,   10,   10,   10,   22,   26,   10,   23,   24,
       21,   25,   27,   20,   25,   23,   28,   29,   40,   23,
       41,   22,   26,   27,   24,   44,   23,   42,   40,   43,
       42,   71,  262,   29,   41,   45,   28,   43,   46,   28,
       45,   46,   47,   48,   47,   48,   44,   71,   49,   46,
       49,   50,   51,   50,   51,   48,   50,   52,   53,   52,
       53,   54,   51,   54,   49,   53,   54,   57,   66,   57,

       67,   68,   70,   67,   54,   69,   72,   73,   74,   75,
       52,   77,   72,   69,   68,   80,   75,   78,   66,   76,
       70,   73,   76,   81,   82,   77,   84,   85,   86,   87,
       74,   80,   78,   84,  158,   88,   87,   88,  158,   82,
       81,   91,   92,   91,   92,   93,   86,   93,   85,   94,
       96,   94,   96,  104,   95,   97,   95,   97,   98,   91,
       98,   92,   93,   95,   99,  105,   99,   98,  106,  107,
      108,  104,  109,   96,  110,   97,  114,  108,  115,  111,
      107,  112,  113,  105,  106,  110,  111,  113,  112,  109,
      116,  117,  115,  118,  114,  119,  118,  116,  119,  120,

      117,  121,  122,  123,  124,  122,  124,  125,  120,  125,
      260,  126,  125,  126,  133,  124,  126,  127,  121,  127,
      128,  123,  128,  130,  129,  130,  129,  131,  127,  129,
      132,  134,  133,  137,  138,  135,  132,  141,  131,  128,
      135,  145,  136,  130,  136,  139,  134,  139,  137,  140,
      143,  142,  143,  149,  138,  257,  140,  141,  142,  144,
      147,  145,  144,  147,  150,  148,  173,  139,  148,  173,
      150,  149,  151,  152,  151,  152,  153,  151,  153,  154,
      155,  154,  155,  162,  154,  155,  156,  165,  156,  157,
      159,  157,  159,  161,  160,  152,  160,  157,  164,  167,

      161,  170,  168,  162,  168,  241,  156,  164,  172,  169,
      165,  169,  175,  177,  172,  178,  184,  178,  175,  241,
      177,  170,  167,  178,  179,  180,  179,  180,  181,  179,
      181,  182,  183,  182,  183,  188,  181,  184,  187,  190,
      187,  183,  189,  191,  189,  194,  188,  203,  195,  197,
      199,  200,  199,  200,  205,  201,  190,  201,  209,  202,
      191,  202,  207,  194,  195,  197,  254,  203,  199,  207,
      205,  208,  211,  201,  211,  212,  214,  212,  208,  215,
      213,  209,  213,  214,  213,  216,  217,  216,  217,  218,
      221,  218,  231,  224,  215,  224,  225,  221,  225,  226,

      230,  226,  224,  233,  232,  233,  232,  221,  245,  236,
      231,  236,  224,  238,  242,  230,  239,  237,  239,  245,
      226,  232,  223,  233,  237,  239,  240,  246,  240,  238,
      243,  242,  243,  244,  247,  244,  247,  248,  246,  248,
      249,  250,  253,  251,  240,  251,  243,  247,  222,  249,
      248,  252,  244,  252,  251,  210,  198,  250,  253,  255,
      256,  255,  256,  259,  196,  259,  176,  174,  146,  252,
      102,  101,   90,   83,   64,   63,   61,  255,  264,  264,
      264,  264,  264,  265,  265,  265,  265,  265,  266,  266,
      266,  266,  266,  267,  267,  267,  267,  267,  268,   60,

      268,  268,  268,  270,  270,   39,  270,  270,  271,  271,
      272,  272,   37,   36,   33,   19,   18,   17,   13,   11,
        7,    4,    3,  263,  263,  263,  263,  263,  263,  263,
      263,  263,  263,  263,  263,  263,  263,  263,  263,  263,
      263,  263,  263,  263,  263,  263,  263,  263,  263,  263,
      263,  263,  263,  263,  263,  263,  263,  263
    } ;

/* Table of booleans, true if rule could match eol. */
static yyconst flex_int32_t yy_rule_can_match_eol[45] =
    {   0,
0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 
    1, 0, 0, 0, 0,     };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int qgz_flex_debug;
int qgz_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *qgztext;
#line 1 "qgames_scanner.l"
#line 2 "qgames_scanner.l"

#include <stdio.h>
#include "qgames_parser.h"
#include "qgames.h"

void   create_define( char* d );
void   add_parameter_to_def( char* p );
int    define_created;
int    define_head;


#line 739 "qgames_scanner.c"

#define INITIAL 0
#define string 1
#define code 2
#define define 3
#define define_head 4

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int qgzwrap (void );
#else
extern int qgzwrap (void );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  );
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO fwrite( qgztext, qgzleng, 1, qgzout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( qgzin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( qgzin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, qgzin))==0 && ferror(qgzin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(qgzin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int qgzlex (void);

#define YY_DECL int qgzlex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after qgztext and qgzleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	if ( qgzleng > 0 ) \
		YY_CURRENT_BUFFER_LVALUE->yy_at_bol = \
				(qgztext[qgzleng - 1] == '\n'); \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 21 "qgames_scanner.l"




#line 904 "qgames_scanner.c"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! qgzin )
			qgzin = stdin;

		if ( ! qgzout )
			qgzout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			qgzensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				qgz_create_buffer(qgzin,YY_BUF_SIZE );
		}

		qgz_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of qgztext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
		yy_current_state += YY_AT_BOL();
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 264 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_current_state != 263 );
		yy_cp = (yy_last_accepting_cpos);
		yy_current_state = (yy_last_accepting_state);

yy_find_action:
		yy_act = yy_accept[yy_current_state];

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			int yyl;
			for ( yyl = 0; yyl < qgzleng; ++yyl )
				if ( qgztext[yyl] == '\n' )
					   
    qgzlineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 25 "qgames_scanner.l"
{ BEGIN(string); }
	YY_BREAK
case 2:
/* rule 2 can match eol */
YY_RULE_SETUP
#line 26 "qgames_scanner.l"
{ qgzlval = (long)strdup(qgztext); 
                  return TOK_STRING;
                }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 29 "qgames_scanner.l"
{ BEGIN(INITIAL); }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 32 "qgames_scanner.l"
{ BEGIN(INITIAL); yyless(0); return  TOK_SEPARATOR; }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 33 "qgames_scanner.l"
{ BEGIN(INITIAL); yyless(0); return  TOK_SEPARATOR; }
	YY_BREAK
case 6:
/* rule 6 can match eol */
YY_RULE_SETUP
#line 34 "qgames_scanner.l"
;
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 35 "qgames_scanner.l"
;
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 37 "qgames_scanner.l"
{ if( !define_created) 
                          create_define( qgztext );
                      else add_parameter_to_def( qgztext );
                    } ;
	YY_BREAK
case 9:
/* rule 9 can match eol */
YY_RULE_SETUP
#line 41 "qgames_scanner.l"
{ BEGIN(define); }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 42 "qgames_scanner.l"

	YY_BREAK
case 11:
YY_RULE_SETUP
#line 45 "qgames_scanner.l"
{ return TOK_ATTR;      }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 46 "qgames_scanner.l"
{ return TOK_BOARD ;    }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 47 "qgames_scanner.l"
{ return TOK_COLOR;     }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 48 "qgames_scanner.l"
{ return TOK_DIRECTION; }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 49 "qgames_scanner.l"
{ return TOK_DROP;      }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 50 "qgames_scanner.l"
{ return TOK_ENDING;    }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 51 "qgames_scanner.l"
{ return TOK_GAMETYPE;  }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 52 "qgames_scanner.l"
{ return TOK_MOVE;      }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 53 "qgames_scanner.l"
{ return TOK_MOVETYPE;  }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 54 "qgames_scanner.l"
{ return TOK_PIECE;     }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 55 "qgames_scanner.l"
{ return TOK_START;     }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 56 "qgames_scanner.l"
{ return TOK_SYMMETRY;  }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 57 "qgames_scanner.l"
{ return TOK_ZONE;      }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 60 "qgames_scanner.l"
{ define_created = 0; BEGIN(define_head);   }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 63 "qgames_scanner.l"
{ return TOK_AHOGADO;   }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 64 "qgames_scanner.l"
{ return TOK_EMPATA;    }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 65 "qgames_scanner.l"
{ return TOK_GANA;      }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 66 "qgames_scanner.l"
{ return TOK_JUEGA;     }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 67 "qgames_scanner.l"
{ return TOK_IF;        }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 68 "qgames_scanner.l"
{ return TOK_OCUPADO;   }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 69 "qgames_scanner.l"
{ return TOK_OCUPADOENEMIGO;   }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 70 "qgames_scanner.l"
{ return TOK_OCUPADOPROPIO;   }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 71 "qgames_scanner.l"
{ return  TOK_PARA;     }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 72 "qgames_scanner.l"
{ return  TOK_PIERDE;   }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 75 "qgames_scanner.l"
{ 
                  qgzlval = atol(qgztext); 
                  return TOK_NUMBER;
                }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 80 "qgames_scanner.l"
{ 
                  qgzlval = (long)strdup(qgztext); 
                  ((char*)(long)qgzlval)[qgzleng] = 0;
                  return  TOK_WORD; 
                }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 86 "qgames_scanner.l"
/* ignore whitespace */
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 87 "qgames_scanner.l"
/* ignora comentario */
	YY_BREAK
case 39:
/* rule 39 can match eol */
YY_RULE_SETUP
#line 90 "qgames_scanner.l"
{ return  TOK_SEPARATOR ; }
	YY_BREAK
case 40:
/* rule 40 can match eol */
YY_RULE_SETUP
#line 92 "qgames_scanner.l"
{ return  TOK_SEPCODE; }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 93 "qgames_scanner.l"
{ return  TOK_SEPCODE; }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 94 "qgames_scanner.l"
{ return (int) qgztext[0]; }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 96 "qgames_scanner.l"

	YY_BREAK
case 44:
YY_RULE_SETUP
#line 99 "qgames_scanner.l"
ECHO;
	YY_BREAK
#line 1231 "qgames_scanner.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(string):
case YY_STATE_EOF(code):
case YY_STATE_EOF(define):
case YY_STATE_EOF(define_head):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed qgzin at a new source and called
			 * qgzlex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = qgzin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_last_accepting_cpos);
				yy_current_state = (yy_last_accepting_state);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( qgzwrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * qgztext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of qgzlex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					qgzrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), (size_t) num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			qgzrestart(qgzin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) qgzrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);
	yy_current_state += YY_AT_BOL();

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 264 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 264 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 263);

	return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp )
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up qgztext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

    if ( c == '\n' ){
        --qgzlineno;
    }

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					qgzrestart(qgzin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( qgzwrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve qgztext */
	(yy_hold_char) = *++(yy_c_buf_p);

	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = (c == '\n');
	if ( YY_CURRENT_BUFFER_LVALUE->yy_at_bol )
		   
    qgzlineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void qgzrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        qgzensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            qgz_create_buffer(qgzin,YY_BUF_SIZE );
	}

	qgz_init_buffer(YY_CURRENT_BUFFER,input_file );
	qgz_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void qgz_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		qgzpop_buffer_state();
	 *		qgzpush_buffer_state(new_buffer);
     */
	qgzensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	qgz_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (qgzwrap()) processing, but the only time this flag
	 * is looked at is after qgzwrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void qgz_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	qgzin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE qgz_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) qgzalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in qgz_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) qgzalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in qgz_create_buffer()" );

	b->yy_is_our_buffer = 1;

	qgz_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with qgz_create_buffer()
 * 
 */
    void qgz_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		qgzfree((void *) b->yy_ch_buf  );

	qgzfree((void *) b  );
}

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a qgzrestart() or at EOF.
 */
    static void qgz_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	qgz_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then qgz_init_buffer was _probably_
     * called from qgzrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void qgz_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		qgz_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void qgzpush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	qgzensure_buffer_stack();

	/* This block is copied from qgz_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from qgz_switch_to_buffer. */
	qgz_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void qgzpop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	qgz_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		qgz_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void qgzensure_buffer_stack (void)
{
	int num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)qgzalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in qgzensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)qgzrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in qgzensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE qgz_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) qgzalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in qgz_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	qgz_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to qgzlex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       qgz_scan_bytes() instead.
 */
YY_BUFFER_STATE qgz_scan_string (yyconst char * yystr )
{
    
	return qgz_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to qgzlex() will
 * scan from a @e copy of @a bytes.
 * @param bytes the byte buffer to scan
 * @param len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE qgz_scan_bytes  (yyconst char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) qgzalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in qgz_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = qgz_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in qgz_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up qgztext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		qgztext[qgzleng] = (yy_hold_char); \
		(yy_c_buf_p) = qgztext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		qgzleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int qgzget_lineno  (void)
{
        
    return qgzlineno;
}

/** Get the input stream.
 * 
 */
FILE *qgzget_in  (void)
{
        return qgzin;
}

/** Get the output stream.
 * 
 */
FILE *qgzget_out  (void)
{
        return qgzout;
}

/** Get the length of the current token.
 * 
 */
int qgzget_leng  (void)
{
        return qgzleng;
}

/** Get the current token.
 * 
 */

char *qgzget_text  (void)
{
        return qgztext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void qgzset_lineno (int  line_number )
{
    
    qgzlineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see qgz_switch_to_buffer
 */
void qgzset_in (FILE *  in_str )
{
        qgzin = in_str ;
}

void qgzset_out (FILE *  out_str )
{
        qgzout = out_str ;
}

int qgzget_debug  (void)
{
        return qgz_flex_debug;
}

void qgzset_debug (int  bdebug )
{
        qgz_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from qgzlex_destroy(), so don't allocate here.
     */

    /* We do not touch qgzlineno unless the option is enabled. */
    qgzlineno =  1;
    
    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    qgzin = stdin;
    qgzout = stdout;
#else
    qgzin = (FILE *) 0;
    qgzout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * qgzlex_init()
     */
    return 0;
}

/* qgzlex_destroy is for both reentrant and non-reentrant scanners. */
int qgzlex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		qgz_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		qgzpop_buffer_state();
	}

	/* Destroy the stack itself. */
	qgzfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * qgzlex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *qgzalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *qgzrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void qgzfree (void * ptr )
{
	free( (char *) ptr );	/* see qgzrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 99 "qgames_scanner.l"



void   change_to_code_mode(){
    BEGIN(code);
}


void   create_define( char* d ){
    define_created = 1;    
}

void   add_parameter_to_def( char* p ){

}

